### ISSUE TITLE
Discussion about using magda search api in national map

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/nationalmap#1015]
**Please add your input.**

DGA datasets are dynamic and unlimited. Fetch all datasets and group them by organisations (publishers) is time consuming and does not provide good ux. That approach will also have high demand on both RAM and CPU. Therefore fetch a small number of datasets most relevant to what user is searching is probably a good solution. However, this new approach likely needs new design.

The demo, catalogue group `Selected Datasets from data.gov.au` at https://nationalmap.dev.saas.terria.io, lets user do free text search on DGA and fetches most relevant results (up to a limit, e.g. 25). Those results are grouped by publishers. A new search can be started at wish and the results are accumulated. There are many UI/UX design issues need to consider.

1. Results of the same search should be paginated as some search may have large number of hits.
2. User should be able to mark interesting results and have a filtered view of them.
3. Indicate which datasets from which search criteria.
4. Share link functionality needs to support dynamic catalogue items.
5. Some publishers, such as AURIN, might have enormous number of layers in one dataset.  Loading many of such datasets into memory will quickly exhaust RAM. Probably need better model loading/unloading management.
6. Should old search results be cleared out after getting new results? Currently they are accumulated.
7. A use case scenario
7.1 Navigate to `Explore map data` -> `Selected Datasets from data.gov.au`.
7.2 Input free text `Water Observations from Space 25m Water Summary` to start search.
7.3 Nine datasets are found and become members of two sub-groups `Geoscience Australia[Water...]` and `Geoscience Australia (S)[Water...]`.
7.4 Navigate to  `Geoscience Australia[Water...]` -> `Satellite Imagery Fractional Cover Percentiles Annual - Bare Soil` -> `Water Observations from Space` -> `Water Observations from Space 25m Filtered Water Summary (WOfS Filtered Statistics)`.
7.5 The above item is sourced from https://ows.dea.ga.gov.au/?service=WMS. (It turns out to be identical to https://map.geo-rapp.org/#share=s-bIcqMVDnuil9aHJs3ELIegj1wU2 that is sourced from https://ows.services.dea.ga.gov.au/.) Add it to workbench.
7.6 This workbench item can not be shared with the current implementation.
8. Issues with the above scenario
8.1 A dataset from `wms` is actually hierarchical, containing sub groups and each sub group has many layers.
8.2 It is not easy to get to the wanted layers without filtering out the noise.
8.3 It seems that the results should be ordered by relevance (score) instead of by name.

**Comment by t83714** [comment]
That looks cool~
The prompt box seems not very user friendly.
Not very familiar with TerriaJs UI but is that possible to customise the description area when the user selects the data.gov.au group?
Is that possible to modify this view and make it show the customised UI when the selected group is DGA one?
https://github.com/TerriaJS/terriajs/blob/next/lib/ReactViews/Preview/DataPreview.jsx

**Comment by mwu2018** [comment]
@t83714 The prompt box is gone now.
