### ISSUE TITLE
NationalMap - v8 - add missing (GA topo) base map

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1016]
Currently in v8 https://beta.nationalmap.terria.io/ we have only 7 base maps: 

![image](https://user-images.githubusercontent.com/18452161/111277394-83d12f80-868c-11eb-9b51-8c07750d36b8.png)

In v7 we have GA's Australian Topography map: 
![image](https://user-images.githubusercontent.com/18452161/111277538-abc09300-868c-11eb-9bbe-aed63c45a0a3.png)

**Comment by nf-s** [comment]
Done
