### ISSUE TITLE
GA has moved the Transmission Lines and Substations services

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#1018]
- [ ] New URL to be changed on both versions: v7 and v8

Geoscience Australia has moved the Transmission Lines and the Substation webservices from the NationalMap catalogue here:

https://nationalmap.gov.au/#share=s-1CS5HslHRNYmvieQATbLxn7miw9

As you can see the services no longer work.

Looking at the GA website they've been moved:

<img width="830" alt="Screen Shot 2021-03-25 at 18 06 37" src="https://user-images.githubusercontent.com/5283003/112432323-da2d2500-8d94-11eb-89c0-9f5d9f69b5ae.png">

The new service is the one on the left, with the service URL:

https://services.ga.gov.au/gis/rest/services/Foundation_Electricity_Infrastructure/MapServer

We need to update the service URL we use.

**Comment by mwu2018** [comment]
Also need to update URL for `National Datasets` -> `Energy` -> `Electricity Infrastructure` -> `Generation` -> `All Power Stations`.
