### ISSUE TITLE
NatMap - AREMI - re-instate the Research Group of data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1019]
AEMO has reached out to inform that the former AREMI Research data group hasn't been transferred to NationalMap. 

Use https://staging.aremi.d61.io/renewables/ 
https://staging.aremi.d61.io/renewables/#share=s-zZTl4YIGQbOXBAFf

![image](https://user-images.githubusercontent.com/18452161/112615937-41bba100-8e77-11eb-861d-5f752078bb4d.png)

**Comment by mwu2018** [comment]
The datasets under group `Research` -> `National Energy Analytics Research (NEAR) Program` -> `DNSP Zone Substations` can not be visualised due to `CORS` errors. See
https://staging.aremi.d61.io/renewables/#share=s-mNG5B2sgsmv6E7xR
