### ISSUE TITLE
NatMap - add Catchment Scale Land Use 2020 - v8

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1020]
Ideally we would make the change in v7 and v8 because of delays with v8 migration. 
if not possible due to time constraints, v8 is the priority, followed by v7 catalogue.

Add the latest version of the Catchments Scale Land Use of Australia: 
The WMS for the updated Catchment scale land use of Australia are here:

ESRI WMS Service:
https://www.environment.gov.au/mapping/rest/services/abares/CLUM_50m/MapServer

The OGC compliant WMS Service:
https://www.environment.gov.au/mapping/services/abares/CLUM_50m/MapServer/WMSServer

- Under Agriculture group replace 2018 datasets with 2020 
- 
![image](https://user-images.githubusercontent.com/18452161/112907381-75c5e900-9139-11eb-8bd8-3b12b4091aab.png)

**Comment by mwu2018** [comment]
@AnaBelgun Please confirm that the existing 5 datasets provided by https://www.asris.csiro.au/arcgis/rest/services/abares/clum_50m_2018/MapServer will be replaced by
https://www.environment.gov.au/mapping/rest/services/abares/CLUM_50m/MapServer. It is replacement instead of addition.

**Comment by AnaBelgun** [comment]
@mwu2018 yes, it's a replacement, not an addition. Thank you.

**Comment by mwu2018** [comment]
Changes can be verified here
https://nationalmap.dev.saas.terria.io/#share=s-jB7GlOxQ8zYLERkzuYz1JQQCTwD

**Comment by AnaBelgun** [comment]
@mwu2018 hi, I think we're missing 2 layers from the service: 
When you add this https://www.environment.gov.au/mapping/rest/services/abares/CLUM_50m/MapServer to the map, you get this list of layers: 
https://nationalmap.dev.saas.terria.io/#share=s-aHzMBlz4L8JqNwuuClk0fcVhJPM
![image](https://user-images.githubusercontent.com/18452161/114498718-f3c0de80-9c67-11eb-9aeb-fb616e87184b.png)

We're missing: 1) Date of mapping; 2) Scale of mapping 

Is it possible to add them as well please?

**Comment by mwu2018** [comment]
Oh I thought those two were not needed. Yes, I can add them in.

**Comment by AnaBelgun** [comment]
np @mwu2018 luckily they noticed. thank you

**Comment by mwu2018** [comment]
@AnaBelgun I will also remove two duplicates (transmission lines and substations in Energy group and their URLs are incorrect too) in https://nationalmap.dev.saas.terria.io/#share=s-vrEhNnCQPHlc0CT23AsE8rZCqb0. Those two datasets are already in Electricity Infrastructure -> Transmission
