### ISSUE TITLE
NatMap - AREMI - EV - electricity data not available

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1022]
Steps to reproduce: 
- NationalMap either v7 or v8
- Energy - Electric Vehicle
- Electricity infrastructure 
- Distribution Cables and Distribution Substations - not available 

![image](https://user-images.githubusercontent.com/18452161/113636762-7c62dc00-96b6-11eb-9e49-49c9ee1e0730.png)

the data is part of the https://nsw-digital-twin-data.terria.io/geoserver/ows 

the issue affects digital twins and nationalmap

**Comment by mwu2018** [comment]
@AnaBelgun Do we have permission to use credentials from api.transport.nsw.gov.au in Vic DT? We previously decided not to use Western Australia's credentials for National datasets Energy access in Vic DT.

**Comment by AnaBelgun** [comment]
hi @mwu2018 ok, not yet; I didn't know we need permission to access that API. Unfortunately I cannot ask for them before the announcement. Is it possible to hide/remove that subgroup under EV data group? We have similar data under Electricity; these two datasets under EV are duplicates.

**Comment by mwu2018** [comment]
The datasets can be verified here:
http://staging.nm.terria.io/#share=s-4Uv57Hg4PPo9uxczBztgwdIVp6E
