### ISSUE TITLE
NatMap - AREMI - Wave Atlas - make available 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1025]

**Comment by steve9164** [comment]
To check if it's done.

**Comment by nf-s** [comment]
I need to add CSW + WPS-group to catalog-converter

**Comment by nf-s** [comment]
This has been added to dev/test catalog - here is the PR to push to production https://github.com/TerriaJS/saas-catalogs-public/pull/3

A few issues:

- CSW is currently crashing in prod, so a new terriajs version will need to be pushed before updating catalog

- WPS `contextItem` hasn't been ported to v8 - so when using WPS functions you won't get the gray "Analysis Study Area" thing (https://github.com/TerriaJS/terriajs/issues/5480)
- 
![image](https://user-images.githubusercontent.com/6187649/117438129-7c375400-af74-11eb-812d-ed18dd46e451.png)

**Comment by nf-s** [comment]
I'm going to mark this as closed. Wave Atlas datasets will be available when terriajs has been upgraded and this PR has been mreged https://github.com/TerriaJS/saas-catalogs-public/pull/3
