### ISSUE TITLE
NationalMap - Esri FS - projection issue

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1029]
We want to report a possible issue/bug with interoperability of the new Nationalmap Beta (https://beta.nationalmap.terria.io/).

We have tried to add a feature layer hosted at
https://services1.arcgis.com/wfNKYeHsOyaFyPw3/ArcGIS/rest/services/Corner_Markers/FeatureServer/0
The layer is added to the workbench pane nut it fails to draw and application returns the following error message:
![image](https://user-images.githubusercontent.com/18452161/117084360-5a7a7900-ad8a-11eb-85d6-709545d674ba.png)

 

In contrast, another feature layer works perfectly fine
https://services5.arcgis.com/OvOcYIrJnM97ABBA/arcgis/rest/services/Australian_Aged_Care_Services_WFL1/FeatureServer/0

The only apparent discrepancy in the data is the projection/datum – the first dataset that we have the issue with is in GDA2020. Does TerriaJS support GDA2020 EPSG 7844, or it could be something else?

**Comment by nf-s** [comment]
We use a library to translate EPSG codes into proj4 string

https://github.com/TerriaJS/terriajs-server/blob/65c12db1fb20bafc4564f55ad6874df2d2fea77c/lib/controllers/proj4lookup.js#L9

It doesn't have proj4 string for EPSG 7844 (either does https://epsg.io/7844)

So I have added one manually

**Comment by nf-s** [comment]
PR https://github.com/TerriaJS/terriajs-server/pull/142

**Comment by na9da** [comment]
Have merged PR TerriaJS/terriajs-server#142 - should be fixed when Saas gets deployed with a new version of terriajs-server
