### ISSUE TITLE
NationalMap - ABS.stat will be HTTPS

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1030]
The  ABS.Stat API, used by the current version of National Map will  use HTTPS instead of HTTP.  It is possible that this change may have an impact on National Map.

The ABS.Stat API will be upgraded to communicate over HTTPS, scheduled for 24th of May 2021, 9am-11am.  From that point in time, any calls made to http://stat.data.abs.gov.au will be automatically redirected to https://stat.data.abs.gov.au.   

We cannot guarantee your current  HTTP calls will seamlessly continue to operate with a (HTTP 301) redirect in place.  Therefore, on the above time or after, we strongly advise you to update your client configurations to directly call the HTTPS url, https://stat.data.abs.gov.au.

If you would like to test your API client against a similar HTTPS API endpoint before the change, we suggest you make a test call against the new ABS Data API (Beta). If your service can successfully call the ABS Data API (Beta) then it will work once HTTPS is enabled on the ABS.Stat API.  
Example test API calls:   
•	XML data: https://api.data.abs.gov.au/data/ABS,RES_DWELL/1.1GSYD+1RNSW.Q?detail=Full&startPeriod=2019-Q4&endPeriod=2020-Q1 
•	JSON data: https://api.data.abs.gov.au/data/ABS,CPI/1.10001.10.1.Q?detail=Full&startPeriod=2021-Q1&endPeriod=2021-Q1&format=jsondata 
•	XML structure: https://api.data.abs.gov.au/dataflow/ABS/CPI?references=descendants
Please don't hesitate to contact us if you need further assistance with the change to HTTPS.

**Comment by nf-s** [comment]
Hi @AnaBelgun this will only be an issue for v7 NationalMap. The new SDMX in v8 will use HTTPS.

Example v7 catalog item:

https://github.com/TerriaJS/NationalMap-Catalog/blob/3bef5618dd68eb475814e4c552079b301df0e4f6/build/abs-itt_big.json#L32

**Comment by AnaBelgun** [comment]
Awesome, that means we can push forward according to plan (i.e. release sdmx on natamap end of May)?

**Comment by AnaBelgun** [comment]
To check when releasing the NatMap end of May

**Comment by nf-s** [comment]
In beta
