### ISSUE TITLE
Land Parcel and Property group to move under Boundaries

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1033]
Currently the Land Parcel and Property Group sits under Energy. 
It should be moved under Boundaries. 
![image](https://user-images.githubusercontent.com/18452161/118566861-058e2800-b7b8-11eb-9408-43aa370fa676.png)

Update 26 Aug 21:
- remove ACT group because of low performance and poor visualisation

**Comment by wibily** [comment]
in dev but needs to be promoted to test/prod. Current v7 prod nationalmap catalog is in s3. This will not change after ejecting beta.nationalmap from saas

**Comment by AnaBelgun** [comment]
done in https://nationalmap-2021-09-03.nm.terria.io/
