### ISSUE TITLE
Oil and gas pipelines to move under Infrastructure

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1034]
Currently the Oil and Gas pipelines are under Energy. 
The layer should move under Infrastructure. 

![image](https://user-images.githubusercontent.com/18452161/118567572-5eaa8b80-b7b9-11eb-9fb2-34ecfb382f4d.png)

**Comment by wibily** [comment]
same situation as nationalmap#1033

**Comment by AnaBelgun** [comment]
Done in https://nationalmap-2021-09-03.nm.terria.io/
