### ISSUE TITLE
NatMap - AREMI - Bioenergy - WA v7-v8 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1035]
A couple of datasets available in v7 are not in v8/beta version. 
v7 
![image](https://user-images.githubusercontent.com/18452161/120745511-a6af0980-c540-11eb-9061-b45dd2bd1d4b.png)

Cereal Straw: 
https://catalogue.data.wa.gov.au/dataset/0e13aba1-447e-4ee5-80b5-67353a1e34ce/resource/cc665742-af91-41c3-a946-e9bddb837180/download/cereal-data130618.csv

Grape marc: 
https://catalogue.data.wa.gov.au/dataset/0612cfcd-e28c-422d-8bf0-317e7d14447a/resource/09a3b358-4b84-45de-b8a3-0a7f3263cfda/download/grape-marc-dw.csv

v8
![image](https://user-images.githubusercontent.com/18452161/120745489-9a2ab100-c540-11eb-9612-0c83fe23565b.png)

**Comment by AnaBelgun** [comment]
https://github.com/TerriaJS/saas-catalogs-public/pull/30

**Comment by nf-s** [comment]
I have added "Grape Marc'" but not - "Cereal Straw" as it requires https://github.com/TerriaJS/terriajs/issues/5213 for correct region mapping

**Comment by nf-s** [comment]
Re-added Cereal Straw https://github.com/TerriaJS/natmap-catalog-v8/pull/29
