### ISSUE TITLE
NationalMap - Residential Population Density layer bug and name change

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1036]
The current data service for residential population density doesn't display data for the bottom of the map (parts of Victoria and Tasmania) and it's name needs updating. 

- [ ] Data visualisation bug 

- go  to NationalMap (either Beta or v7) 
- go Social and Economic - Population Estimates - add Residential Population Density https://beta.nationalmap.terria.io/#share=s-bSVqReKX9TEtK31SakW6wmDRzpZ 
- The bottom of the map is cropped (no data showing for parts of Vic and Tas) 
![image](https://user-images.githubusercontent.com/18452161/120949066-f717a880-c786-11eb-9c76-d0e8ca2b116d.png)
- upon checking the service http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer, it works correctly in other apps especially when using ttps://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer?f=jsapi
- when using 2d map, errors remain with Tas, but data is showing for Victoria

- [ ] Name should be changed to _Residential **Dwelling** Density_ 
- [ ] TerriaJS/terriajs#5650.
- [ ] https://github.com/TerriaJS/saas/issues/169
- [ ] https://github.com/TerriaJS/terrace/issues/172

**Comment by mwu2018** [comment]
It appears that the bbox is too small. Probably due to incorrect `fullExtent` and/or `initialExtent` values from the server http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer?f=json
```
"initialExtent": {
  "xmin": -4449731.015830827,
  "ymin": -5166939.921030828,
  "xmax": 3613268.9841691735,
  "ymax": -909939.9210308276,
  "spatialReference": {
    "wkid": 3112,
    "latestWkid": 3112
  }
},
"fullExtent": {
  "xmin": -4083231.015830827,
  "ymin": -4973439.921030828,
  "xmax": 3246768.984169173,
  "ymax": -1103439.9210308278,
  "spatialReference": {
    "wkid": 3112,
    "latestWkid": 3112
  }
},
```

**Comment by mwu2018** [comment]
It is most likely due to incorrect values of extent in layer 0 of the following query
http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer/layers?f=json.

It is speculated that the layer extents had not been updated after TAS data were added.

Should raise it to GA.

**Comment by mwu2018** [comment]
By setting trait `rectangle = {east: 158, north: -8, south: -45, west: 109}`, the dataset's extent will be overridden and corrected:
![image](https://user-images.githubusercontent.com/41275384/126092948-b9cddce4-c12c-45d0-990d-649127537cae.png)
 However, there are a few defects in showing the dataset, regardless if the rectangle trait is overridden:
![image](https://user-images.githubusercontent.com/41275384/126093582-5e9df5b7-f944-4311-ab97-13d64286b5e4.png)

1. The radius used to calculate a dwelling density is based on zooming level. When fully zoomed-out, the dwelling density is actually per 2km radius, not per 100 meters.
2. The legend is incorrect.

**Comment by mwu2018** [comment]
Change data type to `ArcGisMapServerCatalogGroup` in order to render each layer. Blocked by https://github.com/TerriaJS/terriajs/issues/5650.

**Comment by mwu2018** [comment]
Rendering each layer independently has some side-effects. An initial message pops up to inform the user (once only).
![image](https://user-images.githubusercontent.com/41275384/126731580-7bb6df74-d337-46cc-b0e6-d63442340011.png)

**Comment by mwu2018** [comment]
- In 3D mode, the feature info is always available to any zooming levels as long as map items are visiable.
- Feature info is correct.
- Legends are correct.
![image](https://user-images.githubusercontent.com/41275384/126732000-4ee886c8-8d1b-4a61-8a1d-bba2a661d814.png)

**Comment by mwu2018** [comment]
In 2D mode, the feature info is not available to zooming levels outside the layer's scale range.
![image](https://user-images.githubusercontent.com/41275384/126732363-47d7defb-f973-4f23-ba0e-f7bf3b2c14f6.png)

**Comment by mwu2018** [comment]
A non-map-server-group version now provides correct feature info data:
![image](https://user-images.githubusercontent.com/41275384/126929926-5797f753-3dc7-4b62-9c9b-e703510d102a.png)
This version seems good except for the legends that are yet to be fixed.

**Comment by mwu2018** [comment]
Legends work-around:
![Uploading image.png…]()

**Comment by AnaBelgun** [comment]
Done, we leave it as is; Custodian is working on metadata and legends and the service URL will remain the same, hence any changes will be harvested automatically.
