### ISSUE TITLE
NationalMap - CLUM 2020 update 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1042]
The CLUM 2020 data needs to be updated under the Land Cover and Use data group as well. Right now it's only updated in Agriculture. 

Agriculture group: 
![image](https://user-images.githubusercontent.com/18452161/126755421-da45f0a7-ce24-4ff4-9456-23ceb3d0b723.png)

Land cover and use: 
![image](https://user-images.githubusercontent.com/18452161/126755460-efaa6fe8-d1cf-4943-a08d-ce88a0dc61c4.png)

**Comment by mwu2018** [comment]
See https://nationalmap.dev.saas.terria.io/#share=s-cndsi9iwLgWWDxUMUbxZ64pBSTe

**Comment by AnaBelgun** [comment]
Updated in https://nationalmap-2021-09-03.nm.terria.io/
