### ISSUE TITLE
NationalMap - Nov-Dec 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1043]
**Higher priority:** 

### PRs to merge:
- [x] https://github.com/TerriaJS/natmap-catalog-v8/pull/34
- [x] https://github.com/TerriaJS/terriajs/pull/6056
- [x] https://github.com/TerriaJS/terriajs/pull/6057
- [x] https://github.com/TerriaJS/saas-catalogs-public/pull/110

### Data Catalogue: 
- [x] https://github.com/TerriaJS/nationalmap/issues/1094
- [x] https://github.com/TerriaJS/nationalmap/issues/1050

### TerriaJS:
- [x] https://github.com/TerriaJS/nationalmap/issues/1113
- [x] https://github.com/TerriaJS/nationalmap/issues/1090
- [x] https://github.com/TerriaJS/nationalmap/issues/1099
- [x] https://github.com/TerriaJS/nationalmap/issues/1100
- [x] https://github.com/terriajs/neii-viewer/issues/219
- [x] https://github.com/TerriaJS/terriajs/pull/6049
- [x] https://github.com/TerriaJS/nationalmap/issues/1104
- [x] https://github.com/TerriaJS/terriajs/pull/6048
- [x] https://github.com/terriajs/terriajs/issues/5379

**Post release in production** 
- [ ] https://github.com/TerriaJS/nationalmap/issues/1088
- [ ] https://github.com/TerriaJS/nationalmap/issues/1093

**Comment by AnaBelgun** [comment]
Update 4 Jan 22: Pending testing results from GA.

**Comment by AnaBelgun** [comment]
Reminder @steve9164 - to re-release a version of NatMap with newest TerriaJS

**Comment by wibily** [comment]
Ana: spoke with GA and released onto pre-prod and it works. Vic state data is visible. @steve9164 to make a new deploy and send them a link

**Comment by AnaBelgun** [comment]
Done
