### ISSUE TITLE
NationalMap - Base maps update

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1044]
- [x] add  “National Base Map – GreyScale” https://services.ga.gov.au/gis/rest/services/NationalBaseMap_GreyScale/MapServer as another option in Map Settings > Base Map
- [x] “Australian Topography” should be renamed to the correct name “National Base Map”
- [x] NationalMap_Colour_Topographic_Base_World_WM, http://services.ga.gov.au/gis/rest/services/NationalMap_Colour_Topographic_Base_World_WM/MapServer 
Replacement service: https://services.ga.gov.au/gis/rest/services/NationalBaseMap/MapServer

**Comment by wibily** [comment]
![Screen Shot 2021-08-18 at 2.53.24 pm.png](https://images.zenhubusercontent.com/60529acfe1747f58c17d9340/4a3086b8-a54f-4a60-a691-f323925560a5)

**Comment by AnaBelgun** [comment]
updated in https://nationalmap-2021-09-03.nm.terria.io/
