### ISSUE TITLE
NationalMap - YDYR polishing

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1045]
Update 29 Sep 21: this is ready to publish

Proposed changes: 

**- Name of the data group** - Analysis Tools - keep as is
**- Name of the data** - Your Data Your Regions (Beta)

### Data page description 
YourDataYour Regions (YDYR) is an API for the conversion of data between different Australian geographic boundaries: a process often referred to as geographic correspondence. 

Data is often captured for specific purposes, using particular geographies or administrative boundaries, The regions and geographies used invariably change over time or vary according to the purpose of the analysis. This creates the need for data to be converted between regions to enable its re-use beyond the original purpose, adding to it value. 

YDYR can help users maximise the use of new and existing data by making it available for analysis, integration and display across a range of geographic regions. 

Developed by CSIRO's Data61 in partnership with the Australian Bureau of Statistics (ABS), YDYR modernises the ABS geographic correspondence workflow through the incorporation of machine learning techniques which model the relationship between users' own data and various data collected and maintained by the ABS. 
This is a beta version of the tool limited to a small number of users for evaluation process. Update to a production version of the tool will depend on user feedback and assessment of the results. 

### User Guide
**Users should note that the use of different algorithms may produce different results. All outputs from YDYR are modelled outcomes that should be used and interpreted with caution. The results are not representative of official statistics from the ABS or CSIRO's Data61.** 

The tool is currently under evaluation and users need to register their interest in testing it by emailing info@terria.io.
It can be tested on both the [ydyr.info ](https://ydyr.info/ )website and NationalMap, providing users two options for running the re-aggregation process. You will be prompted to enter username and password to run the analysis (at the last step). 

### Getting started to test YDYR on NationalMap
The YDYR correspondence process includes 4 simple steps: 
1. **Specify the data source** - example, in the catalogue search and select a [Statistical Area 2](https://www.abs.gov.au/ausstats/abs@.nsf/lookup/by%20subject/1270.0.55.001~july%202016~main%20features~statistical%20area%20level%202%20(sa2)~10014)
 (SA2+) based dataset. 

Or use your own data (by adding it to the workbench). 
[Image HERE](https://csiroau.sharepoint.com/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/D61%20xBU%20Ecosystem/YDYR/YDYR%20NatMap%20Add%20data%20Capture.PNG)
![image](https://user-images.githubusercontent.com/18452161/133954094-788bee8a-2658-4449-afcb-dd5dec140493.png)

The data should contain at least two columns:
- a geography column containing unique codes (e.g. SA2)
- a data column containing the values to be converted. For example counts of business by SA2 

Once the data has been added to the map, the YDYR analytics interface will automatically populate the Region Column and Data Column fields. 

[Image HERE](https://csiroau.sharepoint.com/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/D61%20xBU%20Ecosystem/YDYR/YDYR%20NatMap%20YDYR%20sections%20Capture.PNG)
![image](https://user-images.githubusercontent.com/18452161/133947631-d4de22eb-cc95-4af7-ad79-d08c5a25990d.png)

**2. Specify the target geography**
Under the Output Geography heading, select the drop down box and specify the geography which you would like to convert (for example Local Government Areas 2016). 

**3. Specify Algorithms**
Select one of the 2 predicting models available for converting data between the input and output geography:
- **Negative Binomial** - This uses a discrete probability distribution. It models the number of successes in a sequence of independent and identically distributed Bernoulli trials before a specified (non-random) number of failures occurs. This approach potentially provides a better quality result because it may have a stronger relationship with the source data a user wants to convert. Due to the complexity of this approach and interpretation confidence interval, this should be used by advanced users only. 
- **Population Weighted** - This uses population data modelled to address locations to convert data between two sets of geographies. Population based correspondences are typically used to transform social datasets and they're standard correspondence approach used by the ABS. They make the assumption that the distribution of any input dataset is related to the distribution of population. 

**4 Run the analysis**
You'll be prompted to enter access credentials.
Execute the tool. This will convert the source data file from the selected input to output geography. 
The NationalMap workbench (left panel) will be populated with a description of the re-aggregation and a new layer, displaying the output geography and a drop down section to filter the Displaying variable (e.g. Population weighted).

**Comment by wibily** [comment]
![Screen Shot 2021-08-18 at 2.55.37 pm.png](https://images.zenhubusercontent.com/60529acfe1747f58c17d9340/ad874e4d-9b27-4e4c-8918-6d38d70cc4a8)

We need to update the wording on the right hand panel
- how people can get the auth login
- polish the steps

**Comment by wibily** [comment]
Nanda: where does text come from
nfs: text is hardcoded in catalog function

**Comment by meh9** [comment]
YDYR doesn't work at the moment, I suspect it's because the auth fields are missing?

It returns a HTTP 502 with no real error message.

**Comment by nf-s** [comment]
Back up!

**Comment by nf-s** [comment]
Hi @AnaBelgun I have updated YDYR description - but I'm not sure where you'd like me to put the "User guide"

**Comment by AnaBelgun** [comment]
hi @nf-s I was thinking to put it on the front page to replace the current instructions.l Basically the whole section above to replace the current one.
![image](https://user-images.githubusercontent.com/18452161/135556172-79534366-ed20-4ce7-a2d6-db429649ccf5.png)

**Comment by nf-s** [comment]
Ok too easy, i'll update it now
