### ISSUE TITLE
NationalMap - update Satellite imagery group 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1047]
Update satellite imagery group based on DEA maps version. Check if possible to connect to DEA maps (GA) catalogue directly. 

![Screen Shot 2021-08-18 at 2.41.17 pm.png](https://images.zenhubusercontent.com/60529acfe1747f58c17d9340/8750889f-5edd-4dd4-b8a2-c4132c7feeaa)![Screen Shot 2021-08-18 at 2.40.56 pm.png](https://images.zenhubusercontent.com/60529acfe1747f58c17d9340/7374f14c-c04c-439d-a43a-e70ef7bff2de)

**Comment by wibily** [comment]
Ana: it would be easier to connect to their file on github as they make changes regularly.
nfs: Not possible, but easy to add in the model layer
Ana: worst case scenario, copy paste in

**Comment by wibily** [comment]
nationalMaps need to be in sync with DEA groups which is connected to their files in github

**Comment by wibily** [comment]
NB: this will be a terriajs change

**Comment by AnaBelgun** [comment]
dependent on this https://github.com/TerriaJS/terriajs/issues/5754

**Comment by na9da** [comment]
Fixed in latest `main` branch by this PR - https://github.com/TerriaJS/terriajs/pull/5776

Just need to update the catalog here after upgrading to a new version of terriajs (v8.1.x).
[Sample catalog config](https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/terria/dea-maps-v8.json).

**Comment by na9da** [comment]
I can see that https://nationalmap-v8-pre-release.nm.terria.io/ has an extra item under `Satellite Images` called `World Bathymetry Imagery` which does not exist in the other catalog. If we reference the group from other catalog then the bathymetry dataset will go missing. What should be done here @AnaBelgun ?

**Comment by AnaBelgun** [comment]
@na9da please remove World bathymetry imagery from the Satellite Imagery group. I can see the data already exists in Marine & Oceans - Bathymetry

**Comment by AnaBelgun** [comment]
updated
