### ISSUE TITLE
NationalMap - Search 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1048]
search - we should be able to search through entire catalog quickly (even if it is just catalog item names)
Maybe catalog-indexer tool - which loads all dynamic groups and shoves model ids/names into JSON file which is loaded into terriajs (see Story v2.0 - handle re-arranging catalogue not to break sharelinks terriajs#5646)

**Comment by wibily** [comment]
things to consider
- authenticated catalogs
- remote catalog changes
- will it be loaded into the client?

**Comment by na9da** [comment]
For better search performance we could consider exploring one of these text indexing libraries instead of raw JSON - https://github.com/TerriaJS/terriajs/issues/5590. We use [minisearch](https://lucaong.github.io/minisearch/) for item search but looking at others with better language support.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5774/
