### ISSUE TITLE
NationalMap - add NBN data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1050]
I couldn't find any API, just this: https://www.nbnco.com.au/learn/rollout-map
On data.gov.au, these: https://data.gov.au/search?page=1&q=nbn

**Comment by wibily** [comment]
Ana was unable to find NBN data

**Comment by wibily** [comment]
Nick: NBN co also have vector tiles, so might be worth investigating?

**Comment by nf-s** [comment]
Sorry i lied, they have a Carto image tile layer https://cartocdn-gusc.global.ssl.fastly.net/nbncoadmin/api/v1/map/nbncoadmin@f74d0236@7439c4cb26257aed56385cc33d11204e:1631606329341/0,1,2,3,4,5,6,7,8,9/13/7451/5176.png

**Comment by AnaBelgun** [comment]
Update 26 Nov 21: 
we should add the WMS from Dept of Communications: https://programs.communications.gov.au/geoserver/national-broadband-network/wms?request=GetCapabilities

It is strange the data has a preview in data.gov.au but when searched for in NationalMap, users can't find it; also, when opening in NationalMap from dga, it doesn't work. 

We should add the data under Communications group.

**Comment by AnaBelgun** [comment]
done
