### ISSUE TITLE
NatMap - Add Related Maps tab

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1054]
Add Related Maps tab (next to About) and include the following: 

**NSW Digital Twin** https://nsw.digitaltwin.terria.io/
**Image:** https://github.com/TerriaJS/qld-digital-twin/blob/master/wwwroot/images/nsw-dt.png
**Text:** The NSW Spatial Digital Twin aims to respond to the NSW State Infrastructure Strategy by developing a 4D (3D+time) Foundation Spatial Data Framework. The goal is to help the NSW Government with infrastructure assets planning and management, integration with land use planning, data collaboration, and sharing.

**QLD Digital Twin** https://qld.digitaltwin.terria.io/
**Image:** [HERE ](https://csiroau.sharepoint.com/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/QLD%20Digital%20Twin/Related%20Maps/QLD%20Digital%20Twin.PNG) and with this PR: https://github.com/TerriaJS/qld-digital-twin/pull/248 
**Text:** The QLD Spatial Digital Twin is an evolving 4D data platform that enables users to discover, visualise, analyse and share a rich range of datasets in a real world context, to enable better planning and decision making. It is an initiative of Advance Queensland and the Department of Resources in partnership with CSIRO-Data61

**Digital Earth Australia** https://maps.dea.ga.gov.au/ 
**Image:** https://github.com/TerriaJS/qld-digital-twin/blob/master/wwwroot/images/dea.png
**Text:** https://github.com/TerriaJS/qld-digital-twin/blob/master/lib/Views/RelatedMaps.jsx#L97
<p>
Digital Earth Australia (DEA) Map is a website for map-based access to DEA’s products, developed by Data61 CSIRO for Geoscience Australia. DEA uses satellite data to detect physical changes across Australia in unprecedented detail. It identifies soil and coastal erosion, crop growth, water quality and changes to cities and regions.

**National Drought Map** https://map.drought.gov.au/
**Image:** https://github.com/TerriaJS/nsw-digital-twin/blob/main/wwwroot/images/droughtmap.jpg
**Text:** The DroughtMap is a platform built for the Australian Government to assist with planning and management of drought effects in Australia.

**AURIN Map** https://map.aurin.org.au/
**Image:** https://github.com/TerriaJS/nsw-digital-twin/blob/main/wwwroot/images/aurin-map.jpg
**Text**: AURIN Map provides access to datasets on urban infrastructure for urban researchers, policy and decision makers.

**Comment by AnaBelgun** [comment]
To be included as part of config changes when releasing stand alone NatMap

**Comment by mwu2018** [comment]
Superseded by https://github.com/TerriaJS/nationalmap/pull/1052
