### ISSUE TITLE
NationalMap - Sep 21 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1055]
Release when the following tasks are completed:
- [ ] https://github.com/TerriaJS/terriajs/issues/5650
- [ ] https://github.com/TerriaJS/nationalmap/issues/1054
- [ ] terriajs >= v8.0.1 is released and updated in nationalmap.
- [ ] Record history and merge [PR](https://github.com/TerriaJS/natmap-catalog-v8/issues/24)

**Comment by AnaBelgun** [comment]
@mwu2018 is this still needed?

**Comment by mwu2018** [comment]
Let's change it into an official release ticket.

**Comment by AnaBelgun** [comment]
This ticket is superseded by the Beta release mega ticket; hence closing to avoid confusion
