### ISSUE TITLE
Investigate & fix Telecommunications in new developments dataset

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1062]
The telecommunications in new developments data is not working in NatMap v8. 
To test: 

v7: 
- go to Communications - Telecommunications in new developments https://nationalmap.gov.au/#share=s-tuiCIN4yuhauHKpFtWFBTDGUC9e; it works (taking long to load but it does + metadata available)

![image](https://user-images.githubusercontent.com/18452161/132595706-a62887d2-e1ff-4977-9687-7889e970deea.png)

v8: 
- https://beta.nationalmap.terria.io/#share=s-6a7LNu3YRm130cWgyWvqg6ghqkA

![image](https://user-images.githubusercontent.com/18452161/132595792-36a9263c-f964-4c2f-9bae-e69f005de4ed.png)

Data source: data.gov.au 
https://data.gov.au/dataset/ds-dga-7a5ba140-82c2-4746-b579-e59d524ae88d/details

**Comment by mwu2018** [comment]
Fixed now.
https://nationalmap-2021-09-03.nm.terria.io/#share=s-um2K8ouOdmP6vVLLVPCF6XCKKnw
