### ISSUE TITLE
ABS SDMX data - issues with some datasets

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1063]
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-wV7kVRrETtBh7KXMVTySdhque4r

Update 9 Sep 21: 
It didn't work at all 2 hrs ago, but seems to work now?

**Comment by marietruelove** [comment]
https://nationalmap-2021-09-03.nm.terria.io/#share=s-uqQ6lLAutNmwKax88aXkeeT7vJ2
- this dataset gives a 'failed to load error'

https://nationalmap-2021-09-03.nm.terria.io/#share=s-oRb4QtEDDb5M95wTJRkOJcx26rA
- this dataset data doesnt appear on the map?

https://nationalmap-2021-09-03.nm.terria.io/#share=s-rERCvfzWAATcCHQDuYrBIDolfnc
- this data get a chart but no map data? And then a 'failed to load' error when change the categories

Metadata is missing

**Comment by nf-s** [comment]
Testing @marietruelove's links

1. For "Males aged 18 years and over who are current smokers (no.)" there is no data for SA2s - you need to change to SA3s - https://nationalmap-2021-09-03.nm.terria.io/#share=s-1b2jdO7vPQGs0PcXFW3oYJ1J4bY

I will see if I can detect no data for SA2s and automatically swap to SA3s

2. International trade in G and S - only has data for the entire country, not states

I can fix this dataset but disabling region mapping if there is only one region - this will display data as a chart instead.

3. "Producer Price Indexes by Industry"

Not sure what to do about this one, I can add more info to the error messages like "No data for this combination of variables, please select different values" or something?

**Comment by nf-s** [comment]
1. I have changed default "Data Item" to "Estimated resident population"
![image](https://user-images.githubusercontent.com/6187649/132984983-5f3b9306-6b92-4aa3-8b4a-039c5a67e648.png)

2. This is now presented as chart
![image](https://user-images.githubusercontent.com/6187649/132984068-f9b9c034-880b-4d7d-94bb-1cb667417240.png)

3. Re-worded error
![image](https://user-images.githubusercontent.com/6187649/132984043-37595a0d-aac1-42b4-9067-92f1da080ec0.png)

**Comment by nf-s** [comment]
I'm going to close this as datasets mentioned have been fixed (see https://github.com/TerriaJS/natmap-catalog-v8/pull/29) - it has also been superseded by other issues:

- [ ] https://github.com/TerriaJS/nationalmap/issues/1076
- [ ] https://github.com/TerriaJS/nationalmap/issues/1075
- [ ] https://github.com/TerriaJS/nationalmap/issues/1074
- [ ] https://github.com/TerriaJS/nationalmap/issues/1072
- [ ] https://github.com/TerriaJS/nationalmap/issues/1071
- [ ] https://github.com/TerriaJS/nationalmap/issues/1070
