### ISSUE TITLE
Update wording Residential Dwellings data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1065]
Just update on wording:

Example here should read as:

6389 dwellings – 2km Grid

 
![image](https://user-images.githubusercontent.com/18452161/133026666-6999ed1c-ac79-449f-a478-472455fd741f.png)

Change to:
2km Grid:
1km Grid:
500m Grid:
100m Grid:

 
![image](https://user-images.githubusercontent.com/18452161/133026675-2a0520c0-8d29-46e6-bc4f-3c2a3d31571d.png)

**Comment by mwu2018** [comment]
Done.
https://nationalmap-2021-09-03.nm.terria.io/#share=s-67plS4dgmHVqQg69n3Lp2aHYlIf
