### ISSUE TITLE
Remove Indigenous Forest Estate (2018) from catalogue

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1069]
Remove Indigenous Forest Estate 2018 from catalogue https://beta.nationalmap.terria.io/#share=s-hBukUUH1MN2sLsECwejqzoACLqz due to decommissioning by the custodian.

**Comment by mwu2018** [comment]
@AnaBelgun It will be removed from two places
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-5Tnllc4Xvj8yUZ3inwn5tD0N7y5
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-8rPR4cSjtcHBVAo3bTWTUnZQcmm

**Comment by mwu2018** [comment]
Done
See https://nationalmap-2021-09-03.nm.terria.io/
