### ISSUE TITLE
ABS - SDMX Population Projection data inconsistent region mapping

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1071]
<img src="https://user-images.githubusercontent.com/6187649/134806333-ec8017ad-913e-4760-b7a8-6153d7efed9c.png" width="300px"/>

Not sure how to handle region mapping for these datasets, they use the following:
- "CL_ASGS_2011" codelist
- "ABS:CS_GEOGRAPHY(1.0.0).REGION" concept
- "ASGS_2011_STATE_GCCSA_SA4_SA3_SA2" - dimension ID

And they do not have a "region_type" dimension to specify region mapping

This makes it hard to automatically determine that the dataset is actually using  `GCCSA_2011` (greater capital city statistical area)

**Comment by AnaBelgun** [comment]
Shall we go back to ABS and ask to reconsider including a region_type dimension?
