### ISSUE TITLE
ABS - SDMX Petroleum Expansion regions

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1075]
![image](https://user-images.githubusercontent.com/6187649/134849588-4e9b5a2f-615a-42a9-91a4-391498cb3e74.png)

Not sure how to deal with this dataset, the region-mapping is incompatible with STE (state) regions

**Comment by AnaBelgun** [comment]
does it show anything when selecting anything else  other regions from the list?

**Comment by nf-s** [comment]
You get a time series 

![image](https://user-images.githubusercontent.com/6187649/134856616-60874836-7a89-45c4-87dc-fe57bad64858.png)
