### ISSUE TITLE
Add support for the Atlas of Living Australia

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/nationalmap#108]
Atlas of Living Australia (ALA) has what/where/when data for 57m animal/plant sightings.  They have an API - details at http://api.ala.org.au - this includes the use of Apache Solr to generate WMS layers.  In NM, we could allow for users to search for an animal/plant and then show the resulting WMS layer of sightings.  They have been a couple of requests from users wanting to see ALA on NM.

**Comment by florianm** [comment]
The danger of using ALA sightings is that data consumers might not be aware of ALA's policy of dithering coordinates for sensitive locations. Might be worth including a mention into NationalMap's "not for navigation etc" disclaimer that ALA coordinates might be dithered.

The Dept of Parks & Wildlife WA holds threatened and protected plant sightings within WA at http://naturemap.dpaw.wa.gov.au/ and went the other way - to authenticated users with a valid reason to access raw locations, we show accurate locations, else we show no locations at all as not to present incorrect data.

**Comment by stevage** [comment]
Unfortunately their main WMS server is incredibly slow. http://biocache.ala.org.au/ws/ogc/ows has been taking several minutes just to generate the getCapabilities.

**Comment by stevage** [comment]
Hmm, I'm trying to add some layers from the [layers JSON](http://spatial.ala.org.au/ws/layers) but getting errors "400: ALA:bioclim_bio16 is not served by a WMS backend.". eg: http://spatial.ala.org.au/geoserver/gwc/service/wms?service=WMS&version=1.1.1&sld_version=1.1.0&request=DescribeLayer&layers=ALA%3Abioclim_bio16

**Comment by ansell** [comment]
Would updating the version of Geoserver on spatial.ala.org.au help with interoperability? Have been tracking this at the following issue, but didn't have any particular use cases other than a few failures when I was uploading particular layers to it: 

https://github.com/AtlasOfLivingAustralia/spatial-service/issues/9
