### ISSUE TITLE
SDMX - Beta release disclaimer 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1082]
**ABS.Stat Beta** 
Users of NationalMap can access the Beta release of the ABS Data API, which allows to preview the data API before it is released in its final form. It gives the opportunity to provide the ABS with feedback as it works to enhance the service by emailing api.data@abs.gov.au.  

**About the ABS.Stat Beta - from https://stat.data.abs.gov.au/** 
Data in this ABS.Stat beta release may not necessarily be the most up to date. You are advised to check the [ABS website ](https://www.abs.gov.au/)for the latest data.
We recognise that there are still some issues in the beta release. We have compiled a [list of issues ](https://www.abs.gov.au/websitedbs/D3310114.nsf/home/absstat+issues) identified so far and are currently working to rectify these. If further issues are discovered please let us know using api.data@abs.gov.au. The [ABS privacy policy ](https://www.abs.gov.au/about/legislation-and-policy/privacy/privacy-abshow) outlines how the ABS handles any personal information that you provide to us.
For more information on the ABS.Stat Beta release, please refer to https://stat.data.abs.gov.au/.

**Comment by nf-s** [comment]
done!
