### ISSUE TITLE
NationalMap catalogue - improve management

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1083]
Improve management of NatMap catalogue 

- [ ] delete NatMap catalogue repo https://github.com/TerriaJS/NationalMap-Catalog 
- [ ] change configuration management (partly to avoid the confusion of multiple changes by different users, overwriting etc)
- [ ] mind the sharelinks; create share keys for v7-v8 etc

**Comment by nf-s** [comment]
Replaced by https://github.com/terriajs/nationalmap/issues/1122
