### ISSUE TITLE
Most VIC data portal WMS datasets (Either via "Open in NationalMap" button or Built-in national map catalog)

### ISSUE THREAD

**Issue by t83714** [TerriaJS/nationalmap#1090]
### Most VIC data portal WMS datasets (Either via "Open in NationalMap" button or Built-in national map catalog)

E.g. this one: 

https://data.gov.au/dataset/ds-vic-4ce61bcf-f5f2-4f8a-bbe7-4d5a3c07b918

It renders well in Magda map preview but when you open it in nationalMap, it will complaint about:

http status 494 (Request too big)

![image](https://user-images.githubusercontent.com/674387/136504531-610d8bec-6ea9-43ed-b08d-c44282c0af0a.png)

### My theory / Investigation
 
It looks like the original dataset url from vic is like the following (Note it contains the `LAYERS` parameters):

http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&WIDTH=512&HEIGHT=512&LAYERS=ENERGY_ELECTRICITY_DISTRIBUTOR&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A4283&BBOX=141%2C-39%2C150%2C-34

And seems when the url is add to nationalMap (either via open in national map button or manually add in national map), the `layers` parameter is not utilised.

Because of it, the nationalMap will try to fetch all layers --- which lead to the Request too big error.

### Impact

It seems all VIC WMS dataset are structure in that way. So it will impact all vic WMS datasets on data.gov.au.

Furthermore, seems any of VIC nationalMap built-in catalog also not work (for the same error).

![image](https://user-images.githubusercontent.com/674387/136507622-de95589d-d316-4ef4-b831-380912e3b72a.png)

**Comment by wibily** [comment]
requires release in nationalmap
