### ISSUE TITLE
Coastlines story - create share link name similar to DEA

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1093]
DEA Maps coastlines story: https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1

Ticket to create a sharelink similar to the above, by replacing (https://nationalmap.gov.au/#share=s-DEACoastlines&playStory=1)

**Comment by AnaBelgun** [comment]
Updated by Robbi: https://nationalmap.gov.au/#share=s-pdVDHpCbo8CAp7laFIk5q0sNfgU

**Comment by AnaBelgun** [comment]
Next step: 
- create sharelink name

**Comment by steve9164** [comment]
Requires GA to manually upload a json file to their S3 share bucket
