### ISSUE TITLE
NationalMap - Mar / Apr 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1097]
High priority: 
- [x] https://github.com/TerriaJS/neii-viewer/issues/218
- [x] https://github.com/TerriaJS/nationalmap/issues/1120
- [x] https://github.com/TerriaJS/nationalmap/issues/1108
- [x] https://github.com/TerriaJS/nationalmap/issues/1115
- [x] https://github.com/TerriaJS/nationalmap/issues/1118
- [x] https://github.com/TerriaJS/nationalmap/issues/1117
- [x] https://github.com/TerriaJS/nationalmap/issues/1132
- [x] https://github.com/TerriaJS/nationalmap/issues/1131
- [x] https://github.com/TerriaJS/nationalmap/issues/1130
- [x] https://github.com/TerriaJS/nationalmap/issues/1127
- [x] https://github.com/TerriaJS/nationalmap/issues/1129 **To do after release**
- [x] https://github.com/TerriaJS/nationalmap/issues/1128
- [x] https://github.com/TerriaJS/nationalmap/issues/1126
- [x] https://github.com/terriajs/vic-digital-twin/issues/270

Don't forget: 
- [x] https://github.com/TerriaJS/saas-catalogs-public/pull/121
- [x] rerun the search index

_______________________________________________________________________________________________________________________________________

**Comment by meh9** [comment]
Testing:
1. https://github.com/TerriaJS/neii-viewer/issues/218 not fixed - not added to catalogue and when added manually does not display.

**Comment by nf-s** [comment]
- [ ] https://github.com/TerriaJS/terriajs/pull/6240

**Comment by AnaBelgun** [comment]
NationalMap release available in preprod; to be released in prod by GA

**Comment by AnaBelgun** [comment]
Update 19 Apr 2022: 
- GA testing - print preview broken https://github.com/TerriaJS/nationalmap/issues/new

**Comment by mwu2018** [comment]
Updated 26 Apr 2022:
Print preview works now.

**Comment by AnaBelgun** [comment]
Release is now in production
