### ISSUE TITLE
NationalMap - CSV issues investigation 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1100]
To investigate the following CSV issue and re-submit terriajs / csv issue if related to v8 support of CSV:

- [ ] User feedback for [SA1to UCL file ](https://teams.microsoft.com/l/file/91A27E65-5BB4-40A6-B173-C90957C43A9D?tenantId=0fe05593-19ac-4f98-adbf-0375fce7f160&fileType=csv&objectUrl=https%3A%2F%2Fcsiroau.sharepoint.com%2Fsites%2FWebDataPlatformsgroup%2FShared%20Documents%2FGeneral%2FTerria%2FNationalMap%2FData%2FParlMap%2FThis%20does%20not%20work%20SA1%20to%20UCL%202016.csv&baseUrl=https%3A%2F%2Fcsiroau.sharepoint.com%2Fsites%2FWebDataPlatformsgroup&serviceName=teams&threadId=19:bb5b1646ad984aed9d16a0d10dd36ef3@thread.skype&groupId=624ec5d0-4407-4c62-ab3a-74808556dacd)
The one that doesn’t has one more row than the one that doesn’t, which is the row that has one SA1 for ‘Perisher Village’. My original file was ALL SA1s to UCL, but that didn’t work. I whittled it down until I got to the point where the addition of one row makes the file no longer work.

- [ ] Commonwealth Electoral Division - support in v8 for '[com_elb_name_2019' file](https://teams.microsoft.com/l/file/189A6037-FA63-492D-A32C-8DB60BF96EE0?tenantId=0fe05593-19ac-4f98-adbf-0375fce7f160&fileType=csv&objectUrl=https%3A%2F%2Fcsiroau.sharepoint.com%2Fsites%2FWebDataPlatformsgroup%2FShared%20Documents%2FGeneral%2FTerria%2FNationalMap%2FData%2FParlMap%2F2019_CED.csv&baseUrl=https%3A%2F%2Fcsiroau.sharepoint.com%2Fsites%2FWebDataPlatformsgroup&serviceName=teams&threadId=19:bb5b1646ad984aed9d16a0d10dd36ef3@thread.skype&groupId=624ec5d0-4407-4c62-ab3a-74808556dacd) doesn't work anymore in v8; it worked in v7 ParlMap

![image](https://user-images.githubusercontent.com/18452161/138983532-189e3b7f-8723-466b-b87f-60190564bc02.png)

**Comment by nf-s** [comment]
Both are now working in http://ci.terria.io/main/

They will work after next NationalMap release
