### ISSUE TITLE
National Vic State Data folder contains less resources than VIC DT version Vic State Data folder

### ISSUE THREAD

**Issue by t83714** [TerriaJS/nationalmap#1101]
I got an inquiry from Data Vic and they wondering why some of DELWP datasets that added to data VIC are not shown on national map.

Both folders are fetching data from data.vic ckan instance

We can tell national map state data folder only show very little items:
![image](https://user-images.githubusercontent.com/674387/139342301-d8820936-ed46-4f2e-a45f-dbf4491d01bd.png)

And vic DT version has much more:

![image](https://user-images.githubusercontent.com/674387/139342385-51843a84-58cb-4903-8944-6e7362692080.png)

One thing I noticed that national map has a config issue that doesn't fetching GeoJSon correctly.

Here is the query:

https://discover.data.vic.gov.au/api/3/action/package_search?start=0&rows=1000&sort=metadata_created%20asc&fq=%20(res_format%3Akmz%20OR%20res_format%3Ageojson%20OR%20res_format%3Acsv-geo-au%20OR%20res_format%3Aaus-geo-csv)

The query above should also search keyword `GeoJSON` (case sensitive) as VIC DT.

But even count that issue in, we still can't explain why Vic DT has Department of Transport data --- as there are other formats (not only GeoJson) under that folder:

![image](https://user-images.githubusercontent.com/674387/139342735-d34ca518-a1cf-438e-83dd-d9b234f3b7f0.png)

**Comment by nf-s** [comment]
We are now doing this!

https://github.com/TerriaJS/saas-catalogs-public/tree/main/common/aus-gov-open-data

It will be included in the next release
