### ISSUE TITLE
NationalMap - Embedding doesn't appear to work

### ISSUE THREAD

**Issue by marietruelove** [TerriaJS/nationalmap#1103]
Many years ago an integration was done with NationalMaps where we use a jquery post with a payload to present data from Australian Business Register Explorer and the required boundaries.   Unfortunately, this does not appear to be compatible with the recent changes in Terriajs v8 that is now used by NationalMaps.   

We have followed various samples from github  (https://github.com/TerriaJS/nationalmap/wiki/TerriaJS-URL-parameters/79743f08b8cd7378137960354822db9645dc899a) and I think we are using the following property “Start” to pass data.

Similar to the following;  
{
                                                                "initSources": [
                                                                                {
                                                                                                "homeCamera": {
                                                                                                                "north": -55,
                                                                                                                "east": 119,
                                                                                                                "south": -8,
                                                                                                                "west": 151
                                                                                                },
                                                                                                "catalog": [
                                                                                                                {
                                                                                                                                "name": "ABR Explorer",
                                                                                                                                "type": "group",
                                                                                                                                "isOpen": true,
                                                                                                                                "members": [
                                                                                                                                                {
                                                                                                                                                                "name": "ABR Disaster Report" + selectedLgaName,
                                                                                                                                                                "type": "csv",
                                                                                                                                                                "csvString": formattedCsvData,
                                                                                                                                                }
                                                                                                                                ]
                                                                                                                }
                                                                                                ]
                                                                                }
                                                                ]
                                                }
 
But even once we update the json format described in documents it cannot show the data on map properly.
We believe that this maybe a similar issue reported by another user on github (https://github.com/TerriaJS/nationalmap/issues/1099) which suggests a known issue. 

Is there a release date for this fix and do you know when it might become available to NationalMap?

Is there any advice or assistance you can provide to help us overcome this issue?

**Comment by wibily** [comment]
decision to made about whether we support this method of embedding. Also include updating docs with the "blessed" way of embedding

**Comment by AnaBelgun** [comment]
Update 2 Dec 2021: 
We are experiencing ongoing issues with mapping SIP datasets on the NationalMap which is embedded on our SIP map webpage here: https://nationalmap.gov.au/#share=s-iMKtAkE8bAvfnr5wcrkJS42m2Lh. It appears that the embedded NationalMap is having problems downloading and mapping the SIP datasets that are stored in data.gov.au. When you open the SIP Map an error message appears in relation to each SIP dataset that has been added to the SIP map. An example of the error message relating to the Telstra dataset is reproduced below: 

	Error accessing catalogue item
	An error occurred while attempting to download tiles for catalogue item:
	Telstra Corporation Limited - Combined service areas - WMS
	The catalogue item has been hidden from the map. You may re-show it in the Now Viewing panel to try again.
	Tile Error: Got a 200 (OK) response from URL:
	https://data.gov.au/geoserver/statutoryinfrastructureprovidertelstracorporationlimited/wms?transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&crs=EPSG%3A3857&service=WMS&version=1.1.1&request=GetMap&layers=ckan_4e35d278_cc57_4e7a_b84a_94983d4b48cb&bbox=16824707.169906717%2C-4024256.665157959%2C16825318.666132998%2C-4023645.168931678&width=256&height=256&srs=EPSG%3A3857
	but it could not be loaded as an image.

We have tried re-adding the WMS files for each SIP dataset to our SIP map, but the error message still occurs, and the SIP dataset does not map. However, when we add the GeoJSON file for the SIP dataset, the dataset appears to map, and we can view the coloured polygon's by using the 'ideal zoom' button or searching for a specified project/service area address. We've also noted that when adding the GeoJSON files, the unique colour styles allocated to each SIP do not show up in the workbench. Can you advise whether our SIP map can be maintained by removing all the current WMS files and replacing them with the GeoJSON files instead?

**Comment by nf-s** [comment]
For the first issue, the JSON start data requires a `workbench` property, which specifies which items are added to the map when it it loaded.

To use this property, you will need to add an `id` to the item you want to add (in the example below I have added `"id": "some-id"`

For example

```json
{
  "initSources": [
    {
      "homeCamera": {
        "north": -55,
        "east": 119,
        "south": -8,
        "west": 151
      },
      "workbench": [
        "some-id"
      ],
      "catalog": [
        {
          "name": "ABR Explorer",
          "type": "group",
          "isOpen": true,
          "members": [
            {
              "id": "some-id",
              "name": "ABR Disaster Report - some LGA",
              "type": "csv",
              "csvString": "lga_code_2013,value,enum,letter\n54970,10,first value,A\n10300,9,this value,B"
            }
          ]
        }
      ]
    }
  ]
}
```

https://nationalmap.gov.au/#start={%22initSources%22:%20[{%22homeCamera%22:%20{%22north%22:%20-55,%22east%22:%20119,%22south%22:%20-8,%22west%22:%20151},%22workbench%22:%20[%22some-id%22],%20%22catalog%22:%20[{%22name%22:%20%22ABR%20Explorer%22,%22type%22:%20%22group%22,%22isOpen%22:%20true,%22members%22:%20[{%22id%22:%20%22some-id%22,%20%22name%22:%20%22ABR%20Disaster%20Report%20-%20some%20LGA%22%20,%22type%22:%20%22csv%22,%22csvString%22:%20%22lga_code_2013,value,enum,letter\n54970,10,first%20value,A\n10300,9,this%20value,B%22}]}]}]}

**Comment by wibily** [comment]
Ana to communicate back to user

**Comment by AnaBelgun** [comment]
Update 7 Jan 22: 
- to discuss with GA the risk of embedding NatMap with own data
