### ISSUE TITLE
NationalMap - remove WMS layers coming from DTAs GeoServer

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1104]
Under data.gov.au group, to remove temporarily the WMS layers coming from DTA's geoserver (not all WMS layers). 
Leave the working GeoJSON datasets in case they have them as duplicated. resources. 

- [x] Especially check the SIP datasets 

![image](https://user-images.githubusercontent.com/18452161/144364019-f0b7eec8-856a-44a9-acb7-40bae76ab2bd.png)

also includes throwing in the shape files from DTA when WMS layers don't work (request from Mats)

- [x] https://github.com/TerriaJS/nationalmap/issues/1105

**Comment by nf-s** [comment]
Note to self - think about these

- [ ] https://github.com/TerriaJS/terriajs/issues/5533
- [ ] https://github.com/TerriaJS/terriajs/issues/5404

**Comment by nf-s** [comment]
This is done, it will included in the next release
