### ISSUE TITLE
Enable direct loading and conversion of shapefiles from data.gov.au

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#1105]
We should enable direct loading of shapefiles and zipped shapefiles from data.gov.au in order to not be dependent on their GeoServer.

One way to find datasets that have shapefiles just search for WMS layers:

https://data.gov.au/search?format=WMS&q=

Using that method it is then possible to survey what the metadata is for shapefiles - note that we are only interested in the ones where the WMS is hosted on the data.gov.au GeoServer, but I don't have a good way to filter for that using the UI. 

Here are some examples:

https://data.gov.au/data/dataset/erf_project_mapping/resource/ad3bcc6e-9b0f-4c4f-85fd-e0efa8cc4386
https://data.gov.au/data/dataset/manningham-maternal-and-child-health-centres/resource/cca9c24e-0456-4d8d-b1db-92cb04cd1b9a
https://data.gov.au/data/dataset/water-authority-in-horsham_water-mains-gwm-water/resource/a460aee8-3f27-44db-a20b-e4f03fc3a8e5
https://data.gov.au/data/dataset/residential-vacant-land-city-of-greater-geelong/resource/c0ffb734-1618-4077-9513-57ba665f11c3

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6048
This will be enabled next release
