### ISSUE TITLE
Remove Surface Hydrology from Energy - Renewable group

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1108]
Surface hydrology has an old url under Energy - Renewables. 
The correct one is already under Water - Surface.

**Comment by nf-s** [comment]
Fixed in https://github.com/TerriaJS/saas-catalogs-public/commit/daa6fe4b7586fd5d869e72152378a776605eee22

Will be live when https://github.com/TerriaJS/saas-catalogs-public/pull/117 is merged

**Comment by nf-s** [comment]
In prod
