### ISSUE TITLE
NOM - line colour not matching legend

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1112]
User feedback: 
In this section:
Energy \ Electricity Infrastructure \ Network Opportunities \ New Generator Capacity \ Transmission \ Transmission power lines
-> although the legend indicates a colour ramp from red to blue (depending on how much New Generation Connection Capacity is available per transmission line), all the lines on the map appear all grey... No way to tell them apart from one another...

**Comment by nf-s** [comment]
All styling for NOM data is provided by data custodian following GeoJSON simple-style specification.

If you look through the GeoJSON file - https://network-opportunity-maps.s3-ap-southeast-2.amazonaws.com/capacity/test/combined-transmission-powerlines.geojson

You will see that all lines have been set to be gray (or `"stroke":"#808080"`)

![image](https://user-images.githubusercontent.com/6187649/157002104-b6b8c743-6607-48ab-8c6c-3fd9a19a29c0.png)

![image](https://user-images.githubusercontent.com/6187649/157002158-f30124f5-89ab-470f-82bc-f41ba17c1aa3.png)

**Comment by AnaBelgun** [comment]
thanks @nf-s so, the styling changes need to be done by NOM in that GeoJSON file right?

**Comment by jwyndham** [comment]
Hi @nf-s and @AnaBelgun,

The while the line styling is defined in the geojson, the legend is a static image that is hosted in a UTS s3 bucket (if I recall correctly there was some difficulty in the configuring the colours to do exactly what we wanted and so it was set up this way).

I don't really like the way this is set up and would like to investigate alternatives to solve this particular issue, and to make it easier to maintain in future.

Can you show me where to find the initialisation json for this layer so I can understand how everything gets configured and so I can make changes if necessary?

Also, would it be possible for UTS to host the the initialization files for everything in `Energy \ Electricity Infrastructure \ Network Opportunities` ? We presently host them for some of our layers, but not all.

Cheers,
Joe - UTS

**Comment by nf-s** [comment]
Hi @jwyndham 

We now have the ability to dynamically style geoJSON client-side.

For example

http://ci.terria.io/main/#clean&https://gist.githubusercontent.com/nf-s/9a2d49907ac8acd87a3afea4c8e1e5c3/raw/9e465dee2a1a1ca6f25b63ba2e0c54cf119a0798/aremi-dist-lines.json&share=s-wwMBFInmLnz2NOL9EwpHXNp1CPz

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6187649/167757483-9516cec7-e285-454f-ad9d-56ce1e0dbde4.png">

At the moment this only applies to fill/line color, but I am currently working on line width styling.

The initialisation JSON for the entire `Energy` group in NationalMap is here https://terria-catalogs-public.storage.googleapis.com/nationalmap/catalog/energy/prod.json

The init JSON for the example above is here - https://gist.github.com/nf-s/9a2d49907ac8acd87a3afea4c8e1e5c3#file-aremi-dist-lines-json

If you want to host the `Network Opportunities` init JSON, please host this file somewhere

- https://gist.githubusercontent.com/nf-s/74daa39c47606965f597ca21b02a2d92/raw/c253a70a60f975f90ee4f7a8e61c5327657a0686/network-opp.json

and then send me a URL to the file and I can point the NationalMap `Network Opportunities` group at it

Cheers,
Nick
