### ISSUE TITLE
Update Biogas national facilities

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1115]
The new persistent URL is; https://cae-biogas.s3.ap-southeast-2.amazonaws.com/facilities.csv

FYI, the data custodian has our previous name. Could you please change National Centre for Engineering in Agriculture, University of Southern Queensland to Centre for Agricultural Engineering, University of Southern Queensland? 
![image](https://user-images.githubusercontent.com/18452161/152067445-28c50c23-8169-4b6e-ab6e-b92aeeeff5b0.png)

**Comment by mwu2018** [comment]
Close this ticket when the PR https://github.com/TerriaJS/saas-catalogs-public/pull/124 is merged.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/saas-catalogs-public/pull/124
