### ISSUE TITLE
No data for PTV Night Bus Stops - WMS

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/nationalmap#1118]
https://nationalmap.gov.au/#share=s-dXZrvHstngiljKGYKKU21vBXA5k

**Comment by AnaBelgun** [comment]
service provider issue

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/161894899-e3878a4e-8045-4e07-becb-7e64bad8b51a.png)

The layer is not in `GetCapbilities` http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&WIDTH=512&HEIGHT=512&LAYERS=PTV_NIGHT_BUS_STOP&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A4283&BBOX=140.501%2C-39.137%2C150.068%2C-33.0&service=WMS&version=1.1.1&request=GetCapabilities
