### ISSUE TITLE
Correct metadata EV charging stations

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1120]
Currently the EV charging locations shows data for NSW but the metadata states it is an Australia-wide coverage. 

![image](https://user-images.githubusercontent.com/18452161/154397435-67d0b6f0-508e-4a99-8f8b-af58fffb0dea.png)
 Replace "Australia-wide" with "NSW"

**Comment by nf-s** [comment]
Fixed in https://github.com/TerriaJS/saas-catalogs-public/commit/daa6fe4b7586fd5d869e72152378a776605eee22

Will be live when https://github.com/TerriaJS/saas-catalogs-public/pull/117 is merged

**Comment by nf-s** [comment]
In prod
