### ISSUE TITLE
LGA 2019 issue

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1126]
The LGA 2019 statistical boundaries are working inconsistently on NationalMap (when using the same web service): https://geo.abs.gov.au/arcgis/rest/services/ASGS2019/LGA/MapServer

Working: https://nationalmap.gov.au/#share=s-npthh5dH7PVJxljlGeSlz2UQYXY 
![image](https://user-images.githubusercontent.com/18452161/158356363-a65d3c5c-5219-46bd-a6fe-95a4317e7eae.png)

Not working: https://nationalmap.gov.au/#share=s-9wqWaWVArcd1jO2RfAQFwUjldPe

Also, a user reported CSV files based on 2019 LGAs throwing errors, while 2018 based ones, working.

**Comment by AnaBelgun** [comment]
connected to this: https://github.com/TerriaJS/nationalmap/issues/1130

**Comment by steve9164** [comment]
This seems to be working now. Also both items in the catalogue have identical configuration and they have separate ids (so the items won't interfere with each other) so both should work or neither, unless there is a problem on the server.
