### ISSUE TITLE
Update all ABS boundaries with 2021 versions

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1127]
Check and update all ABS ASGS boundaries with new (2021) versions available here: https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/data-services-and-apis

**Comment by mwu2018** [comment]
Nationalmap catalogue will be automatically updated once the PR https://github.com/TerriaJS/saas-catalogs-public/pull/121 is merged.
