### ISSUE TITLE
NationalMap - SIP data - short URL and landing page error issues

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1128]
- [ ] The Share url shortening works inconsistently. To test: 
- use https://nationalmap.gov.au/#share=s-vhmmv24yVT1qPjU0EyLcQXcc6vN
- click on Share to create a share url 
![image](https://user-images.githubusercontent.com/18452161/158366724-e7987905-63f8-4abd-a04d-762fd6411e27.png)

- [ ] Landing page error 
- go to: https://www.acma.gov.au/sip-map
- click on the map
![image](https://user-images.githubusercontent.com/18452161/158915820-84f8263f-14d4-4808-99d2-d0b34f84e936.png)

**Comment by AnaBelgun** [comment]
This is an issue noticed on more stories/share links
If a story / share link has a size limit maybe we should look at a warning prompt
TBC if size is the core issue here

**Comment by AnaBelgun** [comment]
waiting for a release

**Comment by nf-s** [comment]
This is fixed.

To test:

- Go to http://ci.terria.io/ts-story/#configUrl=https://nationalmap.gov.au/config.json&share=s-vhmmv24yVT1qPjU0EyLcQXcc6vN
- Create share link

This will be fixed in NatMap after next release

**Comment by nf-s** [comment]
Landing page error is due to a dataset in the workbench not loading.
The error will disappear if a new share link is created - or the dataset starts to load correctly

**Comment by AnaBelgun** [comment]
create this share link with 21 datasets and it works: (https://staging.nm.terria.io/#share=s-zc0t67NxikHuY7QMF70zw6IGcxK)
