### ISSUE TITLE
WA datasets prompt for sign in

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1132]
Some WA state datasets require sign in
![image](https://user-images.githubusercontent.com/18452161/158927267-ab996735-c567-41ba-83d0-e58d0995f346.png)

**Comment by AnaBelgun** [comment]
proxy auth exists for WA services
to investigate and reach out to WA data.gov

**Comment by AnaBelgun** [comment]
Update 23 March 2022: 
dataWA advised the reason for login prompt is wrong labelling in dataWa platform, 
Some of the datasets sourced via dataWA from Dept of Environment have different levels of restriction (from extent only to complete restriction). The dataWA team troubleshooted and corrected the labelling. 
The users will be advised to source credentials from data custodian directly.

**Comment by nf-s** [comment]
The example dataset no longer exists. The catalog index needs to be updated so it doesn't come up in search results
