### ISSUE TITLE
SDMX - ABS.Stat error

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1134]
In interacting with ABS.Stat, from time to time I get errors like the one depicted in screengrab below. If I change a variable to use for rendering layer  dataset in workbench, it works fine and then selecting again the variable that cause original error, it works fine again. This behaviour suggests there may be a bug with UI, not an issue with the ABS’ API – may or may not be something to look at?

Here is the sharelink:
https://nationalmap.gov.au/#share=s-ibBhigsOdvwY1LoDfNAezmwbRUn
![image](https://user-images.githubusercontent.com/18452161/160724334-a0a44339-73b8-46be-aaac-0658942c848f.png)

**Comment by nf-s** [comment]
I don't believe this is a specific SDMX problem - see https://github.com/TerriaJS/nationalmap/issues/1135
