### ISSUE TITLE
Intermittent 503 reponses through proxy

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1135]
See https://github.com/TerriaJS/nationalmap/issues/1134

Every now and then - calls through proxy return 503 responses - it isn't reproducible and seems totally random

My guess is that it is related to GA's deployment - as we don't see this behavior with our own Terria/SaaS deployments

**Comment by nf-s** [comment]
Just happened when I tried to load the map - this is quite a serious issue

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/6187649/160727638-480b9241-29b9-4d10-87e4-0a5bdf343606.png">

**Comment by AnaBelgun** [comment]
thanks. I'll ask teh GA team if they are aware

**Comment by nf-s** [comment]
Another example - with response headers

![image](https://user-images.githubusercontent.com/6187649/165670603-53cdec7c-4a3c-4f42-9ccf-451e5a074754.png)

**Comment by nf-s** [comment]
Example of failed request compared with successful request
 
![image](https://user-images.githubusercontent.com/6187649/165874911-d7554a02-b512-485e-a278-658ff4a080f3.png)

![image](https://user-images.githubusercontent.com/6187649/165874960-13449984-bffd-43d5-a412-03c13a829cb1.png)
