### ISSUE TITLE
Add NEII catalogue to NationalMap 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1147]
**Update 2022-05-12 by Mike**
Because the current nationalmap uses terriajs version `8.2.2`, many ckan items from `Data.gov.au` (mentioned in the following excel file) are broken, which has been fixed by terriajs version `8.2.3`.

Following NEII's decommissioning, most of the data will remain accessible to users via NationalMap. 
The data list with web services links is [HERE](https://csiroau.sharepoint.com/:x:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/NEII%20Viewer/2022-04-27_NEII%20WMS%20missing%20from%20NationalMap.xlsx?d=w6000e9d770c34f828ef89726d7d3b442&csf=1&web=1&e=3GBEe8)

**Update 2022-05-20 by Mike**
The checked items can be verified in both dev and test envs.
- https://nationalmap.gov.au/#clean&https://terria-catalogs-public.storage.googleapis.com/nationalmap/dev.json
- https://nationalmap.gov.au/#clean&https://terria-catalogs-public.storage.googleapis.com/nationalmap/test.json

**Air - Australian Climate (BoM)**
- [x] Sites and Stations (entire group) 

**Oceans**
- [x] NSW Marine protected areas https://neii-viewer.prod.saas.terria.io/#share=s-lFuyi9K65vRvyWy8YS7GNWgOLw2
- [x]  CAPAD 2020 (Marine) https://neii-viewer.prod.saas.terria.io/#share=s-zvPNL52RDl5p0qOAvwhCSZelTkZ
- [x]  GA - Australian Submarine Canyons https://neii-viewer.prod.saas.terria.io/#share=s-k2PpOFwH1qVEIWXKQdQwPI6Yz1S
- [x]  GA - Geomorphic Features of Australia's Marine Jurisdiction https://neii-viewer.prod.saas.terria.io/#share=s-k2PpOFwH1qVEIWXKQdQwPI6Yz1S

**Water**
- [x] GA - Hydrogeology https://neii-viewer.prod.saas.terria.io/#share=s-6mPMdnvyZbGWoMOSWvDc07BbAVy
- [x] Bureau of Meteorology – Water Regulations Data (Entire group)

**Land**
- [x] CAPAD 2020 Terrestrial - https://neii-viewer.prod.saas.terria.io/#share=s-simbh4WzgXP1jMNYx6uM3E5AwIt NationalMap is providing the data for 2016, not 2020
- [x] GA - Australian Coastal Geomorphology Landform Type (entire group)
- [x] GA - Australian Coastal Geomorphology Landform Subtype (entire group)
- [x] GA - Australian Coastal Geomorphology scale guide (web Mercator) (entire group)
- [x] GA - Australian Coastal Geomorphology Smartline (entire group)
- [x] GA - Australian Geological Provinces layers (entire group)
- [x] GA - Australian Geophysical Data Collection - Australian Fundamental Gravity Network Stations https://neii-viewer.prod.saas.terria.io/#share=s-koAcvvGKn0tMr6A5Qg2B5gEJdhG
- [x] GA - Dynamic National Map Reserves - Forestry Reserves https://neii-viewer.prod.saas.terria.io/#share=s-6Io40puMc1aLVk5GfH0SiUJ2pfh
- [x] GA - Dynamic National Map Reserves - Forestry Reserves Labels https://neii-viewer.prod.saas.terria.io/#share=s-mnIKSu1F6IV0U0kfqsXAvuDGm5M
- [x] GA - Dynamic National Map Reserves - Nature Conservation Reserves Land Labels https://neii-viewer.prod.saas.terria.io/#share=s-yQ5slhP0n31qTirOldYyMoWCLRo
- [x] GA - Dynamic National Map Reserves - Nature Conservation Reserves Marine Labels https://neii-viewer.prod.saas.terria.io/#share=s-ns7XUovtS5TZbPMe7tqkkfNCv94
- [x] Queensland Geology Detailed Web Map Service (Department of Natural Resources, Mines and Energy, Queensland Government) (entire group)

**Processes**
- [x] GA - Natural Hazards - Tropical Cyclone Hazard Assessment 2018 (entire group)
- [x] GA - 2018 National Seismic Hazard Assessment https://neii-viewer.prod.saas.terria.io/#share=s-giNHUwGSITPhgZhe5U1hcC7AaTT

**and some suggestions to the display:**
- [x] Air - Australian Climate (BoM) --> Grids --> Solar, can the list be displayed in the correct monthly order?

**Comment by martin-bom** [comment]
Hi @AnaBelgun , FYI the Solar Climatology web data services [http://neii.bom.gov.au/services/solarclim/wms/data] will be decommissioned together with NEII. Please remove the entire group from the NationalMap after 15 June as well. Thank you.

**Comment by mwu2018** [comment]
A preliminary result can be checked at https://nationalmap.gov.au/#clean&https://terria-catalogs-public.storage.googleapis.com/nationalmap/dev.json.

**Comment by mwu2018** [comment]
Going through newly added datasets, some of them might give network error messages. Open the nationalmap in a new window/tab then click on the same dataset, there is no error message. This can also be confirmed by entering URL directly in a browser's address bar. First request might fail but the second attempt might succeed. @peterhassall thinks that the configuration of load balancer for http://neii.bom.gov.au/ might be incorrect. Need to inform the service provider.

**Comment by AnaBelgun** [comment]
@martin-bom hi would you please have a look or connect us with the IT team working on the neii.bom.gov.au to check the load balancer issue? thank you

**Comment by AnaBelgun** [comment]
@mwu2018 the group called "air" should be renamed "climate"

**Comment by martin-bom** [comment]
@mwu2018 Hi can you give me an example to replicate the error? which dataset are you accessing? Thank you.

**Comment by mwu2018** [comment]
@martin-bom The errors occurred to some random items in `Air` -> `Australian Gridded Solar Climatology (BoM)` but there are no more errors when I checked them just now.

**Comment by martin-bom** [comment]
@mwu2018 Feel free to contact me if the error comes up again, I will forward the error message to our network team to investigate. thank you

**Comment by martin-bom** [comment]
@AnaBelgun @mwu2018 FYI Air -> Australian Gridded Solar Climatology (BoM) will be decommissioned together with NEII. Please remove it from the NationalMap catalog after 15 June 2022. Thank you.

**Comment by AnaBelgun** [comment]
thanks @martin-bom but we can leave the rest of the group? 
![image](https://user-images.githubusercontent.com/18452161/168756229-3952a9c9-0981-4f11-ad96-51e0606c9a22.png)

**Comment by martin-bom** [comment]
@AnaBelgun Hi, the "Australian Climate" dataset will still be available after 15 June, only the group "Australian Gridded Solar Climatology" will be decommissioned. Thank you.

**Comment by mwu2018** [comment]
Should the changes be promoted to production now?

**Comment by AnaBelgun** [comment]
Can't find: 

- [ ] NSW Bionet Flora survey data collection; to be placed under under NSW Government - State - Flora
![image](https://user-images.githubusercontent.com/18452161/169485000-ddf5ff99-4823-44c9-b203-201cdc4b1bda.png)

**Comment by AnaBelgun** [comment]
@mwu2018 please don't merge the new catalogue groups/datasets until we investigate the issue with the feature info

**Comment by mwu2018** [comment]
@AnaBelgun  It seems all items are working now. Please let me know if it is ok to add them to prod.

**Comment by AnaBelgun** [comment]
@mwu2018 yes, please. thank you.
