### ISSUE TITLE
NationalMap - May 2022 Staging release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1149]
- [x] https://github.com/TerriaJS/terriajs/issues/6278
- [x] https://github.com/terriajs/nationalmap/issues/1145

Must upgrade terriajs to version `8.2.3` or above. See https://github.com/TerriaJS/nationalmap/issues/1147.

**Comment by nf-s** [comment]
Check with stakeholder to see if Ukraine flag can be kept in Leaflet attribution

![image](https://user-images.githubusercontent.com/6187649/168757243-92cbdff9-ed48-4cdb-ad45-3f61dc6d4aee.png)

To remove the flag, set the following in `map-config`:

```json
"leafletAttributionPrefix": "<a href=\"https://leafletjs.com\" title=\"A JavaScript library for interactive maps\">Leaflet</a>"
```

**Comment by mwu2018** [comment]
See https://staging.nm.terria.io/
