### ISSUE TITLE
Connect to ACMA RRL API 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1151]
Data API available hee: https://www.acma.gov.au/radiocomms-licence-data

**Comment by steve9164** [comment]
Replace a URL.

**Comment by nf-s** [comment]
Is it to replace `http://web.acma.gov.au/pls/radcom/` with `https://web.acma.gov.au/rrl/` ?

**Comment by nf-s** [comment]
If so - here is a test link

https://nationalmap.gov.au/#clean&https://terria-catalogs-public.storage.googleapis.com/nationalmap/catalog/communications/dev.json&share=s-o0aDQJeYws3BIMUFibbxq59pHAG

**Comment by nf-s** [comment]
Can't use API as it has a limit of 2000 items per request.

The "sites" dataset (which contains lat/lon info) contains 114837 rows.

It is only 12MB CSV - so we can load it into Terria.

Only issue is that ACMA publish the CSV in a ZIP file - https://web.acma.gov.au/rrl-updates/spectra_rrl.zip - which is 60MB

So our options are:
- Download entire zip file and load sites.csv into terria
- Ask ACMA if they host "sites.csv" somewhere not in a zip file
- We host "sites.csv" ourselves - and update it every now and then

**Comment by nf-s** [comment]
Will investigate vector tiles with clustering

**Comment by AnaBelgun** [comment]
not required
