### ISSUE TITLE
Northern Australia Infrastructure Facility - blurry 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1154]
The Northern Australia Infrastructure Facility dataset (yellow contour) appears blurry at all zoom levels. 
https://nationalmap.gov.au/#share=s-luxHTbF5K7DOMImNsfx9f8ptJIm

![image](https://user-images.githubusercontent.com/18452161/171983106-130865cf-8918-422e-bf7b-99b7078cb3d4.png)

**Comment by AnaBelgun** [comment]
Ana to email GA

**Comment by AnaBelgun** [comment]
Emailed on 21 June 2022

**Comment by AnaBelgun** [comment]
Update 22 June 22: 
- when adding the web service https://services.ga.gov.au/gis/rest/services/NAIF_Act_2016_Northern_Australia_Definition/MapServer via Upload Data, it is displayed correctly: https://nationalmap.gov.au/#share=s-6fYluOMZpEeXgFqhm0YQkjQkJmN

![image](https://user-images.githubusercontent.com/18452161/174914564-9a9b5ced-8dea-49d4-ae49-6a81deb04f14.png)

- the About data section in current NatMap catalogue, doesn't capture the full service description

GA's suggestion is to check the caching

**Comment by staffordsmith83** [comment]
Working in Dev: https://nationalmap.gov.au/#clean&https://terria-catalogs-public.storage.googleapis.com/nationalmap/dev.json

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/7980991/176612858-095d6ff1-d990-48aa-b81d-8b7e492b9838.png">

**Comment by staffordsmith83** [comment]
@AnaBelgun  working in Test for review https://nationalmap.gov.au/#share=s-1w8WEmQl4p7PiqalYsK1vh07a0I#clean&https://terria-catalogs-public.storage.googleapis.com/nationalmap/test.json

**Comment by AnaBelgun** [comment]
works well, thank you @staffordsmith83

**Comment by staffordsmith83** [comment]
Great, please let me know if I should make the changes in prod @AnaBelgun

**Comment by AnaBelgun** [comment]
This is good to go @staffordsmith83
