### ISSUE TITLE
Investigate (some) empty polygons 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1159]
To check empty polygons in some datasets: 
https://nationalmap.gov.au/#share=s-xrUAMNuePHlPaxS0kj1J3dByHK1

Comment from custodian:
- the ABS DBR product has data for Black Mountain (SA2 801051123 – no data ERP) and Arboretum (SA2 801101134 – 8 persons ERP) in Canberra.
- Uncertain about how the ABS data services are presenting these data

![image](https://user-images.githubusercontent.com/18452161/175455241-ced8c8ed-7727-4067-9f86-1c348cc3871b.png)

**Comment by nf-s** [comment]
Black Mountain `801051123` has no data in SDMX output

Molonglo `801101137` has no data in SDMX output

Arboretum `801101134` has the following values:

Date | Estimated resident population (no.)
-- | --
2015 | 7
2016 | 8
2017 | 8
2018 | 8
2019 | 8
2020 | 8

This data is coming from:
https://nationalmap.gov.au/proxy/_1d/https://api.data.abs.gov.au/data/ABS_REGIONAL_ASGS2016/ERP_P_20.SA2..A

It is accurately portrayed in NationalMap

**Comment by nf-s** [comment]
This is inline with official data published by ABS 

https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/3235.02016?OpenDocument

<img width="632" alt="image" src="https://user-images.githubusercontent.com/6187649/175465235-551622fa-a3d2-44c1-96da-940e0cc49da2.png">

**Comment by nf-s** [comment]
Arboretum is showing correct value and region

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/6187649/175467411-e4bd5e90-24d1-4b0c-a203-19ffc67a5948.png">

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/6187649/175467506-f718d792-11d8-41ba-b4ec-19aad710a69b.png">

**Comment by AnaBelgun** [comment]
The polygons indicated by the user are showing correspondent data correctly. Advice to user at meeting on 6 July.
