### ISSUE TITLE
ABS Census 2021 - LGA Community profiles - showing no data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1160]
The newest release of Census 2021 is now available in NationalMap.
The Communities Profiles group is showing data for the ABS statistical areas but not for the LGAs (2021). 
https://nationalmap.gov.au/#share=s-bkHn7QqlTfACCKBUBBtXmlt3OrR

To investigate.

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/6357

Will be fixed by next release
