### ISSUE TITLE
BoM water online - Hawkesbury River watercourse stations

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1162]
Investigate why some stations data are missed in the service harvested in NationalMap. 

Steps: 
BoM
- check BoM Water Online http://www.bom.gov.au/waterdata/
- zoom into Hawkesbury River area
![image](https://user-images.githubusercontent.com/18452161/177886790-1c0aefda-a5ff-44b6-9e20-0a59e2b161c0.png)
- hoover over the stations - they seem to be owned by NSW DPIE
- to check also BoM https://portal.wsapi.cloud.bom.gov.au/arcgis/apps/sites/#/australian-water-data-service 

NationalMap
- check water stations data on NationalMap by adding Watercourse discharge: https://nationalmap.gov.au/#share=s-oXIEfV1t7MQCgLJRcs1Ez4Dc22s
- there are no stations appearing from the BoM service
https://nationalmap.gov.au/#share=s-oXIEfV1t7MQCgLJRcs1Ez4Dc22s

![image](https://user-images.githubusercontent.com/18452161/177887022-4f9719bb-85ef-4ba2-a54a-1fd475aba7f4.png)

- to investigate if the stations data on NatMap and BOM's online app come from different services

**Comment by nf-s** [comment]
@AnaBelgun How would you like me to proceed?

**Comment by AnaBelgun** [comment]
Update 23 Nov 2022: 
- delete the "All hydrologic stations" and keep the "Stations" layer which doesn't have a filter enabled.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/saas-catalogs-public/commit/90e9e0517e770092cac4ee863422971093388c80
