### ISSUE TITLE
NationalMap - August / Sep 2022 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1164]
Changes to catalogue configuration post NationalMap release using TerriaJS 8.2.16 
- [ ] https://github.com/terriajs/nationalmap/issues/1153
- [x] https://github.com/terriajs/saas-catalogs-public/issues/167
- [ ] https://github.com/terriajs/saas-catalogs-public/issues/183
- [ ] https://github.com/terriajs/nationalmap/issues/1156
- [x] https://github.com/TerriaJS/nationalmap/issues/1165
--------------------------------------------------------------------------------------------------------------
- [x] https://github.com/TerriaJS/terriajs/issues/6228
- [x] https://github.com/terriajs/terriajs/issues/6441
### Moved to Dec 2022 Release
- [ ] https://github.com/terriajs/saas-catalogs-public/issues/168
- [ ] https://github.com/terriajs/nationalmap/issues/1162
- [ ] https://github.com/terriajs/nationalmap/issues/1157
- [ ] https://github.com/TerriaJS/nationalmap/issues/1158
- [ ] https://github.com/TerriaJS/nationalmap/issues/1172

**Comment by AnaBelgun** [comment]
Release for updating the NOM data only.

**Comment by AnaBelgun** [comment]
- release to GA only for NOM data 
- rest of tickets to be done when migration is completed
- ana to move the tickets into Nov / Dec release (post migration)

**Comment by nf-s** [comment]
In production!
