### ISSUE TITLE
Great Barrier Reef catchment boundaries data - update

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1165]
Update Great Barrier Reef web service link: https://spatial-gis.information.qld.gov.au/arcgis/rest/services/InlandWaters/DrainageBasins/MapServer/3

![image](https://user-images.githubusercontent.com/18452161/179867332-25b3b5e0-f7ab-4c08-83a4-64de5b922c0c.png)

**Comment by mwu2018** [comment]
It appears that https://gisservices.information.qld.gov.au/arcgis/rest/services is replaced with https://spatial-gis.information.qld.gov.au/arcgis/rest/services/

**Comment by mwu2018** [comment]
After fixes:
https://ci.terria.io/main/#configUrl=https%3A%2F%2Fterria-catalogs-public.storage.googleapis.com%2Fnationalmap%2Fconfig%2Fdev.json&share=s-ccBJrXVR9YJvGwa9lVjXgrSRe5I

Many other broken catalog items under https://ci.terria.io/main/#configUrl=https%3A%2F%2Fterria-catalogs-public.storage.googleapis.com%2Fnationalmap%2Fconfig%2Fdev.json&share=s-KupzPUzota95KwAoJ8Q7knJYvz are also fixed.

**Comment by AnaBelgun** [comment]
hi @mwu2018 it looks like the one you suggest looks like this on NationalMap: https://nationalmap.gov.au/#share=s-xk4kHYJHT1vsdOWs8sP0IIKJKOr

The question is are you willing to place those layers under QLD State data and duplicate the Great Barrier Reef single layer to fix the current one? I think that might be one way to go.

**Comment by AnaBelgun** [comment]
Update 14 Sep 22: 
- to replace the current QLD State data (whole) group

**Comment by mwu2018** [comment]
https://nationalmap.gov.au/#share=s-fGz4vUA74zaYDB1KGTCm23fhxY6

**Comment by AnaBelgun** [comment]
looks good @mwu2018
