### ISSUE TITLE
WA DBCA Wetlands data services not working - to check after PR merged 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1168]
prompted by this user feedback: 
_DBCA Geomorphic Wetlands of Swan Coastal Plain Map is not working fo rthe public to view. Urgently required!!_

https://nationalmap.gov.au/#hideExplorerPanel=1&share=s-aAX0EIOrV6rKVAd1REKTs7VWEu

Datasets not throwing an error when added, but no data visualised on the map at various zoom levels. 

Dev tools view

![image](https://user-images.githubusercontent.com/18452161/184558235-be1412d9-4670-4915-b8c1-7e304f6ba6d1.png)

**Comment by AnaBelgun** [comment]
To investigate and report back to [BusinessSolutions@landgate.wa.gov.au](mailto:BusinessSolutions@landgate.wa.gov.au)

**Comment by AnaBelgun** [comment]
Connected to this https://github.com/terriajs/terriajs/issues/6510

**Comment by mwu2018** [comment]
I am unable to reproduce the error with this shared link provided by the feedback: https://nationalmap.gov.au/#hideExplorerPanel=1&share=s-aAX0EIOrV6rKVAd1REKTs7VWEu

It works.
