### ISSUE TITLE
Radiometrics datasets broken

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1175]
To test: 
- upload this service: http://services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer
- test this sharelink: https://nationalmap.gov.au/#share=s-27Uk0EF40WqKihyCWUoTVhpgHBg

Update from custodian 5 Sep 2022: 
It appears that the NationalMap application is requesting the style to be the layer name, which is not a valid request on this service. We can see the NationalMap application makes the following example request:

[https://nationalmap.gov.au/proxy/_0d/http://services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=Radiometrics_U2Th_ratio_filtered_2015&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics_U2Th_ratio_filtered_2015&bbox=10018754.17139462%2C-10018754.17139462%2C20037508.342789244%2C0&width=256&height=256](https://nationalmap.gov.au/proxy/_0d/http:/services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=Radiometrics_U2Th_ratio_filtered_2015&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics_U2Th_ratio_filtered_2015&bbox=10018754.17139462%2C-10018754.17139462%2C20037508.342789244%2C0&width=256&height=256)

When isolating the GA service component of the request, the GA service is responding that the request isn’t valid:

http://services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=Radiometrics_U2Th_ratio_filtered_2015&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics_U2Th_ratio_filtered_2015&bbox=10018754.17139462%2C-10018754.17139462%2C20037508.342789244%2C0&width=256&height=256

If the style is set to ‘default’ the requests will become valid:

•	National Map request: [https://nationalmap.gov.au/proxy/_0d/http://services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=default&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics2015_filtered_ppmTh&bbox=16906647.66422843%2C-4070118.8821290657%2C17219733.73208451%2C-3757032.814272985&width=256&height=256](https://nationalmap.gov.au/proxy/_0d/http:/services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=default&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics2015_filtered_ppmTh&bbox=16906647.66422843%2C-4070118.8821290657%2C17219733.73208451%2C-3757032.814272985&width=256&height=256)
•	Isolated GA request: [http://services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=default&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics2015_filtered_ppmTh&bbox=16906647.66422843%2C-4070118.8821290657%2C17219733.73208451%2C-3757032.814272985&width=256&height=256](https://nationalmap.gov.au/proxy/_0d/http:/services.ga.gov.au/gis/services/Geophysical_Grids/MapServer/WMSServer?transparent=true&format=image%2Fpng&exceptions=XML&styles=default&version=1.3.0&crs=EPSG%3A3857&service=WMS&request=GetMap&layers=Radiometrics2015_filtered_ppmTh&bbox=16906647.66422843%2C-4070118.8821290657%2C17219733.73208451%2C-3757032.814272985&width=256&height=256)

**Comment by meh9** [comment]
This service is now working.
