### ISSUE TITLE
Northern Territory data groups are empty

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1178]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/6187649/190408081-50299b84-aeae-4cbf-821d-ccdc1d422af8.png">

**Comment by nf-s** [comment]
I have added data.nt.gov.au to test

https://nationalmap.test.saas.terria.io/#share=s-ozwupoqAgvv0kEcrlUOAAihZ44F

**Comment by AnaBelgun** [comment]
to be fixed for all LGAs
