### ISSUE TITLE
ABS changes to Census API 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1181]
To discuss changes implemented by ABS for the next release of Census 2021 (Nov-Dev 2022). 
A.	Changes to Census category schemes impacted by 30s time out 
B.	Addition of geospatial information in ABS Data API codelists

**Comment by nf-s** [comment]
Email received on 21st Sept

> The category scheme changes - required to add second release Census 2021 datasets without causing time outs - have now been implemented.
> Unfortunately it has impacted the National Map data catalogue:
>
> ![image](https://user-images.githubusercontent.com/6187649/191412779-8314503a-d9b6-473f-a0d1-20fa5bd4bcd5.png)

I think we will have to implement merging by catalog group name
