### ISSUE TITLE
NSW Local government open data - to investigate and update

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1185]
Ticket to investigate NSW local councils open data missing from NationalMap. 

- [ ] list all councils in this ticket
- [ ] check data.gov.au 
- [ ] check data.nsw
- [ ] check remaining councils websites for open data servers 
- [ ] update the listing in NatMap

**Comment by mwu2018** [comment]
There are [128 councils](https://www.olg.nsw.gov.au/public/local-government-directory/) in NSW. The following table lists councils that have been investigated. If a council potentially has a spatial portal, the link is provided.
| Council Name | Link | Account required |
|---|---|---|
| Albury | https://www.alburycity.nsw.gov.au/forms/map-login-request | Yes |
| Armidale| unknown |  |

**Comment by AnaBelgun** [comment]
closing this ticket, as it is worked on here https://github.com/TerriaJS/product/issues/175
