### ISSUE TITLE
ASRIS Soil data - Organic carbon service update

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1186]
The Organic Carbon services are down atm
(https://nationalmap.gov.au/#share=s-4eNtk7dbsF95HmgpVqnKKIk47By)

https://www.asris.csiro.au/arcgis/rest/services/TERN/SND_ACLEP_AU_NAT_C/MapServer

**Comment by AnaBelgun** [comment]
Update 28 Sep 22: 
The TERN soil landscapes project has created version 2 for several of the SLGA datasets. Versioning is a new challenge for us, and while the approach chosen was seamless for many of the layers, the SOC layer had no direct replacement. It is still available as https://www.asris.csiro.au/arcgis/rest/services/TERN/SOC_ACLEP_AU_NAT_C_V1/MapServer but users should refer to the new recommended layer here: https://www.asris.csiro.au/arcgis/rest/services/TERN/SOC_ACLEP_AU_TRN_N/MapServer for the updated data. You can see where other layers have been updated in the rest catalogue, with version 1 still available as “ *._1”. Please refer to the arcgis rest catalog here: https://www.asris.csiro.au/arcgis/rest/services/TERN.

**Comment by nf-s** [comment]
Fixed in dev and test

- https://nationalmap.test.saas.terria.io/#share=s-uAy6e1m9xDgDEjuahgpJc566COo
