### ISSUE TITLE
NationalMap favicon to change 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1196]
Change NationalMap favicon from Terria logo to Commonwealth Coat of Arms. 
TODO: submit a TerriaJS issue to support change to favicons for all Terria maps.

**Comment by nf-s** [comment]
NationalMap didn't have coat of arms - it had the Australia polygon logo

![image](https://user-images.githubusercontent.com/6187649/198921429-6d07eac4-1dbf-4549-9363-72bc03e64a5f.png)

**Comment by AnaBelgun** [comment]
Thanks Nick,

**Comment by staffordsmith83** [comment]
Something like this, or do we want the Australia polygon logo? ![image.png](https://images.zenhubusercontent.com/62673fa28d46e59cec18c8f1/44af2e02-5674-45d7-8e2e-a0565711a510)

**Comment by AnaBelgun** [comment]
Update 11 Nov:
- depending on the plugin import into NationalMap

**Comment by AnaBelgun** [comment]
Update 23 Nov 22: 
- waiting for config to enable plug ins for SaaS maps 
- push favicon to all SaaS maps
- publish as a package

**Comment by AnaBelgun** [comment]
Connected with https://github.com/TerriaJS/simple-saas-terria-map/issues/2
