### ISSUE TITLE
NationalMap - release version number 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1197]
Check the version number appearing when users hoover over the NationalMap logo. 
- What is it connected to? 
- connect to latest NatMap release version 
- show date together with/in the version number

**Comment by nf-s** [comment]
Version number maps to https://github.com/TerriaJS/simple-saas-terria-map/ version

**Comment by nf-s** [comment]
You can see changes here https://github.com/TerriaJS/simple-saas-terria-map/blob/main/CHANGES.md

**Comment by AnaBelgun** [comment]
Is it possible to have the data incorporated in the version number? at least it gives an indication to users when was last updated. Otherwise the number doesn't mean much to them.

**Comment by nf-s** [comment]
Yes we can change the version to say anything - for example

- 0.0.16 (2022-10-31) TerriaJS 8.2.20

**Comment by AnaBelgun** [comment]
That would be great,

**Comment by nf-s** [comment]
I have changed version format to match new vic-dt format

https://github.com/TerriaJS/simple-saas-terria-map/commit/79ac932232bb92e8416796c7c9044e4114d45209

<img width="373" alt="image" src="https://user-images.githubusercontent.com/6187649/199155893-0288d64f-2c35-4261-b073-5f64cb9098ad.png">

- Date
- Version of TerriaMap
- Version of terriajs
- commit hash of TerriaMap
