### ISSUE TITLE
Sunshine Coast data portal - update 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1198]
The Sunshine Coast data services have been moved from https://gisservices.scc.qld.gov.au/arcgis/rest/services to 
https://data.sunshinecoast.qld.gov.au/.

**Comment by nf-s** [comment]
We can't use this. It uses the ArcGis Hub API - which we don't support

https://www.esri.com/en-us/arcgis/products/arcgis-hub/overview

**Comment by nf-s** [comment]
But, we can change to use https://gislegacy.scc.qld.gov.au/arcgis/rest/services - which seems to still have all the layers active
