### ISSUE TITLE
Error message templating issue

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#1199]
When we get an error message (in this case because the layer `fcp_seasonal_rgb` no longer exists on this WMS server) the error message shows some uninterpolated templating strings:

<img width="513" alt="Screen Shot 2022-11-07 at 14 33 39" src="https://user-images.githubusercontent.com/5283003/200221016-f3300577-e3e9-4c91-8e4d-c365e3040272.png">

Test it using this layer: https://nationalmap.gov.au/#share=s-qMsFwR9q6F2PJB3IycvgMdKcQEi
As we are going to fix that layer you may have to create your own test case - just change the specified WMS layer name in the config to something that doesn't exist.

**Comment by steve9164** [comment]
Probably mismatched parameters between the error message in the translation strings file (en/translation.json) and the parameters passed to `t` function (wherever that translation string is being used). Maybe terriajs 7 used to pass these and the parameters no longer exist since version 8?

**Comment by mwu2018** [comment]
@meh9 A request to the URL you provided will get different error message than yours. I am unable to identify which catalog item caused the error with that shared URL alone. Could you please help?

![image](https://user-images.githubusercontent.com/41275384/235391422-30c40b75-f31a-4c08-a396-05fb48967603.png)

**Comment by AnaBelgun** [comment]
not a problem anymore; will reopen if error is reproduced again

**Comment by steve9164** [comment]
Can be reproduced with this catalogue: http://ci.terria.io/main/#clean&https://gist.githubusercontent.com/steve9164/9b5b6d5c4f763cd6f320b1cd98520b8e/raw/2501e68d4357f2be36e2d77f2c5e314a8b0a7f57/no-layer.json
