### ISSUE TITLE
Add documentation on constructing NM URL with specific dataset loaded

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/nationalmap#120]
It would be good if the docs at https://github.com/NICTA/nationalmap/wiki described the syntax for a URL which loads NM with a specific dataset at another URL loaded (I realise that you can "Add Data" then "share" to get a URL but given that we support the full URL syntax, it would be good if it was documented (eg if someone was automating this rather than doing it through the UI).

**Comment by stevage** [comment]
In general, we should document the URL syntax. There's quite a lot going on there:

- #initfilename
- #local/file.csv
- #http://example.com/remote-file.csv
- #clean 
- #preview
- #map=...
- #share=...
- #start=%7Burlencoded JSON...

**Comment by florianm** [comment]
@bsimyo @stevage This would be a great resource and open up a lot of neat hacks! I'm trying to create NationalMap views on the fly through URL configs only, see https://github.com/datagovau/ckanext-cesiumpreview/issues/3

There I'm trying to show the result of a CKAN search with parameters (e.g. all datasets of a certain CKAN group) on NM.
Currently I'm stuck with one breaking slash before '//api/3/action' in the request TerriaJS builds from the URL, see https://github.com/datagovau/ckanext-cesiumpreview/issues/3#issuecomment-148624228
Is there any way of avoiding the extra slash?

**Comment by stevage** [comment]
Totally agree re: neat hacks: http://stevebennett.me/2015/07/02/your-own-personal-national-map-with-terriajs-no-coding-and-nothing-to-deploy/

The extra slash is definitely a bug to be fixed.

**Comment by stevage** [comment]
Ok, working on this here: https://github.com/NICTA/nationalmap/wiki/TerriaJS-URL-parameters

**Comment by florianm** [comment]
@stevage awesome, thanks for the docs! 
Re your blog post, that work flow is directly what I'd like to see in CKAN's package search page - filter available packages however you like into a list of relevant datasets, then build a terriajs config (in a CKAN extension's controller) and init NM with that config. Having http://terria.io/DataSourceEditor/ and your docs is a great resource!

**Comment by stevage** [comment]
Great. Let me know if you need more.

**Comment by florianm** [comment]
I'm kinda stuck with loading a CKAN catalogue e.g. https://gist.github.com/florianm/bcacc427d44761f245a2
getting a CORS 404.

Same happens with data.gov.au, e.g. 
http://nationalmap.research.nicta.com/#clean&https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fa880f1f3cea2ae712b27%2Fraw%2Fe1eff8eb64672d3eed8aec1850d3257dae7ea9e2%2Fdatasource.json

Also getting a CORS using `https://nationalmap.gov.au/proxy/_1d/http://data.gov.au/` as CKAN URL
https://gist.github.com/anonymous/7a2316f39abe87ea8b46
http://nationalmap.research.nicta.com/#clean&https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F7a2316f39abe87ea8b46%2Fraw%2F37dce928199b1ce35b6dfc2c9e0b91e11059f678%2Fdatasource.json

Testing CORS on [client.cors-api.appspot.com for catalogue.beta](http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fcatalogue.beta.data.wa.gov.au%2F&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote).
and [data.gov.au](http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fdata.gov.au%2F&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

Are both servers not supporting CORS or did I configure NM incorrectly?

**Comment by stevage** [comment]
I might be misunderstanding, but it looks like you're just creating a single `config.json`? Normally, the `config.json` contains general properties, and the names of init files to load ("initializationUrls"), plus domains for which proxying is allowed ("proxyDomains"). If you don't have that latter thing, then it won't proxy for you.

**Comment by florianm** [comment]
I did use http://terria.io/DataSourceEditor/ to configure a CKAN data source with my filter query as additional filter parameter, resulting in one config.json. Not sure whether that was the intended way!
Do I need to add the "proxyDomains" next to the `catalog` entry? I'll try that next.

Just to confirm, is terriajs able to display a CKAN search result like http://catalogue.beta.data.wa.gov.au/dataset?groups=habitat-sampling-initiative as a single, expandable entry in the catalog tab? Or should I build the config for all individual layers of my search result as user added layers on my end?

**Comment by stevage** [comment]
>I did use http://terria.io/DataSourceEditor/ to configure a CKAN data source with my filter query as additional filter parameter, resulting in one config.json. 

Normally you'd create a file "florian.json", then add "florian" to your existing config.json.

>Do I need to add the "proxyDomains" next to the catalog entry? I'll try that next.

Probably - look at other deployments (AREMI, NationalMap etc)

>Just to confirm, is terriajs able to display a CKAN search result like http://catalogue.beta.data.wa.gov.au/dataset?groups=habitat-sampling-initiative as a single, expandable entry in the catalog tab?

Not quite sure what you're asking - you linked to a group which contains one item. A CKAN catalog group can:
- contain a filter, such as only certain resource formats (or a group name or whatever)
- group by CKAN groups

What you're probably missing is a `includeGeoJson: true` field. (It's missing from the data source editor, oops...)

Demo [here](http://nationalmap.research.nicta.com/#clean&https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F9201e4dcf8360dfb0c64%2Fraw%2F230a73246ffe78b2e5707987a7d7cb9ce5e2c66d%2Fdatasource.json). Gist [here](https://gist.github.com/anonymous/9201e4dcf8360dfb0c64).

**Comment by florianm** [comment]
@stevage thanks heaps for the working demo! Indeed the group for now only contains one item, soon more.
My idea was to let users add datasets to an agreed CKAN group, and have one static NM config that shows all datasets of that group. This would be useful for a whole range of use cases around visualising several thematically related datasets from different data custodians.

**Comment by stevage** [comment]
Great - sounds good. Would love to see the outcome. You can of course use complex filters to group stuff together across formal boundaries (eg, anything with a certain string...).

**Comment by florianm** [comment]
Currently it looks like [this](http://catalogue.beta.data.wa.gov.au/dataset/habitat-sampling-initiative/resource/e925914f-0172-4729-88c9-e13b99a56d4f) - here's the [gist](https://gist.github.com/anonymous/42bcb98daa0eb89ee5b4) of it.

Is it possible to initialise NM with the config from my gist directly through the URL?

**Comment by meh9** [comment]
Yeah, just add a `#` on the end of the URL and add the URL of your (raw) Gist:

http://nationalmap.gov.au/#https://gist.githubusercontent.com/anonymous/42bcb98daa0eb89ee5b4/raw/6c17009cdf04e40b9d13feda739e6e3e3a147453/datasource.json

**Comment by florianm** [comment]
@meh9 apologies, that was an unclear question :-) I was wondering whether I could initialise NM without the detour through a gist, and by appending my url-encoded config directly to the NM url.

**Comment by florianm** [comment]
As in e.g.
http://nationalmap.research.nicta.com/#&init=%7B%0A%20%20%20%20%22version%22%3A%20%220.0.05%22%2C%0A%20%20%20%20%22initSources%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22catalog%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22data.wa.gov.au%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22group%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22items%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22ckan%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22Habitat%20Sampling%20Initiative%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22url%22%3A%20%22http%3A%2F%2Fcatalogue.beta.data.wa.gov.au%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22groupBy%22%3A%20%22group%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22filterQuery%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22fq%3Dgroups%3Ahabitat-sampling-initiative%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22includeGeoJson%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22isOpen%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22description%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22includeWms%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22includeKml%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22includeCsv%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22includeEsriMapServer%22%3A%20true%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22isOpen%22%3A%20true%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22homeCamera%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22west%22%3A%20100%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22east%22%3A%20150%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22north%22%3A%20-10%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22south%22%3A%20-50%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D


```
{
    "version": "0.0.05",
    "initSources": [
        {
            "catalog": [
                {
                    "name": "data.wa.gov.au",
                    "type": "group",
                    "items": [
                        {
                            "type": "ckan",
                            "name": "Habitat Sampling Initiative",
                            "url": "http://catalogue.beta.data.wa.gov.au",
                            "groupBy": "group",
                            "filterQuery": [
                                "fq=groups:habitat-sampling-initiative"
                            ],
                            "includeGeoJson": true,
                            "isOpen": true,
                            "description": "",
                            "includeWms": true,
                            "includeKml": true,
                            "includeCsv": true,
                            "includeEsriMapServer": true
                        }
                    ],
                    "isOpen": true
                }
            ]
        },
        {
            "homeCamera": {
                "west": 100,
                "east": 150,
                "north": -10,
                "south": -50
            }
        }
    ]
}
```

**Comment by meh9** [comment]
@florianm yes, simply replace the `&init` with `start` so that the url that you just pasted starts like this and everything works!

http://nationalmap.research.nicta.com/#start=%7B%...

**Comment by florianm** [comment]
no way!! it works! amazing!
http://nationalmap.research.nicta.com/#clean&start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%7B%22catalog%22%3A%5B%7B%22name%22%3A%22data.wa.gov.au%22%2C%22type%22%3A%22group%22%2C%22items%22%3A%5B%7B%22type%22%3A%22ckan%22%2C%22name%22%3A%22Habitat%20Sampling%20Initiative%22%2C%22url%22%3A%22http%3A%2F%2Fcatalogue.beta.data.wa.gov.au%22%2C%22groupBy%22%3A%22group%22%2C%22filterQuery%22%3A%5B%22fq%3Dgroups%3Ahabitat-sampling-initiative%22%5D%2C%22includeGeoJson%22%3Atrue%2C%22isOpen%22%3Atrue%2C%22description%22%3A%22%22%2C%22includeWms%22%3Atrue%2C%22includeKml%22%3Atrue%2C%22includeCsv%22%3Atrue%2C%22includeEsriMapServer%22%3Atrue%7D%5D%2C%22isOpen%22%3Atrue%7D%5D%7D%2C%7B%22homeCamera%22%3A%7B%22west%22%3A100%2C%22east%22%3A150%2C%22north%22%3A-10%2C%22south%22%3A-50%7D%7D%5D%7D

@meh9 and @stevage thanks for your help!
