### ISSUE TITLE
Remove National Datasets -> Vegetation -> [Fractional Cover, Mangroves]

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#1200]
Remove National Datasets -> Vegetation:
1. Fractional Cover group
2. Mangroves
as the layers in these groups are no longer working.

<img width="1224" alt="Screen Shot 2022-11-07 at 14 37 47" src="https://user-images.githubusercontent.com/5283003/200221522-8d79853d-40be-41e1-a4bb-3f1eeca1f707.png">

**Comment by meh9** [comment]
Turns out also National -> Water -> Water Observations From Space has lots of issues. The circled ones below do not work. Note that the `All water observations combined` individual top layer as well as the group with the same name does work, so can't just remove the entire category (unless we intentionally decide to do that):

<img width="484" alt="Screen Shot 2022-11-07 at 14 53 36" src="https://user-images.githubusercontent.com/5283003/200223417-3fc08909-27d0-4ef2-96ed-c63cbd30022b.png">

**Comment by AnaBelgun** [comment]
duplicated ticket https://github.com/TerriaJS/nationalmap/issues/1172
