### ISSUE TITLE
Delete Randwick local government data group

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1201]
Randwick city council has confirmed their open data portal is not available at this stage with now ETA for re-instating. 
To avoid confusion, please delete the data group from Local Governments - NSW - Live data sub-folder. 

![image](https://user-images.githubusercontent.com/18452161/204167933-adde7979-d841-4156-a773-20b2d14edba2.png)

**Comment by t83714** [comment]
PR merged and checked on the national map prod site:
![image](https://user-images.githubusercontent.com/674387/208346050-a29582c5-2962-4e6a-aef2-bb83c5c8fe26.png)
