### ISSUE TITLE
Check and update QLD web services 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1202]
QLD Globe is about to update its web services/end points. https://spatial-qld-support.atlassian.net/servicedesk/customer/portal/2/article/122257646

**Comment by AnaBelgun** [comment]
Update 12 Apr: 
- the files to update might be under Terria SaaS Catalogue public repo: https://github.com/TerriaJS/saas-catalogs-public

**Comment by sixlighthouses** [comment]
updated dev and test ready for review

**Comment by AnaBelgun** [comment]
Update 21 Apr 23: 
- in https://qld.digitaltwin.terria.io/ we will need to keep the Land and Property Administration data group because it has some 3D cadastre data prototypes done specifically by QLD Dept of Resources for the Digital Twin. 
https://qld.digitaltwin.terria.io/#share=s-gKDB0WUq11nrS3xo7J31x74ASkH
- there might be some overlap with some datasets in Planning & Cadastre https://test.qld.digitaltwin.terria.io/#share=s-w0aGnBNSR7uMneZBLCtXBnz25iq but for now let's keep them both

**Comment by sixlighthouses** [comment]
Added back the Land and Property Admin.. to dev
![image.png](https://images.zenhubusercontent.com/6396cf6ae52d054e37b49345/4ba88376-7734-4441-88ab-325212276c2a)

**Comment by staffordsmith83** [comment]
UPDATE 21 June 2023:
Services work in `dev` and `test` but not in `prod` - Brendan is looking into it.

**Comment by AnaBelgun** [comment]
Update 28 Jun 23: 
- wait until Jacky finishes the Magda v1.0 update to get the datasets working in TEST and PROD
