### ISSUE TITLE
Update National Native Title Tribunal data in curated catalogue section

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1212]
All NNTT datasets are currently broken on both data.gov.au and NationalMap due to un-announced changes to webservices. 
To replace current NNTT datasets on NatMap under Boundaries as follows: 
### Boundaries
- [ ] rename Native Title Boundaries with Native Titles 
- [ ] replace current dataset with this list: https://services2.arcgis.com/rzk7fNEt0xoEp3cX/arcgis/rest/services/NNTT_Custodial_AGOL/FeatureServer

**Comment by mwu2018** [comment]
@AnaBelgun
- The new URL is a `esri-featureServer-group` type. Should we give it a new name instead of `Indigenous Reserves`?
- Please check it [here](https://nationalmap.dev.saas.terria.io/#share=s-uQPteIIModtsVxCWeptdhEovlWk).

**Comment by AnaBelgun** [comment]
@mwu2018 thank you. We have to follow the naming conventions the Tribunal has ad literam. If that's the new name appearing for the service, we should definitely follow it.

**Comment by mwu2018** [comment]
@AnaBelgun Please see my updated comment above.

**Comment by mwu2018** [comment]
Done.
