### ISSUE TITLE
Check and add ABS Data by Region 2023 release 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1214]
On Wednesday 21 June, ABS released its six-monthly update to [Data by region (DBR)](https://dbr.abs.gov.au/).
 
Data by region is a visual compendium of regional data, enabling users to find data for over 4,500 regions across Australia.  It contains over 800 data items, covering a range of themes including Population, Economy and Industry, Income, Education, Employment and Land and Environment.
 
The key contents of this update include: 
·         New data items from 2021 Census, including industry of employment, education and qualification levels, youth engagement, labour force status, and household size & income
·         Socioeconomic indexes for areas (SEIFA)
·         Homelessness counts and rates
·         Estimated Resident Population (ERP)
·         Births and deaths
·         Internal and overseas migration
·         Counts of businesses
·         Building approvals and estimates of dwelling stock
·         Selected government pensions and allowances
 
Accessing the data
Data is published through our interactive map interface, available at [dbr.abs.gov.au](http://dbr.abs.gov.au/), and can also be accessed as downloadable [datacubes](https://www.abs.gov.au/methodologies/data-region-methodology/2011-22#data-downloads). 
 
Data can also be accessed through ABS Data Explorer, as data tables and APIs, by visiting the following links:
[Data by region by Australian Statistical Geography Standard Main Structure (ASGS Edition 3, 2021) ](https://explore.data.abs.gov.au/vis?fs%5b0%5d=Data%20by%20region%2C0%7CAustralian%20Statistical%20Geography%20Standard%20-%20Main%20Statistical%20Area%20Structure%23ASGS%23&pg=0&fc=Data%20by%20region&df%5bds%5d=DATA_BY_REGION_TOPICS&df%5bid%5d=ABS_REGIONAL_ASGS2021&df%5bag%5d=ABS&df%5bvs%5d=1.0.0&pd=2020%2C&dq=..AUS.A)
[Data by region by Local Government Area (ASGS Edition 3, LGA 2021)](https://explore.data.abs.gov.au/vis?fs%5b0%5d=Data%20by%20region%2C1%7CLocal%20Government%20Areas%23LGA%23%7CLocal%20Government%20Areas%202021%23LGA2021%23&pg=0&fc=Data%20by%20region&df%5bds%5d=DATA_BY_REGION_TOPICS&df%5bid%5d=ABS_REGIONAL_LGA2021&df%5bag%5d=ABS&df%5bvs%5d=1.0.0&pd=2020%2C&dq=..10050.A)
[Data by region by Indigenous Structure (ASGS Edition 3, 2021)](https://explore.data.abs.gov.au/vis?fs%5b0%5d=Data%20by%20region%2C0%7CIndigenous%20Areas%23INDIG%23&pg=0&fc=Data%20by%20region&df%5bds%5d=DATA_BY_REGION_TOPICS&df%5bid%5d=ABS_REGIONAL_INDIGENOUS_2021&df%5bag%5d=ABS&df%5bvs%5d=1.0.0&pd=2011%2C&dq=..101.A)
[Data by region by Remoteness Areas (ASGS Edition 2, 2016)](https://explore.data.abs.gov.au/vis?fs%5b0%5d=Data%20by%20region%2C0%7CRemoteness%20Areas%23RA%23&pg=0&fc=Data%20by%20region&df%5bds%5d=DATA_BY_REGION_TOPICS&df%5bid%5d=ABS_REGIONAL_REMOTENESS&df%5bag%5d=ABS&df%5bvs%5d=1.2.0&pd=2016%2C&dq=..10.A)
 
Details of the concepts, sources, and methods for Data by region can be found on our [methodology](https://www.abs.gov.au/methodologies/data-region-methodology/2011-22) page.
 
Connections to other Commonwealth data services
Data by region content available on other Commonwealth platforms, including the [Digital Atlas of Australia](https://www.ga.gov.au/scientific-topics/national-location-information/digital-atlas-of-australia), and the [Progress in Australian Regions & Cities Dashboard](https://www.infrastructure.gov.au/department/media/news/2021-progress-australian-regions-and-cities-dashboard).  Data by region also provides key socioeconomic data to the [Australian Climate Service](https://www.acs.gov.au/), to help its customers understand threats posed by climate change and natural hazards.
 
Next release
The next scheduled update to Data by region on the ABS website will be in November 2023.
 
For any questions regarding the statistical data in Data by region, please contact the ABS on [client.services@abs.gov.au](mailto:client.services@abs.gov.au), or by phoning 1300 135 070. 
 
If you would like to provide feedback on the Data by Region application, please contact [small.area.statistics.and.insights@abs.gov.au](mailto:small.area.statistics.and.insights@abs.gov.au).

**Comment by mwu2018** [comment]
Slack discussion
```
mike.wu
  [3:51 PM](https://terria.slack.com/archives/C4NCJT799/p1689227484630749)
Does terria support ArcGIS pbf format?


Mats Henrikson
:vibing:  [4:02 PM](https://terria.slack.com/archives/C4NCJT799/p1689228158657209)
[@mike.wu](https://terria.slack.com/team/U2RNQTMB2)
 I think maybe 
[@Brendon](https://terria.slack.com/team/U04EQ4J6KB5)
 may know things about ArcGIS vector tiles protobuf?


Brendon
  [4:03 PM](https://terria.slack.com/archives/C4NCJT799/p1689228218984089)
yes, the layers we fed through tileserver-gl are ArcGIS pbf tiles


mike.wu
  [4:04 PM](https://terria.slack.com/archives/C4NCJT799/p1689228240423569)
What type should I use?
[4:04](https://terria.slack.com/archives/C4NCJT799/p1689228266356169)
tileserver-gl?


Brendon
  [4:04 PM](https://terria.slack.com/archives/C4NCJT799/p1689228280675449)
let me grab the config we used one second
[4:07](https://terria.slack.com/archives/C4NCJT799/p1689228461055979)
we need to add the arcgis layer to the tileserver-gl  then you can use the url template item
 {
            "image": "https://nsw.digitaltwin.terria.io/api/v0/tileserver-gl/styles/nsw-hybrid/7/116/76.png",
            "item": {
              "allowFeaturePicking": false,
              "id": "nsw-basemap-hybrid",
              "name": "NSW Basemap Hybrid Server",
              "opacity": 1,
              "type": "url-template-imagery",
              "maximumLevel": 15,
              "url": "[https://nsw.digitaltwin.terria.io/api/v0/tileserver-gl/styles/nsw-hybrid/{z}/{x}/{y}.png](https://nsw.digitaltwin.terria.io/api/v0/tileserver-gl/styles/nsw-hybrid/%7Bz%7D/%7Bx%7D/%7By%7D.png)"
            }
          },
[4:08](https://terria.slack.com/archives/C4NCJT799/p1689228481288479)
currently we have tileserver-gl only on nsw DT


mike.wu
  [4:10 PM](https://terria.slack.com/archives/C4NCJT799/p1689228633424899)
I am investigating ABS new regional datasets. Their API example specifies pdf format but I can change it to json like
[https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/STE/MapServer/1/query?f=json&re[…]0000%2C%22falseM%22%3A-100000%2C%22mUnits%22%3A10000%7D%7D%7D](https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/STE/MapServer/1/query?f=json&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A10018754.171386965%2C%22ymin%22%3A-5009377.085690986%2C%22xmax%22%3A15028131.25708294%2C%22ymax%22%3A0.000004991888999938965%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100&quantizationParameters=%7B%22mode%22%3A%22view%22%2C%22originPosition%22%3A%22upperLeft%22%2C%22tolerance%22%3A9783.939620499958%2C%22extent%22%3A%7B%22xmin%22%3A10777612.6166%2C%22ymin%22%3A-5425372.867699999%2C%22xmax%22%3A18701455.7099%2C%22ymax%22%3A-1022048.4730999991%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%2C%22xyTolerance%22%3A0.001%2C%22zTolerance%22%3A0.001%2C%22mTolerance%22%3A0.001%2C%22falseX%22%3A-20037700%2C%22falseY%22%3A-30241100%2C%22xyUnits%22%3A10000%2C%22falseZ%22%3A-100000%2C%22zUnits%22%3A10000%2C%22falseM%22%3A-100000%2C%22mUnits%22%3A10000%7D%7D%7D)
The thing new to me is that they use query endpoint. So I am not sure how terria is going to handle it.


Brendon
  [4:12 PM](https://terria.slack.com/archives/C4NCJT799/p1689228750950439)
I see, that will return ESRI json I think, not quite the same as geosjon
[4:14](https://terria.slack.com/archives/C4NCJT799/p1689228844904789)
this url will gve you the WMS/WMTS may be easier to use one of those  https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/STE/MapServer


Mats Henrikson
:vibing:  [4:15 PM](https://terria.slack.com/archives/C4NCJT799/p1689228956400999)
[@mike.wu](https://terria.slack.com/team/U2RNQTMB2)
 sorry, I obvs don’t know all the details, but if we’re just planning to add them to NatMap or something, why don’t we use the native MapServer REST format that we support well?
[4:16](https://terria.slack.com/archives/C4NCJT799/p1689228990276969)
i.e. esri-mapServer format with this URL: https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/STE/MapServer ?


mike.wu
  [4:17 PM](https://terria.slack.com/archives/C4NCJT799/p1689229027186019)
The native one does not return feature data. Need to add some extra parameters.


Brendon
  [4:18 PM](https://terria.slack.com/archives/C4NCJT799/p1689229081976389)
https://geo.abs.gov.au/arcgis/services/ASGS2021/STE/MapServer/WFSServer?request=GetCapabilities&service=WFS  -- will give you the features


mike.wu
  [4:19 PM](https://terria.slack.com/archives/C4NCJT799/p1689229166474809)
I am trying to get data from https://dbr.abs.gov.au/


Mats Henrikson
:vibing:  [4:20 PM](https://terria.slack.com/archives/C4NCJT799/p1689229208505159)
it seems to work for me: https://nationalmap.gov.au/#share=s-kSbpZR47Bcp0uM2ODJfON3myGsM
Screenshot 2023-07-13 at 16.19.41.png
 
Screenshot 2023-07-13 at 16.19.41.png
nationalmap.gov.aunationalmap.gov.au
[Terria Map](https://nationalmap.gov.au/#share=s-kSbpZR47Bcp0uM2ODJfON3myGsM)
A web map built on Terria Map


mike.wu
  [4:23 PM](https://terria.slack.com/archives/C4NCJT799/p1689229390694379)
Sorry to confuse you all. I thought we should get more data than that. Probably should use other URL. Need to look further.


Mats Henrikson
:vibing:  [4:24 PM](https://terria.slack.com/archives/C4NCJT799/p1689229472912249)
[@mike.wu](https://terria.slack.com/team/U2RNQTMB2)
 aha - ok, now I’m getting there, sorry, I’m a bit slow! you are investigating if we can add support for getting the extended statistical data that they have added!
[4:25](https://terria.slack.com/archives/C4NCJT799/p1689229524570729)
yes, that is much more data than what is in my screenshot/link - there’s none of the dbr data in mine, you are absolutely correct
[4:26](https://terria.slack.com/archives/C4NCJT799/p1689229562040019)
are you saying that they have included that extended data in the pbf?


mike.wu
  [4:27 PM](https://terria.slack.com/archives/C4NCJT799/p1689229650696679)
I think query endpoint may return more data. Need to check.


Mats Henrikson
:vibing:  [4:29 PM](https://terria.slack.com/archives/C4NCJT799/p1689229760686129)
[@mike.wu](https://terria.slack.com/team/U2RNQTMB2)
 yes, I agree - looks like they’ve been a bit sneaky, and depending on what type of region you click on it puts a URL template together with the relevant ABS region id’s and e.g. requests this URL https://dbr.abs.gov.au/json/pin/pin_SA3_20302.json when you click on the region in my screenshot here
Screenshot 2023-07-13 at 16.29.11.png
 
Screenshot 2023-07-13 at 16.29.11.png


:+1:
1

[4:30](https://terria.slack.com/archives/C4NCJT799/p1689229848327269)
my guess would be that that is all custom app logic that makes that happen - 
[@Brendon](https://terria.slack.com/team/U04EQ4J6KB5)
 is that something you’ve seen before that maybe Esri’s web map can do out of the box? (edited) 


mike.wu
  [4:37 PM](https://terria.slack.com/archives/C4NCJT799/p1689230274331579)
Looking at API doc https://api.gov.au/assets/APIs/abs/DataAPI.openapi.html#/


Brendon
  [4:38 PM](https://terria.slack.com/archives/C4NCJT799/p1689230283445879)
yes I think you are right on the custom logic
[4:38](https://terria.slack.com/archives/C4NCJT799/p1689230327538319)
may have an attribute in the data that is the link in the view data hyperlink


Mats Henrikson
:vibing:  [4:42 PM](https://terria.slack.com/archives/C4NCJT799/p1689230541726639)
yes, I think we have all the “link” data to build the URL available in the usual feature info data


mike.wu
  [5:10 PM](https://terria.slack.com/archives/C4NCJT799/p1689232216260879)
It looks like that the esri map server is for drawing the map and other APIs are used to query specific data that follow SDMX (Statistical Data and Metadata Exchange) standard. Not sure if we already support that standard already or not.


Mats Henrikson
:vibing:  [5:12 PM](https://terria.slack.com/archives/C4NCJT799/p1689232325446539)
yes, we do support SDMX, but it may all be tied up in a specific workflow to get data from [stats.abs.gov.au](http://stats.abs.gov.au/)
```

**Comment by mwu2018** [comment]
We already have a group `ABS.Stat (beta)` https://nationalmap.gov.au/#share=s-lLFVebWd8S0p6wtYNSnELpb8Mz6. Should we just update them for 2023 release or add a completely new group?

**Comment by AnaBelgun** [comment]
Thank you @mwu2018 is it possible to list few examples under each of those points please?

**Comment by mwu2018** [comment]
Take the `ERP (Estimated Resident Population` of NSW in 2022 as example.

The `DBR` by ABS has the following entry.
https://dbr.abs.gov.au/region.html?lyr=ste&rgn=1, where it shows the number of persons is `8 156 386` by 30/06/2022.

The national map `ABS.Stat (beta)` has a few entries.
- https://nationalmap.test.saas.terria.io/#share=s-zy1kbvXah12UVXvfqPJf8vNKDDM, where it shows the number of persions is `8,156,386`, the same as `DBR`.
- https://nationalmap.test.saas.terria.io/#share=s-t8TqUCyTCJxvXZ42p0ozjYkrKDB, where it shows the quarterly (Q4 of 2022) estimate of `8,238,801`.

Both `DBR` and `ABS.Stat (beta)` draw data from the same sources but organise the presentation in different ways.

**Comment by staffordsmith83** [comment]
UPDATE 19 July 2023: 
Removed from sprint because need to go back and check each of these issues about ABS.Stats
@AnaBelgun to check these.

**Comment by staffordsmith83** [comment]
UPDATE 2 August 2023:

Remoteness areas / boundaries has been added already.
This is now obsolete.
