### ISSUE TITLE
Add ASGS edition 3 (2021) boundaries for region mapping

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1219]
We are missing most boundaries from ASGS edition 3 (2021) - https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files

I can find datasets in NationalMap that use the following ASGS edition 3 boundaries:

- [ ] States and Territories - 2021
- [ ] Indigenous Locations - 2021
- [ ] Indigenous Areas - 2021
- [ ] Indigenous Regions - 2021
- [ ] Local Government Areas - 2022
- [ ] State Electoral Divisions - 2021
- [ ] Commonwealth Electoral Divisions - 2021
- [ ] Postal Areas - 2021
- [ ] Suburbs and Localities - 2021
- [ ] Significant Urban Areas - 2021
- [ ] Urban Centres and Localities - 2021
- [ ] Section of State - 2021
- [ ] Section of State Range - 2021
- [ ] Remoteness Area - 2021

There are a few other ASGS edition 3 boundaries that we don't have - but I couldn't find any datasets that use them

- [ ] Mesh Blocks - 2021
- [ ] Australia - 2021
- [ ] Local Government Areas - 2023
- [ ] State Electoral Divisions - 2022
- [ ] Tourism Regions - 2021
- [ ] Australian Drainage Divisions - 2021
- [ ] Destination Zones - 2021

We are also missing a lot of boundaries from ASGS 2016 - but our support for ASGS 2011 seems mostly complete

To add boundaries, we need to convert them to mapbox vector tiles, and then add them to either the global TerriaJS [`regionMapping.json`](https://github.com/TerriaJS/terriajs/blob/main/wwwroot/data/regionMapping.json) - which would probably make sense for ASGS - or add them to map-specific `regionMapping.json` files

We have our helper https://github.com/TerriaJS/boundary-tiles library

One thing to keep in mind, we need to test all SDMX datasets to make sure we don't repeat

- https://github.com/TerriaJS/nationalmap/issues/1157

I did a quick survey of the new ABS geospatial web services. They publish ArcGis MapServer and FeatureServer for ASGS boundaries (at least for 2021) - they even publish OGC API for Features! - but I couldn't find any vector tile support. So we would still need to ingest shapefiles/geopackages and convert them to mapbox vector tiles.

See also 

- https://github.com/TerriaJS/nationalmap/issues/1070

**Comment by nf-s** [comment]
I did a quick survey of the difference in boundaries across ASGS editions - while testing SDMX dataflows in Census 2021 category. It is not good. Here is a [story](https://nationalmap.gov.au/#share=s-nJ4SIQXdmQbzNiK6De3Tnn2o8eL) that shows differences in Postal Areas and State Electoral Divisions

 I think we should remove the following groups as soon as possible

- Census 2021/Commonwealth Electoral Divisions
- Census 2021/Postal Areas
- Census 2021/Remoteness Areas
- Census 2021/Suburbs and Localities
- Census 2021/State Electoral Divisions
- Census 2021/Significant Urban Areas
- Census 2021/Urban Centres, Localities...
- Data by region/Indigenous Areas
- Data by region/Remoteness Areas

There are a few other dataflows that have incorrect or missing regions

- All LGA 2020, 2022, 2023
- Environment/Environmental management dataflows use Natural resource management regions 2011 - the should be 2016

**Comment by nf-s** [comment]
We may need latest LGA and postcode geographies for November for new ASEA datasets

**Comment by AnaBelgun** [comment]
Update meeting GA 29 Sep 23: 
- it would be great if we could have a publicly available catalogue of what regions are supported in NatMap / region mapping and a refresh of the csv-geo-au 
- good opportunity once these are done to communicate via GA and Terria channels

**Comment by nf-s** [comment]
Pretty please also do

- https://github.com/TerriaJS/nationalmap/issues/1232

**Comment by nf-s** [comment]
After we add ASGS 2021 - we need to do some sort of announcement - to discuss how.

Also update csv-geo-au

**Comment by AnaBelgun** [comment]
Update 16 Oct 23: 
- almost fully processed and ready to be uploaded to region mapping server
- final testing and start uploaded today

**Comment by ljowen** [comment]
- Upload today

**Comment by AnaBelgun** [comment]
Update 23 Oct 23: 
- push CLUE config and finish the PR today

**Comment by nf-s** [comment]
After release, create a list of SDMX dataflows to send to ABS for QA

**Comment by nf-s** [comment]
This will be in for next release - @nf-s to go through and update SDMX with new regions

**Comment by nf-s** [comment]
In production!
