### ISSUE TITLE
Communications data updates

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1220]
- [x] Mobile Black Spot Database listed under the category of Communications in curate part of National Datasets catalogue needs to be removed as soon as possible.
- [x] Add Mobile Black Spot Program - Round 5A Funded Base Stations dataset to the same category of Communications. I believe the dataset can be sourced from DGA (https://data.gov.au/dataset/ds-dga-d7b82566-3950-4c86-91bb-e4f7e6d45356/details?q=)
- [x] Rename Mobile Black Spot Program - PL Round Funded Base Stations that is currently in this category, to Mobile Black Spot Program – Round 3 (Priority Locations) Funded Base Stations as per DGA (https://data.gov.au/dataset/ds-dga-1e0378ca-05c5-4bfb-8eb8-b4b1ea2ed9cf/details?q=).

**Comment by AnaBelgun** [comment]
hi @mwu2018 or @t83714 is it possible to include this in next week's SaaS release please? the changes have just come through

**Comment by t83714** [comment]
@AnaBelgun 
When you have time, could you please have a look if dev site looks OK? If so, I will copy the changes to test & prod.

**Comment by AnaBelgun** [comment]
@t83714 sorry silly question, but what is the dev site used for this? thank you.

**Comment by AnaBelgun** [comment]
all good to go; we can release now thank you @t83714

**Comment by t83714** [comment]
the changes are in prod site now:

https://nationalmap.gov.au/#share=s-aaOuvtmusIoDgLwDFcu5v3MKyhS

<img width="540" alt="CleanShot 2023-09-07 at 14 20 00@2x" src="https://github.com/TerriaJS/nationalmap/assets/674387/7c866895-b9a1-4490-9806-6f0587812c86">
