### ISSUE TITLE
Fix nationalmap/about page & logos to redirect to GA's NationalMap page

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1221]
- when users click on NationalMap About page button, they are correctly redirected to https://www.ga.gov.au/scientific-topics/national-location-information/nationalmap 
- the url https://nationalmap.gov.au/about points to an old About page
- the NationalMap logo and branding points to the old about page 

TODO
- nationalmap/about redirects to https://www.ga.gov.au/scientific-topics/national-location-information/nationalmap 
- redirect Logos to https://www.ga.gov.au/scientific-topics/national-location-information/nationalmap

**Comment by nf-s** [comment]
- [ ] https://github.com/TerriaJS/saas-catalogs-public/pull/365

**Comment by AnaBelgun** [comment]
not required any longer
