### ISSUE TITLE
Promote Comms datasets to National Datasets Curated section 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1224]
Please promote under Communications the following datasets (available under DGA section too) 
**Peri-Urban Mobile Program (PUMP) – Round 1**
https://spatial.infrastructure.gov.au/server/services/Peri_Urban_Mobile_Program_PUMP_Round_1/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0
 
**Peri-Urban Mobile Program (PUMP) – Round 2**
https://spatial.infrastructure.gov.au/server/services/Peri_Urban_Mobile_Program_PUMP_Round_2/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0

 
![Screenshot 2023-09-22 at 5 49 36 pm](https://github.com/TerriaJS/nationalmap/assets/18452161/723a53c6-8a82-467b-bc1a-800d20d9fbbd)

**Comment by mwu2018** [comment]
Done. See https://nationalmap.terria.io/#share=s-6xn4gWhfwzHlfQCaiXgmFNtByrK
