### ISSUE TITLE
Check SIP datasets loading performance

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1225]
Data custodian feedback:

we're now having issues with our SIP map loading. It can be viewed here: [SIP Map](https://nationalmap.gov.au/#share=s-6rJvBpzuTW9rBRuGHIwBa0zlz6R). It is now taking a lot longer than usual. There is also an error message but that is due to the missing Interphone dataset.

This issue seems to have arisen after we removed and re-added a number of SIP datasets to the map yesterday because although they showed up as present on the dashboard the underlying data wasn’t available on the map when we searched it and the data catalogue indicated that the data hadn’t yet been added.

**Comment by AnaBelgun** [comment]
**Update 29 Sep 23:**
- data.gov.au investigated and located the he _Interphone Pty Ltd Combined Service Areas_, located beneath the _SIP Register - Interphone Pty Ltd_ collapsible
- The slowness of this https://nationalmap.gov.au/#share=s-6rJvBpzuTW9rBRuGHIwBa0zlz6R might be due to an error thrown for the Telstra combined service 
https://data.gov.au/dataset/ds-dga-4e35d278-cc57-4e7a-b84a-94983d4b48cb/distribution/dist-dga-867344e5-2153-40bf-99af-9456b597bfed/details?q=sip%20telstra
Have tested by adding the url to the map and it seems to work. 
- next step: to check what is the issue with the Telstra dataset error and advice Jackie.

**Comment by nf-s** [comment]
Email sent today

It looks like significant portion of the loading time with your share-link is in loading the entire Data.gov.au catalogue. 
When creating share links with the SIP data, it is best to add data from the “Communications -> Statutory Infrastructure Providers (SIPs)” folder instead from the “Data.gov.au” folder. The “Statutory Infrastructure Providers (SIPs)” folder will load much more quickly than the “Data.gov.au” folder.

I created a new sharelink to demonstrate this - https://nationalmap.gov.au/#share=s-7gFpXtGTjIPlHJgcl2xt6Oz8yEt

Please let me know if this improves loading time for you.

**Comment by nf-s** [comment]
Email sent today

We can investigate creating a SIPs "Combined Service Areas” folder with an “Add all” button to make it easier.
We have an example of this with the “NBN Technology Types” folder in NationalMap

I am going to close this and re-open later if needed
