### ISSUE TITLE
Update Comms datasets

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1226]
Update Communications datasets as per list below. 
Functionality to show all at once - we can do that in configuration (as per DTV "select all" feature applied to Melbourne 3D datasets). 

Could you please correct the following datasets for our National Broadband resource to point to the correct layers on our new server API?
 
Our new WMS service is:
https://spatial.infrastructure.gov.au/server/services/National_Broadband_Network_%E2%80%93_Connections_by_technology_type_%E2%80%93_July_2020/MapServer/WMSServer?request=GetCapabilities&service=WMS
 
 
Our data.gov.au datasets are:
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/5230f085-2395-4e6e-8d4f-fc7721fb5510
Needs to point to our new service:
Layer 0
NBN - Fixed-wireless
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/a4d5bfad-2ea9-4676-a1ac-21da7e1a5e46
Needs to point to our new service:
Layer 1
NBN - Fibre to the Basement
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/03847412-c932-4bc2-a6d8-ba866bb57341
Needs to point to our new service:
Layer 2
NBN - Fibre to the Distribution Point/Curb
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/10f2847d-89dc-41ed-b3e2-c82bfeec98d1
Needs to point to our new service:
Layer 3
NBN - Fibre to the Node
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/63f072f1-ad48-4f1d-9952-a953cc843d54
Needs to point to our new service:
Layer 4
NBN - Fibre to the Premises
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/8aa255f7-06ea-4c64-8a3e-4ee498cf2c71
Needs to point to our new service:
Layer 5
NBN - Hybrid Fibre Coaxial
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/1b0d82c1-c451-4cd3-bef2-04039b424999
Needs to point to our new service:
Layer 6
NBN - Satellite
 
https://data.gov.au/data/dataset/national-broadband-network-connections-by-technology-type/resource/e38ac9e6-3ba1-4369-a063-ca6402e05589
Needs to point to our new service:
All layers
I note just using our WMS service loads all layers in the National Map preview, but the actual link in National Map just turns into a folder where people have to load each layer individually?
Can the link above be set in such a way that national map will have a single link that will load them all?

**Comment by AnaBelgun** [comment]
Update 27 Sep 23: 
- Mike to investigate a fix of styling for feature info

**Comment by mwu2018** [comment]
Done. See https://nationalmap.gov.au/#share=s-pVVniDRM6kHDnOMNkJJhsXbk4al

**Comment by nf-s** [comment]
Update: feature info is fixed!
But found icon bug in "add all"

**Comment by mwu2018** [comment]
Depends on https://github.com/TerriaJS/terriajs/issues/6913.
