### ISSUE TITLE
WPS Wave: Extract Time-series of 2D Wave Spectra is broken

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1227]
https://nationalmap.gov.au/#share=s-7g9wxzE6aVvACf0aFtSmq4wPOqr

A few issues

- The rectangle box is a text field - it should let you select a rectangle on the map

<img width="1204" alt="image" src="https://github.com/TerriaJS/nationalmap/assets/6187649/4dea3e2e-0ef8-4a1b-ae8e-c98a78789d12">

- `WebProcessingServiceCatalogFunction` is incorrectly polling this service for `status`, which is causing an error

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- PyWPS 4.2.2 -->
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
  <ows:Exception exceptionCode="OperationNotSupported" locator="" >
      <ows:ExceptionText>Process does not support the updating of status</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

**Comment by uwer** [comment]
Hi Nick,
I used to maintain these services, why is this one service endpoint treated differently to the others - they are all comping from the same service?
Uwe

**Comment by nf-s** [comment]
Update

- @sixlighthouses is going to try adding support for bbox input - so we get the correct rectangle input UI
