### ISSUE TITLE
Northern Australia Infrastructure Facility boundary

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1228]
New dataset/ boundary to be released soon. 
Pending information from GA. 
Update 4 Oct 23: 
- New end point is https://services-ap1.arcgis.com/ypkPEy1AmwPKGNNv/arcgis/rest/services/Northern_Australia_Infrastructure_Facility/FeatureServer

**Comment by nf-s** [comment]
Live on Digital Atlas - https://digital.atlas.gov.au/datasets/f867030c70724071873927564d17ec59_0/explore?location=-29.705378%2C140.373691%2C4.53

**Comment by dbutrovski** [comment]
A thing to note... We have noticed that the published symbology (yellow outline, transparent polygon fill) is not honored by Esri FeatureServer, items accessed from the hub catalogue default to blue symbology.
I was informed, there’s nothing that can be done until the Esri development team fix this issue. More details can be found here: https://community.esri.com/t5/arcgis-enterprise-questions/arcgis-hub-enterprise-sites-is-there-any/m-p/1019587

The good news is the layer uses the yellow symbology when added to the Digital Atlas map viewer, however, on NationalMap it will need to be restyled.

**Comment by mwu2018** [comment]
Can be verified at https://nationalmap.gov.au/#share=s-qHyGHjHOtgYH7vl3izQjEzVaq4z
