### ISSUE TITLE
Geofabric 2.0 to be decommissioned

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1230]
The Geofabric 2.0 data will be replaced soon with 3.0. 
Details to be confirmed soon. We will need to update the catalogue in case formats change.

Update 3 Oct 2023: 
- Geofrabric v2.0 http://geofabric.bom.gov.au/simplefeatures/ows to be replaced with Geofabric v3.0 https://hosting.wsapi.cloud.bom.gov.au/arcgis/rest/services/ahgf/Geofabric_V3x_All_Products/MapServer
- Mapping of layers is [HERE](https://csiroau.sharepoint.com/:x:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/NationalMap/Data%20%26%20custodians/Geofabric%20-%20BOM/[2023-10-04_GeofabricAPIs_MappingV2toV3.xlsx](https://csiroau.sharepoint.com/:x:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/NationalMap/Data%20%26%20custodians/Geofabric%20-%20BOM/2023-10-04_GeofabricAPIs_MappingV2toV3.xlsx?d=w773621824bd84e178dfbba92004b9ffa&csf=1&web=1&e=ycCKLG)?d=w773621824bd84e178dfbba92004b9ffa&csf=1&web=1&e=ycCKLG)

**Comment by nf-s** [comment]
Waiting for BoM to confirm.

Names aren't human readable - ideally we can point directly at a WMS server with desired group structure and human-readable names

**Comment by nf-s** [comment]
Update

- Geofabric v3.3 is production service
- Use spreadsheet to map old v2 layers to new v3.3 layers
- Make sure to add version number (v3x) to catalog group name and description
- Presumed strong preference for new data in DGA before we add

**Comment by nf-s** [comment]
When we have this in test - contact Matt from BoM to check

**Comment by nf-s** [comment]
Please try to preserve IDs - or use `shareKeys` to keep old share-links working

**Comment by mwu2018** [comment]
The mapping of layers shared link is not available.

**Comment by nf-s** [comment]
Sorry not sure why the link is broken

New link - https://csiroau.sharepoint.com/:x:/r/sites/WebDataPlatformsgroup/Shared%20Documents/General/Terria/NationalMap/Data%20%26%20custodians/Geofabric%20-%20BOM/2023-10-04_GeofabricAPIs_MappingV2toV3.xlsx?d=w773621824bd84e178dfbba92004b9ffa&csf=1&web=1&e=UXFv9z

**Comment by nf-s** [comment]
We will just create `wms-group`

**Comment by mwu2018** [comment]
@AnaBelgun @nf-s 
The datasets are automatically harvested in the group `BoM Geofabric Datasets (V3)` and located in the `Water` group in the test env. See it at https://nationalmap.test.saas.terria.io/#share=s-m33G0QI6B1sFZjf0MbDZFysnoXw

**Comment by nf-s** [comment]
Thanks @mwu2018

Can you please remove all the old Geofabric v2 layers?
These will use the `http://geofabric.bom.gov.au/simplefeatures/ows` url

**Comment by mwu2018** [comment]
> Can you please remove all the old Geofabric v2 layers? These will use the `http://geofabric.bom.gov.au/simplefeatures/ows` url

@nf-s 
- Done with `dev` and `test`. 
- See https://nationalmap.test.saas.terria.io/#share=s-3fJ3vUFTvT24gtf3Inn21WHh0gZ
- Let me know when to propagate the changes to `prod`.

**Comment by nf-s** [comment]
Sent email to BoM today, will wait for response

**Comment by nf-s** [comment]
Hi @mwu2018 

BoM are happy with the changes, can you please push to production, thanks!
