### ISSUE TITLE
Add Mobile Network Hardening Program (MNHP) to Communications data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1235]
Add (duplicate) the following datasets into the Communications data group: 

Mobile Network Hardening Program (MNHP)
MNHP Round 1 - Stage 1 Funded Sites
https://spatial.infrastructure.gov.au/server/services/Mobile_Network_Hardening_Program_MNHP/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0
 
MNHP Round 1 - Stage 2 Funded Sites
https://spatial.infrastructure.gov.au/server/services/Mobile_Network_Hardening_Program_MNHP/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0
 
These can already be seen in our data.gov.au directory on national map:
![Screenshot 2023-10-18 at 2 46 19 pm](https://github.com/TerriaJS/nationalmap/assets/18452161/5d17883b-81cf-488a-9186-f64a0910ef32)

**Comment by nf-s** [comment]
When doing this please setup as `wms-group` pointing to https://spatial.infrastructure.gov.au/server/services/Mobile_Network_Hardening_Program_MNHP/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0

And please sort catalog items by name

**Comment by nf-s** [comment]
In production!
