### ISSUE TITLE
Heavy minerals data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1237]
Check and add this data https://portal.ga.gov.au/persona/heavy-mineral-map-of-australia

**Comment by nf-s** [comment]
Add the WMS group and call it "Mineralogy"

- https://services.ga.gov.au/gis/mineralogy/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

Please put in "Land Cover and Land Use" catalog

Can you also please sort the "Land Cover and Land Use" by alphabetical order

**Comment by nf-s** [comment]
@AnaBelgun do you agree with my comment above?

**Comment by nf-s** [comment]
https://github.com/TerriaJS/saas-catalogs-public//blob/80084f140d94c7a369f8af4c3317ec2116c3333a/nationalmap/catalog/land-cover-land-use/prod.json

**Comment by mwu2018** [comment]
Can be verified at https://nationalmap.gov.au/#share=s-hgJPesLvxcc9PPnCXahYO27ZZNB
