### ISSUE TITLE
Update AURIN datasets

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1240]
new data catalogue is available here 
check and work out which ones / or harvest entire CKAN public API 
https://data.aurin.org.au/

**Comment by mwu2018** [comment]
Metadata are public but data URLs not. Have requested an account from AURIN.

**Comment by mwu2018** [comment]
- WFS services url: https://adp.aurin.org.au/geoserver/wfs
- Access type: wfs-group. Contains large number of layers in flat structure.
- Service access credentials: CSIRO users can generate credentials for API access from https://adp-access.aurin.org.au.
- Need to proxy for the wfs services from adp.aurin.org.au with proxyauth, probably having access to open data only.
- [Terms and conditions](https://aurin.org.au/legal/aurin-terms-of-use/)
- Probably need to inform AURIN that we are going to use their wfs services in the nationalmap.

**Comment by mwu2018** [comment]
- See [dev deployment](https://nationalmap.dev.saas.terria.io/#share=s-wVgGw5dOItSPzV0aQh2ICIG0K6T). It will take a while to load the metadata. Please check if the description is OK.
- This ticket depends on the two referenced PRs below.

**Comment by nf-s** [comment]
Waiting on @AnaBelgun to confirm access control - and check dev site

**Comment by AnaBelgun** [comment]
Emailed AURIN just now.
