### ISSUE TITLE
Remove "Australian Exposure Information" layer group from the catalogue

### ISSUE THREAD

**Issue by dbutrovski** [TerriaJS/nationalmap#1242]
There are 16 layers in the group portraying residential, commercial and industrial data aggregated to SA1 and LGAs geographies. The services were originally setup for a specific client and are now unmaintained (they show old data). These services will be decommissioned without replacement. The service endpoint is https://[services-em.ga.gov.au/geoserver/exposure/ows?service=WMS&version=1.3.0&request=GetCapabilities](https://services-em.ga.gov.au/geoserver/exposure/ows?service=WMS&version=1.3.0&request=GetCapabilities)
GA4 indicates these layers were seldomly used on NationalMap, only 3 of them were viewed 14 times in NationalMap in the period 1 July to 20 October 2023 (and of those instances some are likely our own viewing in making assessment).
This layer group should be removed from the catalogue because it is old data and delivered by an unsupported service. It is in the catalogue hierarchy as "National Datasets" > "Social and Economic" > "Finance, Business and Trade" > "Australian Exposure Information".

**Comment by nf-s** [comment]
Thanks @dbutrovski, we will remove these as part of the next release.

**Comment by nf-s** [comment]
In production!
