### ISSUE TITLE
Add CSIRO Bushfire intelligence data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1243]
Add the following datasets for National Bushfire Intelligence Capability (NBIC) Stage 1 collection
https://data.csiro.au/collection/csiro%3A56790v1 
files here https://data.csiro.au/collection/csiro%3A56790v1

**Comment by nf-s** [comment]
Note on uploading to our GeoServer

- They have COGs in S3
- Some files are quite large
- Need to confirm which extension we have in our GeoServer (S3 or COG)
- https://gis.stackexchange.com/questions/442695/s3-support-for-geotiff-vs-cog-cloud-optimized-geotiff-support-geoserver-co

**Comment by nf-s** [comment]
We have neither extensions - so will probably just put on disk

**Comment by nf-s** [comment]
Update:

emailed today to see if public release of data is planned

**Comment by nf-s** [comment]
Data is back https://data.csiro.au/collection/csiro%3A56790v2

**Comment by nf-s** [comment]
Waiting on COG support, then will proceed
