### ISSUE TITLE
Add Northern Territory State data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1245]
Add in prod https://nationalmap.test.saas.terria.io/#share=s-8KRLCyzyjvSGJCR6NPLBbtxxW2c

**Comment by nf-s** [comment]
We should email whoever runs NTG open data portal - https://data.nt.gov.au/

A lot of shapefiles exist that are behind a server that sometimes requires a login - we should ask them if they can provide links in CKAN that go directly to the files so they are compatible with NationalMap
