### ISSUE TITLE
Tool to check availability of all data services in catalog

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/nationalmap#157]
This would be a tool that could be run eg once per day and send a notification if there are any unavailable data services (eg from government agencies).

**Comment by meh9** [comment]
@peterhassall and I have discussed a tool like this in the past. It would be good if this could be designed in conjunction with @peterhassall so that if possible and desirable he can add automated checks to his monitoring tools.

**Comment by peterhassall** [comment]
I had a chat with @kring and we should be able to put some monitoring in place. It's a little tricky as we need to support CKAN and Socrata instances, so we'll probably use Terria to generate the list of services and feed that into Nagios or equivalent.

**Comment by stevage** [comment]
Related to https://github.com/TerriaJS/terriajs/issues/886

Basically we have this problem that our catalog requires a combination of JSON files, JavaScript interpretation, and off-site requests (eg CKAN) - and currently we have no way to access that assembly outside a browser.

I'd suggest we use PhantomJS in the short term to automate the construction of whatever format Nagios needs, then we can use that as the basis for other "catalog as platform" work in the future.

**Comment by kring** [comment]
In theory, it shouldn't be too hard to get the non-mapping parts of TerriaJS running in Node.  I haven't tried it though.

**Comment by stevage** [comment]
When I tried this previously, it got very difficult: http://stackoverflow.com/questions/31801289/run-browserify-ed-app-in-nodejs
