### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by metanomy** [TerriaJS/nationalmap#166]
1. The official Node docker image recommends against using the [onbuild image](https://hub.docker.com/_/node/)
2. On the TerriaJS [Problems and Solutions](https://github.com/TerriaJS/terriajs/wiki/Problems-and-Solutions) page, it recommends running `npm install` again if the first run returns an error.

Here is an updated Dockerfile that incorporates both concepts:

```
# Docker image for the primary national map application server
FROM node:0.10.41

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install; exit 0
RUN npm install
COPY . /usr/src/app

CMD [ "npm", "start" ]
MAINTAINER briely.marum@nicta.com.au
RUN apt-get update && apt-get install -y gdal-bin
```

I tested this successfully against the AREMI fork of nationalmap.

**Comment by kring** [comment]
@metanomy we're not currently using Docker for deployment, so the Dockerfile has gone unmaintained for awhile now.  If it's helpful to you, and you feel like opening a pull request, I'm happy to merge it, though.
