### ISSUE TITLE
Process for updating catalogue outside of the software release process

### ISSUE THREAD

**Issue by stevage** [TerriaJS/nationalmap#223]
A bit of thinking out loud here.

We want the data.gov.au team (PM&C) to be able to update the NM catalogue without having to wait for the next monthly NM release. 
### Needs:
- data.gov.au can make changes to the catalogue using the Data Source Editor
- They can preview the changes
- They can show us the changes 
- They don't need to locally run anything to get the combined `nm.json` built
- All changes are versioned
- Unclear: does data.gov.au need the ability to push the change out themselves, or are they ok with asking us to do it? (My tentative suggestion is it's better if we do the final technical check, although editorial decisions remain with data.gov.au)
### Proposal
- The catalogue lives at some new repo, perhaps /TerriaJS/NationalMapCatalogue
- NM accesses the repo directly from there, using RawGit
- data.gov.au have a fork at /DataGovAu/NationalMapCatalogue
- They can make changes to their fork, previewing as they go
- When ready to make a change, they send a pull request.
- We double check the PR, build the combined nm.json, and commit it back. 

Comments, @tobybellwood ?

**Comment by tobybellwood** [comment]
I like the dga fork, edit test / PR to D61 / D61 commit - that gives good oversight.  Will organise a discussion this/next week around testing procedure etc
