### ISSUE TITLE
Update ACT Government data urls

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#299]
Released
final open datasets and metadata under creative commons.
Some metadata has changed to reflect new datasets.

The categories are attached in the spreadsheet and associated new map service URLS
Metadata was reviewed and updated and is accessed through here via each dataset: http://actmapi.actgov.opendata.arcgis.com/

[Copy of National Map and ACT Data Categories.xlsx](https://github.com/NICTA/nationalmap/files/377218/Copy.of.National.Map.and.ACT.Data.Categories.xlsx)

**Comment by stevage** [comment]
[Google Sheets version of spreadsheet](https://docs.google.com/spreadsheets/d/16A2FTH3d071NqZ-gAEV56Sf-oSdBjbvI9n1-NuFJ-J8/edit?usp=sharing)
