### ISSUE TITLE
Out of date NSW LGA boundaries

### ISSUE THREAD

**Issue by kring** [TerriaJS/nationalmap#303]
Email from someone at planning.nsw.gov.au dated 2016-08-05:

> National Map catalogue has out of date data for NSW LGA boundaries. See https://www.strongercouncils.nsw.gov.au/  for reference
> 
> A number of changes to NSW LGA boundaries occurred 12/5/2016.  Further changes are pending.

**Comment by tobybellwood** [comment]
Closed in favour of #386
