### ISSUE TITLE
Update regionmapping.json to csv-geo-au (AEC boundaries 2016)

### ISSUE THREAD

**Issue by stevage** [TerriaJS/nationalmap#319]
https://github.com/TerriaJS/nationalmap/blob/master/wwwroot/data/regionMapping.json

Doesn't follow csv-geo-au: should be ced_aec_code_2016, not com_elb

**Comment by tobybellwood** [comment]
Com_elb had been suggested to avoid using the abs terms ced and sed, using com_elb nsw_elb etc, and allow us to use districts too eg wa_eld

**Comment by RacingTadpole** [comment]
I've just had a query from a user about why their csv file isn't working; he is using the column name `ced_aec_name_2016`.  Note neither `ced_aec_name_2011` nor `ced_aec_name` works either, although they are listed as examples of csv-geo-au in [the docs](https://github.com/TerriaJS/nationalmap/wiki/csv-geo-au).

Can we add all 3 of these to all our maps? Is there a workaround in the meantime (@stevage?)?

**Comment by stevage** [comment]
Ok, let's spell it all out, in the form of a brain dump.

There are electoral boundaries, managed by the AEC, which tends to use the term "com_elb" (commonwealth electoral boundaries). These are updated from time to time, between elections. For simplicity, the Parliamentary Library uses the year of the election to refer to them (so, a boundary that was modified in 2009 for the 2010 election would be called a 2010 boundary).

There are approximations of these, matching ASGS blocks, managed by the ABS, which uses the term CED (commonwealth electoral divisions). The ASGS gets updated every year, but I think the CEDs [get updated in line with the AEC](http://www.abs.gov.au/AUSSTATS/abs@.nsf/allprimarymainfeatures/974977DD341E5C8DCA257D17001192BB?opendocument).

The ABS uses names that exactly match the AEC ones, but allocates its own 3 digit IDs. The AEC doesn't seem to provide IDs (in the PSMA Administrative Boundaries downloads there are ids like NSW47).

We currently have these boundaries loaded in our productionregion-mapping geoserver:

* [ABS 2011 CED](http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_2011_AUST&styles=&bbox=96.816941408,-43.740509603,159.109219008,-9.142175977&width=768&height=426&srs=EPSG:4326&format=application/openlayers)
* [AEC 2007](http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_AEC_2007&styles=&bbox=96.817997,-43.74051,159.105442,-9.142186&width=768&height=426&srs=EPSG:4326&format=application/openlayers)
* [AEC 2010](http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_AEC_2010&styles=&bbox=96.816766,-43.74051,159.109219,-9.142176&width=768&height=426&srs=EPSG:4326&format=application/openlayers)
* [AEC 2013](http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_AEC_2013&styles=&bbox=96.816766,-43.74051,159.109219,-9.142176&width=768&height=426&srs=EPSG:4326&format=application/openlayers)
* [AEC 2016](http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_COM20160509_ELB&styles=&bbox=96.81676599999999,-43.74050999999999,159.10921899999994,-9.142175999999997&width=768&height=426&srs=EPSG:4326&format=application/openlayers)
*[AEC 2016 again](http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_AEC_2016&styles=&bbox=96.816766,-43.74051,159.109219,-9.142176&width=768&height=426&srs=EPSG:4326&format=application/openlayers)

All the AEC layers, except the very last one, also have the ABS ids. Maybe @steve9164 merged them in. It seems every so slightly weird to use ABS ids to refer to actual AEC boundaries, but, whatever.

On our development region-mapping server (regionmap-dev), we also have:

* [ABS CED 2013](http://regionmap-dev.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_2013_AUST&styles=&bbox=96.816941408,-43.740509603,159.109219008,-9.142175977&width=768&height=426&srs=EPSG:4326&format=application/openlayers)
* [ABS CED 2016](http://regionmap-dev.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_CED_2016_AUST&styles=&bbox=96.816941408,-43.740509603000035,159.109219008,-9.142175977&width=768&height=426&srs=EPSG:4326&format=application/openlayers)

Now, what column names should we support? Probably this:

* `ced`,`ced_code`, `ced_code_2016` -> ABS boundary, 2016 release, matched by code
* `ced_name`, `ced_name_2016` -> ABS boundary, 2016 release, matched by name
* `ced_code_2013`, `ced_code_2011`, `ced_name_2013`, `ced_name_2011` -> ABS boundary, 2013/11 release (etc etc)
* `com_elb_name`, `com_elb_name_2016`, `ced_aec_name`, `ced_aec_name_2016` -> AEC boundary, 2016 election, matched by name
* `com_elb`, `com_elb_code`, `com_elb_code_2016`, `ced_aec`, `ced_aec_code`, `ced_aec_code_2016` -> AEC boundary, 2016 election, matched by ABS id
* (and similar for 2007, 2010, 2013)

Should we prefer `com_elb` over `ced_aec` or vice versa?

**Comment by tobybellwood** [comment]
Agree with the column names above.

com_elb should definitely be preferred - the ced_aec is a confusing conflation of terminology.
Out of interest, given that ced_aec doesn't currently work - can we correct the standard, remove it and handle complaints as they come?

For info the AEC does use a numbering system consistent across the years (http://vtr.aec.gov.au/Downloads/GeneralEnrolmentByDivisionDownload-20499.csv has the 
DivisionID column for 2016 - I have a X-ref somewhere...)

**Comment by stevage** [comment]
Ok, I'll remove it from the standard, but quietly support it for anyone that has already created csvs in that format.

**Comment by stevage** [comment]
Actually...no, supporting a non-standard name is probably a bad move. Let's not do that.

**Comment by stevage** [comment]
Hmm, the AEC "division ID" don't match the ABS codes. We should include those, but label them separately, maybe "com_elb_id".

**Comment by stevage** [comment]
Our 2011 AEC boundaries don't have ABS codes (or division ids for that matter). http://geoserver.nationalmap.nicta.com.au/region_map/region_map/wms?service=WMS&version=1.1.0&request=GetMap&layers=region_map:FID_COM20111216_ELB_region&styles=&bbox=96.816766,-43.74051,159.109219,-9.142176&width=768&height=426&srs=EPSG:4326&format=application/openlayers

**Comment by steve9164** [comment]
Toby got me to add division IDs to the 2016 AEC boundaries (as well as merging the 2011 boundaries with a few of the states that had changed their boundaries for 2016)

**Comment by tobybellwood** [comment]
[aec_div_ids.txt](https://github.com/TerriaJS/nationalmap/files/468818/aec_div_ids.txt)
Here's a list of the AEC division IDs for 2004-2016 - note the renaming of the IDs for Fraser and Throsby in 2016.

**Comment by stevage** [comment]
Yeah, for consistency (I hope) I'll go with `code` = ABS code, `id` = AEC div id.
