### ISSUE TITLE
Close feature cross in wrong location

### ISSUE THREAD

**Issue by LegoStormtroopr** [TerriaJS/nationalmap#362]
If I click a feature the popup shows and the close button is on the left of the titlebar.

![image](https://cloud.githubusercontent.com/assets/2173174/19460740/2a09ef8a-952a-11e6-9472-1dbe29d48f3b.png)

Then when I hover on the 'x' is jumps to the right of the titlebar.

![image](https://cloud.githubusercontent.com/assets/2173174/19460742/3325ec54-952a-11e6-8141-9c9031a77f71.png)

But only in Chrome, Widnows 10.

**Comment by chloeleichen** [comment]
included in this PR: https://github.com/TerriaJS/terriajs/pull/2178

**Comment by kring** [comment]
Fixed by TerriaJS/terriajs#2178.
