### ISSUE TITLE
New ABS boundaries added to ASGS 2016, breaking old links

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/nationalmap#379]
Please get updated ASGS and non-ASGS boundary items from

https://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/ASGS2016BoundariesOnline/MapServer

Addition of new layers has reordered mapserver layers, and muddled existing links to layers  on nationalmap under abs>stat boundaries>2016

**Comment by kring** [comment]
Fixed by https://github.com/TerriaJS/NationalMap-Catalog/pull/32
