### ISSUE TITLE
LGA boundaries are 2011, not 2016

### ISSUE THREAD

**Issue by stevage** [TerriaJS/nationalmap#386]
The 2016 LGA boundaries are available here:

http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1270055003_lga_2016_aust_shape.zip&1270.0.55.003&Data%20Cubes&6A6A6E8944937276CA25802C00142DD2&0&July%202016&13.09.2016&Latest

**Comment by tobybellwood** [comment]
I'm going to look at using the PSMA admin boundary versions (as opposed to the ABS Approximations).

**Comment by RacingTadpole** [comment]
Fixed in #505.
