### ISSUE TITLE
NationalMap-Catalog gulp.task('update-lga-filter' missing (at least one) Local Government

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/nationalmap#388]
I've just noticed that the `gulp.task('update-lga-filter'` in the NationalMap Catalog is missing filtering a Local Government (http://data.gov.au/organization/edit/yarra-ranges-council)

This is because the title isn't filtered in `org.title.match(/city|shire/i)` - **but** if we add council in, we'll also filter out the Australian Research Council...

Can we use `org.extras.value.match(/local/i)` (where it exists) from the url https://data.gov.au/api/3/action/organization_list?all_fields=true&include_extras=true 

I've tried, but handling the undefined ones in map/filter stretches my JS skills too far...

**Comment by tobybellwood** [comment]
Adding http://data.gov.au/organization/cairns-regional-council for reference

**Comment by kring** [comment]
Is this a priority for Monday's release @tobybellwood?

**Comment by tobybellwood** [comment]
Prob not - given it should require edits to the catalog repo only, it should be doable outside the ordinary monthly cycle, and folded in next time we release a catalog.

**Comment by kring** [comment]
Ah yes, good point!
