### ISSUE TITLE
Issue creating CKANCatalogItems from Esri REST sources

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/nationalmap#409]
The reworked Solr query in https://github.com/tobybellwood/NationalMap-Catalog/commit/395e3e7b6af96d65ae0e034845808b1e2189f8ca is now bringing in datasets with 'Esri REST' formats, but these aren't being converted into NM Catalog items.  In most cases one (or more) of the other spatial formats in the dataset are included (TerriaJS/terriajs#2318)

Here are two sample datasets with only Esri REST (MapServer - to avoid TerriaJS/terriajs#2319 issues) links.
http://www.data.gov.au/api/3/action/package_search?rows=100000&fq=name:ga*+AND+res_format:%22Esri%20REST%22

These show up in the new package_search called by NationalMap under the data.gov.au catalog item, but don't end up as a dataset.
http://data.gov.au/dataset/ga_sbagd_framework
http://data.gov.au/dataset/ga_sbagd_transport

Presumably they're being parsed incorrectly somewhere in CKANCatalogItem?

**Comment by kring** [comment]
`CkanCatalogGroup` doesn't include ESRI items by default.  Add `"includeEsriMapServer": true` to your init file.  I tried it and those two sbagd datasets show up and work.

**Comment by tobybellwood** [comment]
oooh - so close to competency!

As expected, this errors when it creates a MapServer item for a FeatureServer as per TerriaJS/terriajs#2319

**Comment by kring** [comment]
I'm working on the FeatureServer and the `(WMS)` thing now.

**Comment by tobybellwood** [comment]
you're awesome (just in case no-one's told you today)

**Comment by kring** [comment]
haha thanks!  that means a lot coming from my favorite client! :)
