### ISSUE TITLE
Download data after geocoding 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#415]
Comment left on Twitter in relation to G-NAF based bulk geocoding feature: 
 how do I download the matched data after I geocode a CSV?

**Comment by tobybellwood** [comment]
I just did this the other day - "Download the currently selected data in CSV format" via "About this dataset" downloads a table with the Lat/Long Pairs and the matched address.
![image](https://cloud.githubusercontent.com/assets/4373945/22497120/622a0c02-e8a3-11e6-9512-1d387eb70cc5.png)

**Comment by tobybellwood** [comment]
...and going back to correct myself - this apparently only works if you've loaded it via a url.  An uploaded csv doesn't offer the "Download the...." option
