### ISSUE TITLE
NationalMap under https can give mixed content

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/nationalmap#416]
Some catalogue items have legend images loaded over http, eg. https://nationalmap.gov.au/#share=s-ffsgaSNcfTfYuYA45qAWifqTenk gives this result:

> Mixed Content: The page at 'https://nationalmap.gov.au/' was loaded over HTTPS, but requested an insecure image 'http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/da…fontSize%3A14%3BforceLabels%3Aon%3BfontAntiAliasing%3Atrue&srs=EPSG%3A3857'. This content should also be served over HTTPS.

Is there anything we can do to prevent this, or does it require an update by the data provider?

**Comment by kring** [comment]
We can rig up TerriaJS to load the legend via the proxy in this scenario.  Actually I'm surprised it's not doing that already.
