### ISSUE TITLE
Redirect http to https?

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/nationalmap#417]
Is it time to redirect http://nationalmap.gov.au to https://nationalmap.gov.au ?

**Comment by philipgrimmett** [comment]
Currently Chrome users receive an error when they attempt to the use the geolocation feature ("only secure origins are allowed"). Ideally we can redirect to https and avoid the alert all together, but if not we should provide the user with an option to remedy the problem e.g. "to access your geolocation please load the map in another browser."

**Comment by kring** [comment]
The best remedy is to manually visit https://nationalmap.gov.au.

I'm all for https-always, but it's GA that needs to do that, not us.

**Comment by philipgrimmett** [comment]
@kring in that case can we link to https://nationalmap.gov.au in the error message?

**Comment by rowanwins** [comment]
This now happens
