### ISSUE TITLE
Should csv-geo-au recognise Customs' 4-letter country codes?

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/nationalmap#420]
This is an Australian Customs-specific format, but it is used by the ABS in this dataset: http://stat.data.abs.gov.au/sdmx-json/dataflow/MERCH_EXP  (and MERCH_IMP).

The 4-letter code mappings are available here: https://www.legislation.gov.au/Details/C2004A03491

Is it worth adding this to csv-geo-au?  I suspect not unless someone requests it.

**Comment by tobybellwood** [comment]
my guess is that this list differs slightly from the ISO-approved one, so would be sufficient to warrant a different set of base polygons anyway.  Would be nice to see the ABS tie this in with SACC (http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1269.0Main+Features12016?OpenDocument) - not that SACC currently contains abbrevations, but they could use the codes...)

**Comment by chris-beer** [comment]
I'll start having a look at "tying it in" it with people here. Question - may I assume at this time that ideally you'll (D61 / wider community) will want ISO (as Geo-spatial have already done with the AUS(036) code in ASGS) as the primary classification/code lists and Customs/SACC to correspond to it?
