### ISSUE TITLE
Missing button to copy link to clipboard

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/nationalmap#430]
![screenshot from 2017-02-21 10 47 53](https://cloud.githubusercontent.com/assets/25913085/23145549/41ffd904-f823-11e6-9c5d-361dba4d1e70.png)

There should be a button they click which copies the link text to the clipboard rather than the more complex instructions of selecting the text and pressing the copy keyboard shortcut. A different button would be needed to copy the embed code.

**Comment by rowanwins** [comment]
A copy button is now available
