### ISSUE TITLE
Shorten URL checkbox appears to have no affect

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/nationalmap#431]
![screenshot from 2017-02-21 10 47 53](https://cloud.githubusercontent.com/assets/25913085/23145588/91afdac6-f823-11e6-8468-6b302c860e39.png)

Clicking or not clicking the checkbox 'Shorten the share URL using a webservice' does not appear to affect the text in any way.

**Comment by kring** [comment]
It certainly has an effect on my system.  The changed part is nearly outside the edit box, so it's a bit subtle... but with shorten enabled, the URL ends with `#share=s-<something>`.  With shorten disabled, it ends with `#start=<some incredibly long string>`.

Can you confirm that you see the same?  It might take half a second for the URL to change when clicking shorten.  If you see it changing like I do, please close this issue.

**Comment by kring** [comment]
@MakeupArtist please see above.
