### ISSUE TITLE
Feedback form does not reset its format after being closed

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/nationalmap#433]
![screenshot from 2017-02-21 10 52 43](https://cloud.githubusercontent.com/assets/25913085/23145669/243b68b0-f824-11e6-8212-70c07e40c569.png)
![screenshot from 2017-02-21 10 53 02](https://cloud.githubusercontent.com/assets/25913085/23145677/2f28b160-f824-11e6-9a7c-037ef526eda9.png)

If you adjust the feedback form then cancel it and reopen it, it reopens to its adjusted form. It does reset back to its clean original form.

**Comment by kring** [comment]
Now that I've fixed #432 (the form gets messed up on resize in the first place), I don't think it's necessary to restore the original size of the feedback form when it's closed and re-opened.  In fact, users might consider that a bug.  So I'm closing this.
