### ISSUE TITLE
'Done' should be 'Clear results'

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/nationalmap#435]
![screenshot from 2017-02-21 10 59 08](https://cloud.githubusercontent.com/assets/25913085/23145768/fece8098-f824-11e6-8575-d3aeb2738cd1.png)

There is a 'Done' button in the top right of the search results that should read 'Clear' or 'Clear results'.

**Comment by kring** [comment]
There is ongoing discussion of the various Close / Clear/ X / Done buttons in TerriaJS in TerriaJS/terriajs#2090.  I'm closing this in favor of that issue.
