### ISSUE TITLE
Update QLD Gov services 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#446]
From Feedback: 

The Queensland Government web services have changed
example of new structure  below https://gisservices.information.qld.gov.au/arcgis/services/GeoscientificInformation/GeologyDetailed/MapServer

*User details*

• Name: Helen Moon
• Email Address: Helen.Moon@dnrm.qld.gov.au
• IP Address: 203.8.131.32
• User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
• Referrer: http://www.nationalmap.gov.au/
• Share URL: http://www.nationalmap.gov.au/#share=s-o3dipRQLueXyVtEqDYDpyLGSFDC

**Comment by tobybellwood** [comment]
I've got updated information from Helen, and just checking they're happy.  It'll be a full catalog hopefully.

**Comment by AnaBelgun** [comment]
Hi @tobybellwood did you get further with QSpatial? The QLD team suggested we use QSpatial, but there are no details available (API etc). Do you have more information on this?

**Comment by AnaBelgun** [comment]
Updated.
