### ISSUE TITLE
Pre prod test v2017-03-15 - Search marker 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#463]
Not sure if this is as per specification:

The search marker (symbol) created by using the Search for 'Canberra' on map is not cleared by the 'Remove All' button/function. See attached screen shot.

![national map v2017-03-15 - search marker](https://cloud.githubusercontent.com/assets/22827786/24232441/2a0c8fa8-0fdf-11e7-8d89-b6bf533e4f1d.jpg)

**Comment by kring** [comment]
This is working as intended.  The search marker is not an item on the workbench, so clearing the workbench shouldn't clear the marker.  To clear the search location, click the X at the right of the search box.  There is a small bug with this, though, which I wrote up as TerriaJS/terriajs#2524.
