### ISSUE TITLE
GA Prehost test v2017-04-13 - Map display hangs after switching between Map Views

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#476]
Layer: National Datasets/Surface Water/Dynamic Hydrology and Marine Layers
Map View and Base Map set to: 3D Terrain/Bing Map Aerials with Labels

Swithched Map view from 3D Terrain: (1) to 3D Smooth (error), (2) to 2D (worked), (3) to 3D Smooth (error), (4) to 3D Terrain (hanged).

**Comment by steve9164** [comment]
This seems to be mainly a problem with the server hosting the layer:
![image](https://cloud.githubusercontent.com/assets/13863530/25211952/3bf1731c-25cb-11e7-9495-d3723b2c2429.png)

When you change Cesium terrain providers (such as switching from 3D Terrain view to 3D Smooth Ellipsoid view), Cesium will use a small amount of large, low detail tiles first to draw layers, then load other smaller more detailed tiles and update the globe as they load. The problem with that layer is that a request for a low detail tile (one that covers all of Australia) takes 1 minute to return.

**Comment by kring** [comment]
Closing as this is not a NationalMap issue.
