### ISSUE TITLE
GA Prehost test v2017-04-13 - Could not load JSON error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#477]
Error displayed when tried to open catalogue item:
Local Government/ New South Wales/ Lake Macquarie/Complying Development Certificates ... Macquarie City Council

**Comment by steve9164** [comment]
This is a CORS error. Since the file is not hosted at a .gov.au address it isn't automatically proxied. Looking at the actual response from the server:
```
{
"data_set": "cdc-submitted-last-week",
"publisher": "Lake Macquarie City Council",
"url": "http://apptracking.lakemac.com.au/modules/ApplicationMaster/openda.aspx?&1=lastweek&4a=434&5=T&format=json",
"date_start": "9/04/2017",
"date_end": "15/04/2017",
"applications": []
}
```
there's nothing to draw anyway.

**Comment by kring** [comment]
Added `lakemac.com.au` to the proxy whitelist.  This doesn't fix the "Complying Development Certificates" dataset for the reason @steve9164 mentioned.  But other datasets (e.g. Natural Resources -> Community Ecosystem Monitoring data - Lake Macquarie City Council) now work (even in IE9).
