### ISSUE TITLE
GA Prehost test v2017-04-13 - Redundant catalogue entry

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#478]
Data.Gov.Au has the following redundant catalogue entry:
No group/This group is empty

**Comment by steve9164** [comment]
I think this is intended behaviour (since the data.gov.au catalogue group is queried from the data.gov.au CKAN and there could be datasets that don't have a group).

**Comment by kring** [comment]
It would be a bit nicer to hide that group when it's empty.  I wrote TerriaJS/terriajs#2525 to track that change.
