### ISSUE TITLE
National Map v2017-05-15 pre-release test - Data Catalogue Search observation

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#494]
Wanted to find the 'State of Environment Map' related catalogue entries.

Attempts:
1. Search string 'State of Environment' - system ran indefinitely for a long time (Slide 1) and returned not found message (Slide 2)
2. Search string 'State Environment' - system returned 2 records (Slide 3)
3. Search string 'Environment' - system returned a long list of records (Slide 4)
4. Search string 'State of Environment ' again - system returned no records (Slide 5)
5. Search string 'State of the Environment' - system returned 1 record (Slide 6)

What is the simplest way to find the 'State of Environment Map' related catalogue entries?

![slide6](https://cloud.githubusercontent.com/assets/22827786/26133204/e35fbf82-3ae8-11e7-8933-3be17e1d654f.JPG)
![slide5](https://cloud.githubusercontent.com/assets/22827786/26133201/e351dbd8-3ae8-11e7-9d50-f74769078f85.JPG)
![slide4](https://cloud.githubusercontent.com/assets/22827786/26133202/e356e72c-3ae8-11e7-964d-25884047a1ee.JPG)
![slide3](https://cloud.githubusercontent.com/assets/22827786/26133203/e35c5c7a-3ae8-11e7-8cd8-d1dd42b21b20.JPG)
![slide2](https://cloud.githubusercontent.com/assets/22827786/26133206/e365a4ce-3ae8-11e7-9d2a-7e477d62da36.JPG)
![slide1](https://cloud.githubusercontent.com/assets/22827786/26133205/e3632b22-3ae8-11e7-9477-7bd39d4678c8.JPG)

**Comment by AnaBelgun** [comment]
related https://github.com/TerriaJS/terriajs/issues/2204
