### ISSUE TITLE
National Map v2017-05-15 pre-release test - CMAR - CSIRO Marine Atmospheric Research data - 'No layer found' error 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#495]
Error displayed when attempted to open 'CMAR - CSIRO Marine and Atmospheric Research' WMS data layers - see  (Slides 7, 8 and 9)

![slide7](https://cloud.githubusercontent.com/assets/22827786/26133401/12132156-3aea-11e7-9b86-e6d07963272e.JPG)
![slide8](https://cloud.githubusercontent.com/assets/22827786/26133402/126568ee-3aea-11e7-9a62-7937365d5425.JPG)
![slide9](https://cloud.githubusercontent.com/assets/22827786/26133437/579ffc1c-3aea-11e7-9d8f-543f97abb122.JPG)

**Comment by AnaBelgun** [comment]
Dealt with; followed up with custodian.
