### ISSUE TITLE
National Map v2017-05-15 pre-release test - Coral Reef Studies ARC Centre .. data layers - 'No layer found' error 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#496]
Error displayed when attempted to open Coral Reef Studies ARC Centre .. data layers - see  (Slide 10)

![slide10](https://cloud.githubusercontent.com/assets/22827786/26133546/2f091b0c-3aeb-11e7-9437-0f8dd00f0418.JPG)

**Comment by AnaBelgun** [comment]
Dealt with; followed up with data.gov.au and custodian.
