### ISSUE TITLE
National Map v2017-05-15 pre-release test - Error opening local government layer

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#498]
Error opening 'Local Government/South Australia/Playford/Historic Places in Playford (LGA)'

See Slide 12

![slide12](https://cloud.githubusercontent.com/assets/22827786/26133756/ecd94ce6-3aec-11e7-9065-a4ce04ba2f58.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and followed up with custodian 

![image](https://user-images.githubusercontent.com/18452161/41761937-61470e52-763c-11e8-8620-5f3f1cff49df.png)
