### ISSUE TITLE
National Map v2017-05-15 pre-release test - Measure Distance tool - Observations

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#499]
Measure Distance tool - two observations:

1. When the last selected point is selected again the line gets deleted - this is in contrary to many web mapping/GIS tools where this confirms the selection of the line/path to measure (Slide 15)

2. Wanted to measure the distance between Sydney and Los Angeles in 2D map view. See Slide 16 - the red broken line ends were my two points selected. The system draws calculated line (shown in white) on the opposite direction across the globe. The distance shown in km appears to be correct. Same test in 3D map view works fine and as expected. Not sure if this 2D issue could be fixed.

![slide15](https://cloud.githubusercontent.com/assets/22827786/26134193/32504d58-3af0-11e7-9c64-34f179683df2.JPG)
![slide16](https://cloud.githubusercontent.com/assets/22827786/26134195/34d695dc-3af0-11e7-8d9d-05cf80c4c698.JPG)

**Comment by AnaBelgun** [comment]
New issue here: https://github.com/TerriaJS/terriajs/issues/3006
