### ISSUE TITLE
Migrate some bathymetry layers to new services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#501]
Please be advised that GA has migrated a bathy data set:

From

http://www.ga.gov.au/gisimg/services/marine_coastal/Multibeam_50m_Bathymetry_2012_RGB/MapServer/WMSServer
To

http://services.ga.gov.au/gis/rest/services/Multibeam_Bathymetric_50m_Colour_2012/MapServer
http://services.ga.gov.au/gis/rest/services/Multibeam_Bathymetric_50m_Greyscale_2012/ImageServer

![bathymetry layer](https://cloud.githubusercontent.com/assets/18452161/26135286/dc508a82-3af7-11e7-9805-75e6de6cc1e7.JPG)

**Comment by meh9** [comment]
We don't have that original layer in the catalogue, must have been picked up from DGA - nothing to do here.
