### ISSUE TITLE
Rewrite Feedback instructions

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#503]
Rewrite feedback instructions, so they provide guidance to users on addressing the non-technical complaints/feedback and help decreasing the number of non-relevant feedback addresses to software developers. 

![image](https://cloud.githubusercontent.com/assets/18452161/26616628/60dc2c7c-4613-11e7-9b5f-9c26acbabc1e.png)

**Comment by AnaBelgun** [comment]
@ajbar7

**Comment by ajbar7** [comment]
Thanks Ana - I'll deal put something in line with the next release.

**Comment by ajbar7** [comment]
@AnaBelgun 

Here's some new text for the feedback form. 

> Thank you for your feedback – please use this form to let us know about your experience using NationalMap. 
> 
> Please note that NationalMap is a visualisation tool for spatial information. As we do not host the datasets viewable on the site we may not be able to provide advice on data content. If you have questions about any specific dataset we encourage you contact the data custodian. You can find additional information about any dataset by clicking on the ‘About this Data Set’ link available with each dataset in the left hand panel.
>

**Comment by AnaBelgun** [comment]
I would only change a bit the last sentence: "you can find their details and other information by clicking on ......

**Comment by AnaBelgun** [comment]
@kring can we change the text on the Feedback form in an effort to decrease the number of irrelevant feedback messages and give users more information on what is the purpose of that form? 
Feel free to amend the text, in case it doesn't fit.
