### ISSUE TITLE
ABS SDMX-JSON items use yearless region mapping alias

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/nationalmap#506]
While browsing through datasets under National Datasets > Social and Economic, it appears that all (or a majority) of datasets use yearless region mapping aliases:
![image](https://user-images.githubusercontent.com/13863530/26909361-8fcb4ad2-4c43-11e7-8eb5-dfdc512aeaf1.png)

This will lead to problems when ASGS 2016 aliases become default (probably this nationalmap release, since 2016 Census data will be released soon after) as the data is being mapped against the wrong version regions.

**Comment by RacingTadpole** [comment]
Thanks Steve. The raw data, eg. http://stat.data.abs.gov.au/sdmx-json/dataflow/ABS_CENSUS2011_B31, just specifies the region as "SA4" etc, so this will require another config override.  Shouldn't be too hard.
