### ISSUE TITLE
National Map v2017-06-15 pre-release test - Catalogue data group unavailable - Queensland Government

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#511]
**Queensland Government - the whole group is unavailable!!**

![slide1](https://user-images.githubusercontent.com/22827786/27366630-b3a65162-568a-11e7-880c-ddfe61deb03a.JPG)

**Comment by RacingTadpole** [comment]
Yes, it seems that https://geospatial.information.qld.gov.au is down or has changed (it has been in the NM catalog for a year).  Someone will need to investigate whether it has been taken down or its URL has changed.

**Comment by AnaBelgun** [comment]
Services updated and working now under the QLD Gov category.
