### ISSUE TITLE
National Map v2017-06-15 pre-release test - Catalogue data group unavailable - Queensland Government (BETA)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#512]
**Queensland Government (BETA) - the whole group of layers is unavailable !!**

![slide2](https://user-images.githubusercontent.com/22827786/27366717-3a6a1d32-568b-11e7-9506-b907f62dc7b3.JPG)

**Comment by RacingTadpole** [comment]
It looks like the layer naming and/or layer hierarchy has changed, eg. https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/layers?f=json no longer returns anything useful.  It looks like it has moved to https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/VegetationManagement/MapServer/layers?f=json .

**Comment by ajbar7** [comment]
@kring do you know the difference between Queensland Government / Queensland Government Beta? Was one supposed to replace the second? If that's the case we can just drop the old one and only fix the beta one.

**Comment by kring** [comment]
Not exactly @ajbar7.  I know it was added by @tobybellwood in https://github.com/TerriaJS/NationalMap-Catalog/pull/46, and he was addressing https://github.com/TerriaJS/nationalmap/issues/446.  The latter indicates the change suggestion came directly from someone in the QLD government.

**Comment by tobybellwood** [comment]
@kring - that pretty much sums it up :-) Not sure why they've gone a server per ISO 19115 Topic code, but  ¯\_(ツ)_/¯

would the existing links work as an "esri-group" - thinking about trying to mitigate against further downstream changes?

**Comment by AnaBelgun** [comment]
Services updated and working now.
