### ISSUE TITLE
National Map v2017-06-15 pre-release test - Climate Futures Tasmania - Scenario's A2 and B1

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#513]
Layer Data.gov.au/Climate Futures Tasmania - Scenario's A2 and B1

- Zoom to extent showing the Indian Ocean - Correct?
- Showing legend but not displaying any data - Correct?

![slide3](https://user-images.githubusercontent.com/22827786/27366860-392f20ba-568c-11e7-9b85-7fcf9781ce4a.JPG)
![slide4](https://user-images.githubusercontent.com/22827786/27366859-392ebab2-568c-11e7-8327-b51cba938b3d.JPG)

**Comment by AnaBelgun** [comment]
Dealt with and followed up with custodian.
