### ISSUE TITLE
National Map v2017-06-15 pre-release test - Layer hangs then generates error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#514]
Layer Data.gov.au/IMOS SOOP Sea Surface Temperature Data Collected ...(Rottnest Island Ferry)

- Hangs
- Displays error message

![slide7](https://user-images.githubusercontent.com/22827786/27366977-1107fd54-568d-11e7-8255-937ab8f2b8be.JPG)
![slide8](https://user-images.githubusercontent.com/22827786/27366978-1114d9de-568d-11e7-976b-213f6b327e36.JPG)
![slide9](https://user-images.githubusercontent.com/22827786/27366979-11197e30-568d-11e7-98c4-bfe1069d95b2.JPG)

**Comment by AnaBelgun** [comment]
Dealt with and followed up with data.gov.au and CSIRO teams.
