### ISSUE TITLE
National Map v2017-06-15 pre-release test - Layer load error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#515]
Layer Data.gov.au/Aurora Australis Voyage 1 2009/10 Track and Underway Data

- Generates error when attempted to load

![slide6](https://user-images.githubusercontent.com/22827786/27367046-948d67a4-568d-11e7-9765-9ae6aab7262f.JPG)
![slide5](https://user-images.githubusercontent.com/22827786/27367045-947b1f72-568d-11e7-85aa-d9e7f5125c93.JPG)

**Comment by kring** [comment]
Not something we can fix.
