### ISSUE TITLE
National Map v2017-06-15 pre-release test - Observation - Catalogue directory label

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#516]
Observation

Catalogue directory label - 'departmentofenvironment'

![slide10](https://user-images.githubusercontent.com/22827786/27367111-ff2781f8-568d-11e7-9cfa-f93d0326275d.JPG)

**Comment by AnaBelgun** [comment]
Nothing we can do at our end at this stage.
