### ISSUE TITLE
National Map v2017-06-15 pre-release test - Feature information display error?

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#517]
**A major Issue**

Layer: Data.gov.au/Department of Agriculture and Water Resources/Annual Family Income, 1997-1997 to 1998-1999 (Three Year Average)

Layer displayed in the map window.
When tried to review feature information by clicking inside NT polygon jiggered lines filled up the map window. 
Tried to clear the lines using 'Remove' and 'Remove All' - only the map layer was removed - lines remained.
Closing the Feature Information window using (x) button cleared the lines. 
Please check Feature Information function compatibility with the data format.

![slide12](https://user-images.githubusercontent.com/22827786/27367302-5452df50-568f-11e7-9e14-507feeada0d2.JPG)
![slide11](https://user-images.githubusercontent.com/22827786/27367303-54550f3c-568f-11e7-96d4-283e4d5c2c06.JPG)

**Comment by RacingTadpole** [comment]
Wow, nice find!  It happens on the live nationalmap.gov.au too, so it's not a problem introduced by this release. We will definitely investigate this one. I suspect there's something funny going on with the polygons on the Agriculture WMS server, since it doesn't happen with other WMS servers I've tried.

**Comment by RacingTadpole** [comment]
This looks like a terria bug.  I'll open a terria issue for it.

**Comment by ajbar7** [comment]
As this should be addressed by https://github.com/TerriaJS/terriajs/issues/2580 it can be closed.
