### ISSUE TITLE
National Map v2017-06-15 pre-release test - Error rendering in 3D

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#518]
**Major Issue**

Layer: Data.gov.au/Department of Agriculture and Water Resources/Farmer Population 1996
Layer: Data.gov.au/Department of Agriculture and Water Resources/Farm Equity Ratio 1996-1997 to 1998-1999 (three year average)

- Layer generated 'Error rendering in 3D' error (see slide below)
- Removed the layer from 
- Second attempt did not display the error message but no data was displayed.
- When tried to query a feature by clicking on the map jig-jagged lines filled the map window.

![slide14](https://user-images.githubusercontent.com/22827786/27367775-1f34bc5a-5692-11e7-8b27-f20d74618ced.JPG)
![slide15](https://user-images.githubusercontent.com/22827786/27367773-1f18db70-5692-11e7-8a99-a4f52461522f.JPG)
![slide13](https://user-images.githubusercontent.com/22827786/27367774-1f1d93b8-5692-11e7-9c9d-1c8a6b20d3ae.JPG)

**Comment by ajbar7** [comment]
As this should be addressed by https://github.com/TerriaJS/terriajs/issues/2580 it can be closed.
