### ISSUE TITLE
National Map v2017-06-15 pre-release test - Error accessing catalogue item

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#519]
Layer: FOI - Index Extent - Vicmap Features of Interest

Error accessing catalogue item

![slide16](https://user-images.githubusercontent.com/22827786/27368003-66480b3c-5693-11e7-8b46-141e5bec6d96.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and although very slow, it doesn't throw an error

![image](https://user-images.githubusercontent.com/18452161/41761090-61238d90-7639-11e8-99ef-bcc2d6038fe5.png)
