### ISSUE TITLE
National Map v2017-06-15 pre-release test - Layer zoom to extent inactive

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#520]
Layer: National Datasets/Social and Economic/Births and Deaths Data/At year of Registration/by Indigenous Status by Sex

- Zoom to extent not working for the dataset
- Can only zoom to extent by using the 'Reset Zoom' tool

![slide18](https://user-images.githubusercontent.com/22827786/27368173-60433990-5694-11e7-963e-9235768ff390.JPG)
![slide19](https://user-images.githubusercontent.com/22827786/27368174-60497d6e-5694-11e7-9bdd-15c8f124101c.JPG)
![slide17](https://user-images.githubusercontent.com/22827786/27368175-604c8cf2-5694-11e7-898f-0f2e7ae3a558.JPG)

**Comment by RacingTadpole** [comment]
Yes, detecting the extent directly from the tabular data is tricky and is a known issue (https://github.com/TerriaJS/terriajs/issues/920).  However it may be a good idea to provide an override specifically for the ABS data (eg. default to all of Australia).  I'll add an issue in Terria to add this.

**Comment by ajbar7** [comment]
This can be closed as it'll be addressed by https://github.com/TerriaJS/terriajs/issues/2579.
