### ISSUE TITLE
National Map v2017-06-15 pre-release test - Bad geojson issue

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#522]
**Major Issue**

This data 3D compatibility issue has been encountered for a number of data layers during this testing.  Suggest review all data in the catalogue for its suitability to display and query on 3D map views - and if possible restrict them in Catalogue for 2D viewing only.

Test summary:

Layer: Local Government/South Australia/Mitcham/Housing, Land, Planning and Infrastructure/City of Mitcham Waste Collection Areas

- Crashed the system on first attempt
- On second attempt displayed jig-jagged black lines on map
- When clicked on one of the lines for feature info, map filled with triangle and generated 'Error rendering in 3D' error

![slide23](https://user-images.githubusercontent.com/22827786/27368788-d753cd8a-5697-11e7-97bb-2511a359231d.JPG)
![slide24](https://user-images.githubusercontent.com/22827786/27368789-d7577d54-5697-11e7-9716-178c6e7eb4ba.JPG)

**Comment by RacingTadpole** [comment]
Wow! I see this in 2D as well.  This happens on the live nationalmap.gov.au too, so it's not a new problem - it looks like some bad geojson at https://data.sa.gov.au/.

**Comment by ajbar7** [comment]
I'll get in touch with the data custodian @ data.sa to inform them of the issue. This can be closed.
