### ISSUE TITLE
National Map v2017-06-15 pre-release test - Error accessing catalogue item

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#524]
Failed to load

Layer BIO1 Global biodiversity hotspots and natural value World Heritage Areas in Australia

![slide28](https://user-images.githubusercontent.com/22827786/27369339-dbf16af2-569a-11e7-9bf7-cb0aa72b2581.JPG)
![slide27](https://user-images.githubusercontent.com/22827786/27369338-dbf0f5ae-569a-11e7-9604-be6a5ab8bb4e.JPG)

**Comment by AnaBelgun** [comment]
Working now
![image](https://user-images.githubusercontent.com/18452161/41760767-62b9eb0a-7638-11e8-8a41-73c1049387ff.png)
