### ISSUE TITLE
National Map v2017-06-15 pre-release test - Missing data error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#525]
Failed to load - Missing data

Layer: 50m Multibeam Dataset of Australia

![slide29](https://user-images.githubusercontent.com/22827786/27369426-318a244a-569b-11e7-80bc-a7d4ce989eb4.JPG)
![slide30](https://user-images.githubusercontent.com/22827786/27369425-3180cc24-569b-11e7-93ec-42358add33df.JPG)

**Comment by RacingTadpole** [comment]
The 50m multibeam items are gone from the catalog now, most likely as a result of the delay between data.gov.au reharvests.
