### ISSUE TITLE
National Map v2017-06-15 pre-release test - Catalogue data unavailable - Geoscience Australia

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#527]
**Major Issue**

Most of the data items listed under 'Data Providers/Geoscience Australia' is inaccessible.

Generating: 'Missing data' and 'Error loading KML or KMZ' errors

![slide33](https://user-images.githubusercontent.com/22827786/27410930-0af93b8e-572e-11e7-8470-84229961b217.JPG)
![slide34](https://user-images.githubusercontent.com/22827786/27410928-0ae90c46-572e-11e7-954a-d9bb13daf187.JPG)
![slide35](https://user-images.githubusercontent.com/22827786/27410929-0af5300c-572e-11e7-874f-60f6e0b17043.JPG)

**Comment by RacingTadpole** [comment]
This one’s over to you guys at GA to fix: zip files have been uploaded to data.gov.au and tagged as KML files, eg. http://www.data.gov.au/dataset/a-probabilistic-tsunami-hazard-assessment-of-the-southwest-pacific-nations/resource/5d520420-1711-4776-bf43-058eb235223d.
