### ISSUE TITLE
National Map v2017-07-21 pre-release test - Error loading layers - Geoscience Australia

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#538]
- Catalogue group: Data Providers/Geoscience Australia
- Layers generating 'Error loading KML or KMZ error (see slide below)
- This issue has been reported in last test report (v2017-06-15) #527 - understand it is being resolved
- Data61 response to #527 - This one’s over to you guys at GA to fix: zip files have been uploaded to data.gov.au and tagged as KML files, eg. http://www.data.gov.au/dataset/a-probabilistic-tsunami-hazard-assessment-of-the-southwest-pacific-nations/resource/5d520420-1711-4776-bf43-058eb235223d.

![slide1](https://user-images.githubusercontent.com/22827786/28650574-0631b15a-72c0-11e7-8011-4c56efe3ba71.JPG)

**Comment by kring** [comment]
I think the fix for this is in progress by GA, but no need for an issue in any case because there's no action on our side currently.  Closing.
