### ISSUE TITLE
Remove Integrated Marine Observing System (IMOS) from Data Providers

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#539]
- Catalogue group: Data Providers/Integrated Marine Observing System (IMOS)
- Layers generating 'Error loading KML or KMZ' error (see slide below)
- This issue has been reported in the past

![slide2](https://user-images.githubusercontent.com/22827786/28650869-e8c9fbca-72c1-11e7-85ff-fb9fba4b74b6.JPG)

**Comment by ajbar7** [comment]
Looks like all IMOS datasets have been removed.

**Comment by kring** [comment]
Removed IMOS from the Data Providers section.
