### ISSUE TITLE
National Map v2017-07-21 pre-release test - Error loading layers - Airborne Research Australia (ARA)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#540]
- Catalogue group: Data.gov.au/Airborne Research Australia (ARA)
- All four layers when activated hangs for a long time then displays the 'Error loading KML or KMZ' error' (See slide below)

![slide3](https://user-images.githubusercontent.com/22827786/28651024-b17d4324-72c2-11e7-8b6d-121f39c8c503.JPG)

**Comment by ajbar7** [comment]
Data comes to data.gov.au via the Australian Oceans Data Network harvest. Looks like there are issues resolving reaching the domain http://146.118.96.76:8080/geonetwork/srv/en/resources.get?uuid=316116c8-f889-42a0-adc3-ddd9aba2dced&fname=080918%20ARA%20Photo%20Waypoints.kmz&access=private.

Not an issue with NationalMap.

**Comment by kring** [comment]
Not something we can fix.
