### ISSUE TITLE
National Map v2017-07-21 pre-release test - Error loading layers - Coral Reef Studies ARC Centre of Excellence, James Cook University

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#542]
- Catalogue group: Data.gov.au/CMAR - CSIRO Marine and Atmospheric Research
- Layers generating 'Error loading KML or KMZ' error

**Comment by ajbar7** [comment]
Looks like there's a request wall at the end point http://eatlas.org.au/geonetwork/srv/eng/file.disclaimer?uuid=70e21d20-cc5e-4d1d-9d2b-7b08f4b061a2&fname=ts-jcu-dugong-rel-density.kmz&access=private

Harvested from the Australian Institute of Marine Science CSW Harvester.

**Comment by ajbar7** [comment]
Harvested from  Australian Oceans Data Network CSW Harvester. Server is not responsive.

**Comment by kring** [comment]
Not something we can fix.
