### ISSUE TITLE
National Map v2017-07-21 pre-release test - Error loading layers - CSIRO Oceans & Atmosphere - Hobart

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#543]
- Catalogue group: Data.gov.au/CMAR - CSIRO Oceans & Atmosphere - Hobart
- Layer generating error (see slide below)

![slide5](https://user-images.githubusercontent.com/22827786/28651443-48cc97c8-72c5-11e7-8882-f1332e31d591.JPG)

**Comment by ajbar7** [comment]
Harvested by data.gov.au from Australian Oceans Data Network CSW Harvester. End point server is not responsive.

**Comment by kring** [comment]
Not something we can fix in NationalMap because we don't know it will be unresponsive until we try it, at which point we display the error.
