### ISSUE TITLE
National Map v2017-07-21 pre-release test - Feature information display error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#544]
- Catalogue group: Data.gov.au/Department of Agriculture and Water Resources
- Feature information display error (See Slide below)
- This error has been reported in June 2017 test report #517 

![slide6](https://user-images.githubusercontent.com/22827786/28653992-4f3a6c8e-72d4-11e7-8ac6-5c37481ef066.JPG)
![slide7](https://user-images.githubusercontent.com/22827786/28653994-53b722de-72d4-11e7-8f72-afdb6562054b.JPG)

**Comment by ajbar7** [comment]
This should be addressed by https://github.com/TerriaJS/terriajs/issues/2580.

@RacingTadpole / @kring - when do we expect that issue to get a look in?
