### ISSUE TITLE
National Map v2017-07-21 pre-release test - Feature information desplay error (more)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#545]
- Catalogue group: Data.gov.au/Department of Agriculture and Water Resources
- Layer: Farms with significant degradation problems (irrigation salinity), 1998-1999

Note:
- Two clicks on same map layer gave different Feature Information results (Slides 8 and 9)
- Also later generates an 'Error rendering in 3D' error and then resets the Map View from 3D to 2D (!!) (Slide 10)

![slide8](https://user-images.githubusercontent.com/22827786/28654181-a8dc9482-72d5-11e7-81c8-1d27a16dd739.JPG)
![slide9](https://user-images.githubusercontent.com/22827786/28654186-b633f3c8-72d5-11e7-84c5-78fd36753fcd.JPG)
![slide10](https://user-images.githubusercontent.com/22827786/28654189-bc353340-72d5-11e7-85e1-eb67fdb259fe.JPG)

**Comment by ajbar7** [comment]
@RacingTadpole - is this the same as https://github.com/TerriaJS/terriajs/issues/2580?
