### ISSUE TITLE
National Map v2017-07-21 pre-release test - Loading JSON error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#546]
- Catalogue group: Data.gov.au/Department of Communications and the Arts
- Layer: Digital Enterprise (GeoJSON)

- It appears that some data in the catalogue are listed with their data format separately. For example: layername(GeoJSON), layername(KML) and layername(WMS)
- In this catalogue group, some layers have duplicate GeoJSON entries (ie Digital Enterprise and Digital Hubs). One of them is generating the 'Could not load JSON' error (See Slide 11 below)

![slide11](https://user-images.githubusercontent.com/22827786/28654600-f08310c4-72d8-11e7-9620-67efcfc3d6d4.JPG)

**Comment by steve9164** [comment]
This is a problem with the dataset's ckan entry: http://search.data.gov.au/dataset/6914b1cc-2047-4849-a8ac-54b98e551a88/details and not a problem with nationalmap. The second GeoJSON entry has a URL that serves this error message instead of GeoJSON:
```
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://data.gov.au:80/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="outputFormat">
<ows:ExceptionText>Failed to find response for output format geojson</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

**Comment by ajbar7** [comment]
Yeah the error is because it's asking for GeoJSON and should just be asking for JSON. I've deleted the entry from data.gov.au as there is one that works above it.
