### ISSUE TITLE
National Map v2017-07-21 pre-release test - Could not load JSON error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#547]
Layer: South Australian Government (BETA)

- Error loading layer - 'Could not load JSON' (See Slide below)

![slide12](https://user-images.githubusercontent.com/22827786/28654839-c0b6e562-72da-11e7-9177-02ad3661587b.JPG)

**Comment by ajbar7** [comment]
Looks like a CORs issue with the data end point: http://realtime.adelaidemetro.com.au/SiriWebServiceSAVM/SiriStopMonitoring.svc/json/SM?MonitoringRef=17754&LineRef=&PreviewInterval=30&StartTime=&DirectionRef=&StopMonitoringDetailLevel=normal&MaximumStopVisits=20&Item=1

@steve9164 can we add 'realtime.adelaidemetro.com.au' to the proxy list?
