### ISSUE TITLE
National Map v2017-07-21 pre-release test - Error accessing catalogue items

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#548]
The following layers generated 'Error accessing catalogue item' error:

**Layers**
- Victorian Government/Admin and Political Boundaries/2010 Index of Stream Condition - Bank Full Width Reach polygon features (see Slides 15-16)
- Victorian Government/Admin and Political Boundaries/2010 Index of Stream Condition - Toe of Bank line features
- Victorian Government/Cadastre & Land Description/Services And Utilities-Public Land Management (Slide 17)
- Victorian Government/Elevation/Ground Surface Point 1:25,000 - Vicmap Elevation. Layer starts to display but fails before completing it (Slides 18-19). 
- Victorian Government/Environmental/2010 Index of Stream Condition - Bank Full Width Reach polygon features (Slide 20). 

![slide15](https://user-images.githubusercontent.com/22827786/28655657-b66480a0-72e0-11e7-993a-6b46c90e4145.JPG)

![slide16](https://user-images.githubusercontent.com/22827786/28655695-e38f8d2c-72e0-11e7-9ee7-de395caedd2b.JPG)

![slide17](https://user-images.githubusercontent.com/22827786/28655761-3ed2569c-72e1-11e7-9b5a-744e32448b78.JPG)

![slide18](https://user-images.githubusercontent.com/22827786/28655737-1416ed3c-72e1-11e7-8ac8-81109524b437.JPG)

![slide19](https://user-images.githubusercontent.com/22827786/28655826-95ae817a-72e1-11e7-8a79-2c9537b80f55.JPG)

![slide20](https://user-images.githubusercontent.com/22827786/28655736-14166ea2-72e1-11e7-977d-e897ae2f0cd2.JPG)

**Comment by ajbar7** [comment]
@steve9164 layers are slow to load perhaps fetch tile requests are timing out? 

![image](https://user-images.githubusercontent.com/7380633/29151679-44ab0b46-7dc6-11e7-9c7f-31c985f3e241.png)

**Comment by kring** [comment]
The Vic server is pretty slow, not something we can fix.
