### ISSUE TITLE
National Map v2017-07-21 pre-release test - Observation - Layer takes long time to display feature

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#549]
**Observation**

The following layer took very long time to generate the features after displaying the layer:

Victorian Government/Environmental/Dry Forests - Exposed and/or lower altitude - Native Vegetation (EVCBCS_2005) (see Slide 21)

![slide21](https://user-images.githubusercontent.com/22827786/28655958-661ccf06-72e2-11e7-9345-bf745b6e7ec1.JPG)

**Comment by ajbar7** [comment]
It appears that we're getting pretty slow responses across all the Victorian layers. 

It takes the service a considerably long time to load (http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities).

**Comment by kring** [comment]
Yep, not something we can fix on our end.
