### ISSUE TITLE
National Map v2017-07-21 pre-release test - Observation - Feature label character style

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#550]
**Observation**

Layer: Western Australian Government/Department of Education/ Current Active Schools Semester 1 2014 - Public (DET-006)

- The feature label character style may need review and change (?) (see Slide 22)

![slide22](https://user-images.githubusercontent.com/22827786/28656069-1cd794e2-72e3-11e7-91e1-604260cf9449.JPG)

**Comment by ajbar7** [comment]
That's really an issue for the publisher - happy to send it on but I'm not sure that we'd convince them. 

@steve9164 happy for you to close this one.

**Comment by kring** [comment]
This is not something we can change.
