### ISSUE TITLE
National Map v2017-07-21 pre-release test - Displaying layers with multiple formats 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#551]
**Major Issue**

A good number of layers are now registered in the National Map catalogue that have more than one format (i.e. GeoJSON, KML and WMS). For a general user it could be confusing as to what format to choose - particularly when it is not described. The experience is not very friendly - rather very confusing:

For example try the following layer:
Local Government/Queensland/City of Ipswich/Contours - 1 metre - Ipswich City 2014
that has three different formats

Result:
- GeoJSON - hanged until removed (see Slides 23-24)
- KML - generated Chrome browser error 'Ah snap, Reload' (see Slide 25)
- WMS - loaded fine, as expected (see Slide 26)

Comment:
- Is something wrong with this layer?
- Whereas, 'Ipswich Library and Mobile Library Sites' that also has three formats worked fine!!

![slide23](https://user-images.githubusercontent.com/22827786/28656555-ee85b63e-72e5-11e7-998b-6d882bb5ee8b.JPG)

![slide24](https://user-images.githubusercontent.com/22827786/28656567-07a901f2-72e6-11e7-998d-c509e916fe12.JPG)

![slide25](https://user-images.githubusercontent.com/22827786/28656588-2df0fac2-72e6-11e7-85ca-ab3d5caaa981.JPG)

![slide26](https://user-images.githubusercontent.com/22827786/28656633-5bf1c596-72e6-11e7-8a7f-b5add6d21686.JPG)

![slide27](https://user-images.githubusercontent.com/22827786/28656634-6458d828-72e6-11e7-819d-cedac35840b7.JPG)

**Comment by ajbar7** [comment]
I tend to agree with this one but my understanding is that it can be a bit challenging where the data is being fetched from different catalogues? Perhaps this merits a bit of a cleanup of the Local Government section of the catalogue to be more selective. For example with LG data coming from data.gov.au only include WMS but for other be more permissive with formats as they don't all have spatial services.

@kring / @steve9164 happy to get your advice on this to see if there's anything smarter that can be done.

**Comment by AnaBelgun** [comment]
New issue here: https://github.com/TerriaJS/terriajs/issues/3005
