### ISSUE TITLE
National Map v2017-07-21 pre-release test - Displaying layers with multiple format (#551) - Another example

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#553]
v2017-07-21 pre-release test - Displaying layers with multiple format (#551) - Another example

- As I understood, National Map provides the following options to load a layer to the map:
(A) - Click on the layer name to display the description ONLY
(B) - The (+) button to add the layer to map
(C) - The 'Add to map' button to add the layer to map
I have noticed SOME layers (i.e. layers that have multiple formats) - attempts to load the layer to map when clicked on the layer name (A). Not sure if this is expected!

- For example:
Layer: Local Government/Tasmania/Glenorchy/Glenorchy City Council Building Footprints (KML)
When tried (A) option disabled (B) and (C) and hanged, posted 'Page Unresponsive' prompt followed by browsers 'Aw, Snap! Google Chrome ran out of memory ...' error.

SOME more instances of the above example have been noted.

Please investigate!!!

![slide5](https://user-images.githubusercontent.com/22827786/28699552-d1a03258-738d-11e7-9cc1-60bbffde238a.JPG)

![slide29](https://user-images.githubusercontent.com/22827786/28699572-f17428b4-738d-11e7-8749-80e4b85544a0.JPG)

![slide30](https://user-images.githubusercontent.com/22827786/28699578-f893e5f8-738d-11e7-8c2c-9b9bfa58706d.JPG)

**Comment by ajbar7** [comment]
@kring / @steve9164 is this because the layer is trying to load into the preview? Some of those KMLs could be quiet big and probably causing the browser to run out of memory?

As per https://github.com/TerriaJS/nationalmap/issues/551 - it's probably worthwhile preferring WMS only and only falling back to other formats if nothing else is available. The building footprint KML is around 100MB so probably pretty taxing for most browser to load in.

**Comment by steve9164** [comment]
I'm not exactly how the CKAN listings work, but I think it would be hard to detect that two different distributions that are different formats both show the same thing

**Comment by kring** [comment]
Loading when you preview an item is expected.  And we have other issues covering excluding non-WMS from data.gov.au.  So I'm closing this.
