### ISSUE TITLE
National Map v2017-07-21 pre-release test - ArcGIS Mapserver error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#555]
Layer: National Datasets/Infrastructure/Dam Walls

Generated 'ArcGIS Mapserver error'

see Slide 35 below

![slide35](https://user-images.githubusercontent.com/22827786/28703090-f589c3d4-73a4-11e7-8de4-5549ee6419f7.JPG)

**Comment by ajbar7** [comment]
@EhsanCanberra looks like GA changed the layer location can you confirm that the new layer to use is: http://services.ga.gov.au/site_7/rest/services/NM_Hydrology_and_Marine_Lines/MapServer?
