### ISSUE TITLE
National Map v2017-07-21 pre-release test - Catalogue group not available

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#556]
Catalogue group displaying 'Group is not available' error!

Group: Tasmanian Government/Wealth from Water

![slide36](https://user-images.githubusercontent.com/22827786/28703151-71999c74-73a5-11e7-9752-a2c31f4e2e55.JPG)

**Comment by ajbar7** [comment]
Looks like it was a temporary issue with their server. It's back.

![image](https://user-images.githubusercontent.com/7380633/29154954-c94dc72a-7ddb-11e7-8956-db50f3c4f8c7.png)

@steve9164 this issue can be closed.
