### ISSUE TITLE
GA dataset issues

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#561]
Attached is a list of datasets from Geoscience Australia that AREMI uses. Some of these have problems that need to be fixed.

[AREMI and NationalMap checks using GA Data - UPDATED 29JUNE2017.xlsx](https://github.com/TerriaJS/nationalmap/files/1224907/AREMI.and.NationalMap.checks.using.GA.Data.-.UPDATED.29JUNE2017.xlsx)

**Comment by EhsanCanberra** [comment]
Mats, could you please share with GA the app you have used to generate the report? We are trying to create a similar tool to verify the catalogue entries in National Map (difficult to do it manually for over 500 layers!). Thanks, Ehsan

**Comment by AnaBelgun** [comment]
Most services updated.
