### ISSUE TITLE
National Map v2017-08-15 pre-release test - Could not load JSON error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#564]
**Major**

Issues with 'Data.gov.au/ABS Geospatial Solutions/' layers (hangs system!)

- 1st layer - ASGS (2011 Edition) - Indigenous Structure - Indigenous Area (IARE) Boundaries (GeoJSON) - generated error

- 2nd layer - ASGS (2011 Edition) - Indigenous Structure - Indigenous Area (IARE) Boundaries (GeoJSON) - loaded ok

- 3rd layer - generated error then hanged and displayed the 'Aw snap, reload' message

![slide2](https://user-images.githubusercontent.com/22827786/29500777-fbfad210-8666-11e7-8615-7519c2c7f443.JPG)

![slide3](https://user-images.githubusercontent.com/22827786/29500782-04cabfea-8667-11e7-990e-a4b60c6dcb54.JPG)

![slide4](https://user-images.githubusercontent.com/22827786/29500799-16a041c2-8667-11e7-95e0-1e2c5f4ef2d7.JPG)

![slide5](https://user-images.githubusercontent.com/22827786/29500891-b2415850-8667-11e7-9fc5-05b9bf96ada2.JPG)

**Comment by kring** [comment]
The second data file is quite large - 82 megabytes - so the browser is running out of memory and crashing.  There's not a lot we can do about this, unfortunately, but I wrote TerriaJS/terriajs#2638 to consider at least warning the user before trying to load a large file that might crash the browser.  Closing this issue.
