### ISSUE TITLE
National Map v2017-08-15 pre-release test - Category group - no layer found

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#568]
**Major**

Category group - 'Data.gov.au/CMAR - CSIRO Marine and Atmospheric Research' - datasets can't be loaded

- The datasets listed in the group generated 'No layer found' error

See image below:

![slide12](https://user-images.githubusercontent.com/22827786/29503803-435642ea-867e-11e7-8724-8692d699091e.JPG)

**Comment by kring** [comment]
To fix this, we need to implement TerriaJS/terriajs#2630.
