### ISSUE TITLE
National Map v2017-08-15 pre-release test - Observation - Catalogue entry placement

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#572]
**Observation**

Category: Data.gov.au/Department of Health and Human Services

- The title of the three layers in the group refer to Tasmanian public health facilities
- Should these layers be moved under 'Tasmanian Government' category?

![slide16](https://user-images.githubusercontent.com/22827786/29504306-08334c9a-8682-11e7-9b11-3bd89f6ad3c9.JPG)

**Comment by kring** [comment]
The name of the Organization would need to be renamed on data.gov.au:
http://data.gov.au/organization/department-of-health-and-human-services

Not something we can fix in NationalMap.
