### ISSUE TITLE
National Map v2017-08-15 pre-release test - Observation - Catalogue category labels - 1

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#573]
**Observation**

Catalogue category labels under 'Data.gov.au' may need to specify their jurisdiction

- Department of Health and Human Services (for the Tasmanian Government)
- Department of Human Services (Australian Government)

![slide17](https://user-images.githubusercontent.com/22827786/29504551-ce1ed608-8683-11e7-9bb8-1742e8472dba.JPG)

**Comment by kring** [comment]
Organization names would need to change on data.gov.au, not something we can fix in NationalMap.
