### ISSUE TITLE
National Map v2017-08-15 pre-release test - Observation - Catalogue category labels - 2

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#574]
**Observation**

Catalogue category labels under 'Data.gov.au' 

- Department of the Environment and Energy (appears to load as expected)
- departmentofenvironment - generating 'No layer found' and 'Error accessing catalogue item' error

Similar titles (?)
One display the layers and the other generates 'No layer found' error

![slide19](https://user-images.githubusercontent.com/22827786/29505321-f6fb489a-8688-11e7-8f52-58fd657be461.JPG)

![slide20](https://user-images.githubusercontent.com/22827786/29505330-02c50bde-8689-11e7-8def-9141cfdb2524.JPG)

![slide21](https://user-images.githubusercontent.com/22827786/29505478-ef65ee40-8689-11e7-9244-1e74f859a40a.JPG)

**Comment by kring** [comment]
That odd organization comes directly from data.gov.au, not something we can fix in NationalMap.
http://data.gov.au/organization/departmentofenvironment
