### ISSUE TITLE
National Map v2017-08-15 pre-release test - Observation - Multiple catalogue entries

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#578]
**Observation**

Category: Local Government/Queensland/Gold Coast

- Multiple entries of same layer? 

see image below:

![slide25](https://user-images.githubusercontent.com/22827786/29506043-00a29994-868d-11e7-9d50-b9678194f259.JPG)

**Comment by kring** [comment]
It is a true representation of what's on data.gov.au:
http://www.data.gov.au/dataset/gold-coast-boat-ramps

There are three different KML/KMZ resources.
