### ISSUE TITLE
National Map v2017-08-15 pre-release test - Error loading data layer - 12 (GA Flow Grid) 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#584]
Layer: National Datasets/Elevation/Flow Grid Direction Image

- Generated 'An error occurred' error message - see image below:

![slide31](https://user-images.githubusercontent.com/22827786/29507046-d1910d66-8691-11e7-9a1c-af434f3e633c.JPG)

**Comment by kring** [comment]
It seems the URL is no longer valid: http://www.ga.gov.au/thredds/wms/national_grids/d8-9s.nc
Do you know an updated URL?  If not, I can remove it from the catalog.

**Comment by AnaBelgun** [comment]
It needs to be removed from the catalogue; they've decomissioned the service. I put it in the catalogue clean up issue, but forgot to remind you last week.

**Comment by AnaBelgun** [comment]
Decommissioned service removed.
