### ISSUE TITLE
National Map v2017-09-15 pre-release test - Zoom to Extent failure - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#590]
Major Issue:
Zoom to Extent fails after adding any '2016 Census' data layers.

Result:
Zoom to Extent inaccessible for the above layers.

Comment:
Workaround is to use the zoom reset button.

![slide1](https://user-images.githubusercontent.com/20634718/30571575-1fab0e38-9d2c-11e7-9600-5a253446f05f.JPG)

![slide2](https://user-images.githubusercontent.com/20634718/30571578-267e130e-9d2c-11e7-8794-18b158261e5e.JPG)

**Comment by kring** [comment]
Wrote a TerriaJS issue for this:
https://github.com/TerriaJS/terriajs/issues/2690
