### ISSUE TITLE
National Map v2017-09-15 pre-release test - No Region Recognised - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#591]
Major Issue:

- No Region Recognised Error
- All '2016 Census' layers

Result:
The above errors appears when selecting 'Australia' under Geography Level. After the error is presented the GUI element disappears from view.

Comment:
There is no workaround to this.

![slide3](https://user-images.githubusercontent.com/20634718/30571788-539712c2-9d2d-11e7-865e-48a9c32bbd67.JPG)

![slide4](https://user-images.githubusercontent.com/20634718/30571796-64ff252c-9d2d-11e7-9657-d4f896615dda.JPG)

**Comment by kring** [comment]
Create a TerriaJS issue for this: https://github.com/TerriaJS/terriajs/issues/2691
