### ISSUE TITLE
National Map v2017-09-15 pre-release test - Communications Broadband - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#592]
Major Issue:

- Request failure when accessing data layers that start with 'Broadband' under the Communications group

Result:
Unable to load the above layers.

Comment:
This is also occurring in the Production system.

![slide5](https://user-images.githubusercontent.com/20634718/30571929-1cc31c5e-9d2e-11e7-83cf-9defaf97eacc.JPG)

**Comment by kring** [comment]
I believe this was a problem with the Communications server.  I no longer see the problem.
