### ISSUE TITLE
National Map v2017-10-16 pre-release - Error loading data layer

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#600]
Layer: Complying Development Certificates

 - Generated error message - see image below:
![slide1](https://user-images.githubusercontent.com/20634718/31692914-932322ca-b3e7-11e7-8540-2c4a7403b40f.JPG)

**Comment by kring** [comment]
data.gov.au lists this as a GeoJSON file, but it's not valid GeoJSON:
http://apptracking.lakemac.com.au/modules/ApplicationMaster/openda.aspx?&1=lastweek&4a=434&5=T&format=json

Looks like a custom JSON structure, but definitely not GeoJSON.  Not something we can fix.
