### ISSUE TITLE
National Map v2017-10-16 pre-release - Error loading data layer

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#601]
Layer: ASGS (2011 Edition) - Indigenous Structure ....

 - Generated error message - see image below:
![slide2](https://user-images.githubusercontent.com/20634718/31692979-e8ff1eba-b3e7-11e7-8ba0-cf895563fcb4.JPG)

**Comment by kring** [comment]
Looks like the URL published on data.gov.au is invalid:
http://www.data.gov.au/dataset/asgs-2011-ireg/resource/518b200f-cb85-4fce-8d4c-311cc8fbeb25
And click URL at the top.  Not something we can fix.
