### ISSUE TITLE
National Map v2017-10-16 pre-release - Error no compatible resources found

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#603]
Layer: Unable to load data layer

 - Incomplete data layer definition ?
![slide4](https://user-images.githubusercontent.com/20634718/31693300-80a1395a-b3e9-11e7-966e-be3674c3baf5.JPG)

**Comment by kring** [comment]
Looks like an out-of-date snapshot of the SoE map.  I added a note to fix this to #615.
