### ISSUE TITLE
National Map v2017-10-16 pre-release - Error Energy Efficiency Concession Areas

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#604]
Layer: Unable to load data layer

 - Takes a long time before producing the error and appears to consume lots of RAM
![slide5](https://user-images.githubusercontent.com/20634718/31693531-d95913fa-b3ea-11e7-8613-6b4f7f464fed.JPG)

**Comment by kring** [comment]
I can't reproduce this one, it seems to load ok for me.  I even tried a couple of different browsers.  Perhaps a layer you had tried to load earlier caused problems?

**Comment by kring** [comment]
The layer I'm trying is `South Australian Government (BETA) -> Housing, land, planning and infrastructure -> Energy Efficiency Concession Areas`.
