### ISSUE TITLE
National Map v2017-10-16 pre-release - Observation No Group Assignment

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#606]
Observation only

 - See below screen capture
![slide7](https://user-images.githubusercontent.com/20634718/31693726-01ab7acc-b3ec-11e7-814d-ac735d7a562e.JPG)

**Comment by kring** [comment]
The VIC CKAN server has some datasets that are not in any group.  This is behaving as intended.
