### ISSUE TITLE
National Map v2017-10-16 pre-release - Error loading KML or KMZ

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#607]
Layer: Payment Condition Data

 - Unable to load data layer
![slide8](https://user-images.githubusercontent.com/20634718/31694070-e7e1676c-b3ed-11e7-8638-7a8172dc7530.JPG)

**Comment by kring** [comment]
Another huge KML file (over 400 megabytes).  Not much we can do other than warn the user.
