### ISSUE TITLE
National Map v2017-10-16 pre-release - Error Page Unresponsive

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#608]
Layer: Traffic Count Locations

 - Unable to load data layer
![slide9](https://user-images.githubusercontent.com/20634718/31694145-4c89d028-b3ee-11e7-8884-e9b706156f98.JPG)

**Comment by kring** [comment]
This is a very large KML file that breaks even Google Earth on my system.  Ideally we'd implement TerriaJS/terriajs#2638 so that the user's session isn't broken unexpectedly.
