### ISSUE TITLE
National Map v2017-10-16 pre-release - Observation No preview available

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#609]
Layer: Multiple layers affected

 - Unable to load preview
![slide10](https://user-images.githubusercontent.com/20634718/31694211-b453c6a0-b3ee-11e7-9cfa-b0e63afed9ea.JPG)

**Comment by kring** [comment]
The WA server does not support the web mercator (EPSG:3857) projection, which is required for the 2D map and the preview.  Not something we can reasonably fix.
