### ISSUE TITLE
National Map v2017-10-16 pre-release - Observation no group assignment

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#610]
Layer: Multiple layers affected

 - Not assigned a group name
![slide11](https://user-images.githubusercontent.com/20634718/31694251-ec7b5ffc-b3ee-11e7-8435-2e30b29e209b.JPG)

**Comment by kring** [comment]
data.gov.au has a Mosman organisation, but it has no datasets:
http://data.gov.au/organization/mosmanmunicipalcouncil
NationalMap is working as expected.
