### ISSUE TITLE
National Map v2017-10-16 pre-release - Error ArcGIS Mapserver Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#612]
Layer: Unable to load data layer(s)

 - Multiple affected. Possible corruption of metadata ?
![slide13](https://user-images.githubusercontent.com/20634718/31694386-b4ba09fa-b3ef-11e7-8641-4fd996ebb71b.JPG)

![slide14](https://user-images.githubusercontent.com/20634718/31694426-f8a9b606-b3ef-11e7-9e38-101a860314f3.JPG)

**Comment by kring** [comment]
We don't have any control over the ACT server.
