### ISSUE TITLE
NationalMap catalogue cleanup/curation

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#615]
This tickets is to address issues with data layers currently returning errors on NationalMap, due to reasons such as: decommissioning by custodian, change of service url/name etc. The ticket also addresses issues with duplication of data layers, wrong categorisation etc. 

- [x] remove Elevation - Flow Grid Direction Image (GA's THREDDS server decommissioned)

- [x] remove Framework - Waste management facilities (duplicate; already in Infrastructure where it makes more sense)

- [x] replace Radio Licenses - ACMA broken service with http://gis.aremi.data61.io/acma/wms 

- [x] Delete the Water Geofabric from Data Providers and move it under Surface Water, replacing the Geofabric layers there

**Comment by AnaBelgun** [comment]
@philipgrimmett please pick a section of the NatMap catalogue to have a look and check if the layers are working or data is duplicated etc. Depending on your pick, I'll deal with the remaining part of the catalogue.

**Comment by kring** [comment]
The Data Providers - > State of the Environment group looks to be a snapshot of the SoE map, and it's out of date.  See #603.  We should at least update the snapshot.

**Comment by RacingTadpole** [comment]
I've just noticed an SDMX-JSON item that needs a little improving -
DEATHS_AGESPECIFIC_REGISTRATIONYEAR
![image](https://user-images.githubusercontent.com/1757858/32591423-29ac5472-c573-11e7-86ca-534d85039d3d.png)
This has both "Total" and "All ages" under ages, and only the latter works, but the former is the default.
![image](https://user-images.githubusercontent.com/1757858/32591458-446c3782-c573-11e7-9319-4a431c7af2a7.png)
May also apply to some others.

**Comment by AnaBelgun** [comment]
We can close now @meh9
