### ISSUE TITLE
National Map v2017-10-31 pre-release test - Major - No layers found

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#618]
Catalogue Item: Data.gov.au/CMAR - CSIRO Marine and Atmospheric Research/all layers
Error: No layer found

![slide4](https://user-images.githubusercontent.com/22827786/32361712-1d0c48b4-c0b7-11e7-8328-1b5cff3ecd01.JPG)

**Comment by kring** [comment]
This is a symptom of TerriaJS/terriajs#2630.
