### ISSUE TITLE
National Map v2017-10-31 pre-release test - Observation - Missing ZtoE function?

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#622]
Datasets:
Calculating larval growth rates .. central Great Barrier Reef
Aspects of the life history .. Davies Reef, Great Barrier Reef

Missing 'Zoom to Extent' function?

![slide5](https://user-images.githubusercontent.com/22827786/32362500-f78d4898-c0bd-11e7-8c54-14b566c577cf.JPG)

**Comment by kring** [comment]
This is by design.  We now hide the button if "Zoom To" is not supported.  Previously the button would have been present but pressing it would have done nothing.
