### ISSUE TITLE
National Map v2017-11-09 pre-release test - Error loading data layer 1 (ACT Gov Topo)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#631]
Error loading Catalogue entry

- Australian Territory Government/Topographic/2004 1m Contours

![slide3](https://user-images.githubusercontent.com/22827786/32645139-c28cfc02-c639-11e7-8efe-9628eb379909.JPG)

**Comment by AnaBelgun** [comment]
Followed up with custodian (ACTMapi team). Will close and re-open if necessary.
