### ISSUE TITLE
Update Postal Areas to 2016 data

### ISSUE THREAD

**Issue by axman6** [TerriaJS/nationalmap#634]
Looks like the postal areas in under National Datasets -> National Boundaries is using the 2011 data, not the 2016 data. The region mapping server defaults to 2016 for `postcode` columns, which confused us when we were comparing postcodes to some data we have at postcode level.

**Comment by AnaBelgun** [comment]
They are here as csv and Esri shape files: http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.003July%202016?OpenDocument

**Comment by AnaBelgun** [comment]
@steve9164 is it hard to update them in our region mapping server?

**Comment by steve9164** [comment]
The data in National Boundaries are layers served from geoserver. It shouldn't be too hard to add 2016 postcodes to geoserver.
