### ISSUE TITLE
Add CLUM data service

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#635]
Add the new CLUM data service (which will run temporarily, until Data.gov.au can provide it), under National Datasets - Land - Agriculture & Mining

The service is now available at the following link:

http://www.asris.csiro.au/arcgis/rest/services/abares

You can view it with this endpoint:
http://www.asris.csiro.au/arcgis/rest/services/abares/clum_50m_current/MapServer?f=jsapi

and getcapabilities from the wms here:
http://www.asris.csiro.au/arcgis/services/abares/clum_50m_current/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by steve9164** [comment]
Waiting on TerriaJS/northernaustralia#48 to be approved, then I'll PR this into `NationalMap-Catalog`.

**Comment by AnaBelgun** [comment]
Updated Url: http://www.agriculture.gov.au/abares/data/clum-50m-current.

**Comment by AnaBelgun** [comment]
@stevage can we action this one for this month release? please
