### ISSUE TITLE
National Map v2017-11-21b pre-release test - Agricultural exposure layer - Slow response

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#637]
**Observation**

- Many layers in this release were found to load very slowly, some hanged the system! (A few listed under issues)

![slide1](https://user-images.githubusercontent.com/22827786/33190002-66637596-d0fc-11e7-9b65-48c96cc3f6fc.JPG)

**Comment by gordjw** [comment]
Seems to be occurring on the current release as well

**Comment by AnaBelgun** [comment]
Re-tested and works fine (fast). 
![image](https://user-images.githubusercontent.com/18452161/41759820-a36004d2-7633-11e8-872f-f6bbe875a645.png)
