### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading data.gov.au/Airborne Research Australia

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#638]
Error loading Catalogue entry

- Data.gov.au/Airborne Research Australia (ARA)/WAMSI Kimberley aerial photo data - 22nd September 2008
- Error loading KML or KMZ

![slide2](https://user-images.githubusercontent.com/22827786/33190068-133e6bae-d0fd-11e7-9c12-c1ad44876f78.JPG)

**Comment by AnaBelgun** [comment]
Followed up with data.gov.au and custodian.
