### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading data.gov.au/Australian Antarctic Division

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#639]
Error loading Catalogue entry

- Data.gov.au/Australian Antarctic Division/*all layers*
- Error (An error occurred)

![slide3](https://user-images.githubusercontent.com/22827786/33190136-96c802aa-d0fd-11e7-964d-d59739c7bc8b.JPG)

**Comment by AnaBelgun** [comment]
Already dealt with; Followed up with data.gov.au and the custodian.
