### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading data.gov.au/Australian taxation office

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#640]
Error loading Catalogue entry

- Data.gov.au/Australian Taxation Office/**all layers**
- Error (System hanged, needed to restart)

![slide4](https://user-images.githubusercontent.com/22827786/33190201-277cf508-d0fe-11e7-9fae-7d94f211c7b6.JPG)

![slide5](https://user-images.githubusercontent.com/22827786/33190223-7e5d00ca-d0fe-11e7-88d2-f9f0da2047f8.JPG)

![slide6](https://user-images.githubusercontent.com/22827786/33190244-d03f6f68-d0fe-11e7-962e-d0f196e9bcdf.JPG)

![slide7](https://user-images.githubusercontent.com/22827786/33190248-d87cf47a-d0fe-11e7-9138-2cfcb329b60b.JPG)

![slide8](https://user-images.githubusercontent.com/22827786/33190250-df2525e0-d0fe-11e7-8b7a-8bebe577c44c.JPG)

**Comment by AnaBelgun** [comment]
Re-tested: 
- the message about csv-geo-au still showing but not affecting the data viz (still working) 
- tested the KML version and was very very slow but no error message
