### ISSUE TITLE
National Map v2017-11-21b pre-release test - Data.gov.au/testing layer

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#643]
**Observation**

- The Catalogue sub-heading appears to be a dummy to assist developer to add new items.
- Should this entry be in 'Production'?

![slide11](https://user-images.githubusercontent.com/22827786/33190437-d2e5463c-d100-11e7-9855-f51c6c6b495b.JPG)

**Comment by AnaBelgun** [comment]
Deleted from the catalogue.
