### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading data.gov.au/Curtin Uni

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#645]
Error loading Catalogue entry

- Data.gov.au/Department of Environment and Agriculture, Curtin University/WAMSI Node 4.2.2a ....Fish assemblages
- Error (Error loading KML or KMZ)

![slide13](https://user-images.githubusercontent.com/22827786/33190622-bb662dda-d102-11e7-938e-0ae37fb97b3b.JPG)

**Comment by AnaBelgun** [comment]
Followed up with the Curtin Uni and data.gov.au to check if issues are at their end. 
Will close and reopen if we need to fix anything.
