### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading data.gov.au/DSS payments

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#646]
Error loading Catalogue entry

- Data.gov.au/Department of Social Services/DSS Payments by 2014 Local Government Area
- Error (Unable to load CSV file)

![slide14](https://user-images.githubusercontent.com/22827786/33190666-45d39976-d103-11e7-8c45-79a9a1e5c716.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and working now

![image](https://user-images.githubusercontent.com/18452161/41758816-6a37099e-762e-11e8-9af7-4c68febc1001.png)
