### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading ABS Statistical boundaries/ADD

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#647]
Error loading Catalogue entry

- Data Providers/ABS Statistical Boundaries/2016/Australian drainage divisions (ADD)
- Error (System hanged, needed to restart)

![slide15](https://user-images.githubusercontent.com/22827786/33190768-9d62212a-d104-11e7-90e4-6e168f2bdd89.JPG)

![slide16](https://user-images.githubusercontent.com/22827786/33190771-a52a3c9e-d104-11e7-9373-591b58b0ab75.JPG)

![slide17](https://user-images.githubusercontent.com/22827786/33190773-b0450690-d104-11e7-8558-312b6ab1622f.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and working now (fast response) 

![image](https://user-images.githubusercontent.com/18452161/41758768-25bba5c2-762e-11e8-9fe0-cbeed40f49ec.png)
