### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading GA Marine Seismic surveys

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#648]
Error loading Catalogue entry

- Data Providers/Geoscience Australia/Marine Seismic Surveys Shape files and KML files
- Error (Error loading KML or KMZ)

![slide18](https://user-images.githubusercontent.com/22827786/33190805-17987502-d105-11e7-8ef0-85a9f7dbb85f.JPG)

**Comment by AnaBelgun** [comment]
Followed up with GA
https://github.com/TerriaJS/nationalmap/issues/741
