### ISSUE TITLE
Clarify with BoM and curate Geofabric data on NationalMap

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#649]
Error loading Catalogue entry

- Data Providers/Water (Bureau of Meteorology Geofabric)/(All) Hydrology Reporting Catchments
- Error (Error accessing catalogue item)

![slide19](https://user-images.githubusercontent.com/22827786/33190838-a5dd1520-d105-11e7-9dab-f8df2fc65113.JPG)

**Comment by AnaBelgun** [comment]
Currently there are 2 sections on NatMap catalogue which include Geofabric with old and new services links. They need to clarified and merged into one section, or two sections if necessary but with the same data.

**Comment by AnaBelgun** [comment]
![image](https://user-images.githubusercontent.com/18452161/39346375-2b1e35b2-4a31-11e8-95da-62f32e5dacef.png)

**Comment by AnaBelgun** [comment]
Does not exist in the catalogue under Data Providers - Water
