### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading SA Gov / Adelaide Metro 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#650]
Error loading Catalogue entry

- South Australian Government (BETA)/Adelaide Metro Real-Time Passenger Information
- Error (Could not load JSON)

![slide20](https://user-images.githubusercontent.com/22827786/33190858-1539212a-d106-11e7-9b9d-003f58d5989b.JPG)

**Comment by AnaBelgun** [comment]
Emailed SA Gov team. 
Will close for now and re-open if there's anything at our end.
