### ISSUE TITLE
National Map v2017-11-21b pre-release test - Error loading VIC Gov / Seismic survey lines

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#651]
Error loading Catalogue entry

- Victorian Government/Environment/Seismic Survey Lines - for Petroleum Industry Exploration
- Error (Error accessing catalogue item)

![slide21](https://user-images.githubusercontent.com/22827786/33190902-9f71a6c8-d106-11e7-96af-93ab29de41b7.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and working now

![image](https://user-images.githubusercontent.com/18452161/41758637-659d7036-762d-11e8-8d93-3fd66a362426.png)
