### ISSUE TITLE
National Map v2017-11-21b pre-release test - 'Map View' function - Elevation display

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#652]
It appeared that the **Map View** function has an issue that need investigation

- The Elevation display at the bottom of the map should only appear when the Map View is set to '3D Terrain'
- During the test, switching between the three 'Map View' options, moving backward '2D -> 3D Smooth -> 3D Terrain' or '2D -> 3D Terrain' the above default setting changed - the '3D Terrain' stopped displaying the Elevation reading.

- This occurred when the base map was set to 'Natural Earth II'

- Two screen captures attached - one from pre-release and the other from Prod National Map v2017-11-13

- Please investigate

![slide22](https://user-images.githubusercontent.com/22827786/33191044-ca761910-d108-11e7-8cd0-e1d07d994938.JPG)

![slide23](https://user-images.githubusercontent.com/22827786/33191052-dadce9e6-d108-11e7-83fe-014e91645422.JPG)

![slide24](https://user-images.githubusercontent.com/22827786/33191100-7ca59bc4-d109-11e7-87ee-a9031f025cfe.JPG)

**Comment by AnaBelgun** [comment]
Issue here: https://github.com/TerriaJS/terriajs/issues/2952
