### ISSUE TITLE
National Map v2017-11-21b pre-release test - Base Map location search issue

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#653]
Map View base map - 'Natural Earth II' - issue:

- It appeared that the above base map is not performing as expected

Test;
- Set Map View to '3D Terrain' and base map to 'Natural Earth II' 
- In location Search enter 'Canberra'
- Click on the returned results - the first, under Location heading -> 'Canberra, ACT'
- Generated error (Error accessing base map)

![slide25](https://user-images.githubusercontent.com/22827786/33191191-a3f0bdac-d10a-11e7-941a-d6e1c21d14f6.JPG)

![slide26](https://user-images.githubusercontent.com/22827786/33191196-ab1b7248-d10a-11e7-8f55-df1951475326.JPG)

![slide27](https://user-images.githubusercontent.com/22827786/33191198-b4fc81ee-d10a-11e7-9be7-25424865b4db.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and no error message

![image](https://user-images.githubusercontent.com/18452161/41758433-f7df5588-762b-11e8-8770-ab6a74779e27.png)
