### ISSUE TITLE
Error loading CAMRIS data from data.gov.au

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#658]
I am trying to get access to this database, located at https://data.gov.au/dataset/australian-estuaries-database-camris but I get an error from many of the links on the page. Can this be fixed and can you please let me know when it has been done?

Kind regards

Katrina Szetey

**Comment by kring** [comment]
This is a CORS error.  The WMS server, `acef.tern.org.au`, isn't in our proxy whitelist and it doesn't support CORS.  I'll open a PR to add it to the whitelist.
