### ISSUE TITLE
National Map v2018-01-18 pre-release test - Error in loading KML or KMZ files

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#665]
We have tested Several links that use .kml files for loading relevant data on to the national maps. 
An error message appears stating an error has occurred while loading a Kml or KMZ file 
We also observed that the Metadata links are up and running. This would indicate that the data is available from the data providers 
We see this error in 
Data Providers -> Geoscience Australia -> Air Traffic Services
Data Providers -> Geoscience Australia -> Electricity Transmission Lines
Data Providers -> Geoscience Australia -> Electricity Transmission Sub Stations
Data Providers -> Geoscience Australia -> Marine Seismic Surveys shape files and Kml Files
Data Providers -> Geoscience Australia -> Costal Maritime Navigation Lights Database
Data Providers -> Geoscience Australia -> National Consular Missions Database
Data Providers -> Geoscience Australia -> National Onshore Gas Pipelines Database
Data Providers -> Geoscience Australia -> National Onshore Oil Pipelines Database
Data Providers -> Geoscience Australia -> Power Stations
Data Providers -> Geoscience Australia -> Waste Management Facilities (KML)
Coral Reef Studies ARC Center of excellence james cook university -> Torres Strait Dugong distribution and relative density - Spatial model of aerial surveys from 1987 - 2011 (NERP TE 2.1, JCU)
Below is a screenshot showing a sample of the error: 
![image002](https://user-images.githubusercontent.com/35437484/35130760-7425df18-fcba-11e7-9639-397da3f5b8f3.jpg)

**Comment by kring** [comment]
This was previously reported in #623.  It is not something we can fix in NationalMap, but it is something that Geoscience Australia can fix. See the linked issue for details.
