### ISSUE TITLE
National Map v2018-01-18 pre-release test - Duplicate links appearing in the add data window

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#666]
During testing we observed that links with the same description appears twice in same folder. 

One example is 
Data Providers -> Geoscience Australia -> Waste Management Facilities (KML)
The above link appears 2 times in the list. Their Data url is the same but the KML or KMZ url is different.

**Comment by kring** [comment]
This is because the dataset on data.gov.au (https://data.gov.au/dataset/waste-management-facilities) has two different KML/KMZ resources.  GA should consider removing one of them.
