### ISSUE TITLE
National Map v2018-01-18 pre-release test - ARCGis components not opening in the maps 

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#667]
ArcGIS Components are not opening in the maps for both 2D and 3D 

We have tested for the following components 
ACT Reserves
Dog Exercise Areas
Threatened Grasslands

Screenshot given below:
![image010](https://user-images.githubusercontent.com/35437484/35131419-ffddacd6-fcbd-11e7-8f40-7a0621a8fefd.jpg)

**Comment by kring** [comment]
These layers are all under ACT Government, and in all cases the layer has been removed from the server (for unknown reasons).  I'll remove it from the NationalMap catalog, and look into the possibility of configuring the ACT catalog so that the list of layers is queried from the server instead of hard-coded into our catalog.

**Comment by jimmyjamesga** [comment]
I had tried accessing other arcgis sources but they all returned errors. 
Below is another example: 
Depth of Regolith 
![arcgis_errors](https://user-images.githubusercontent.com/35437484/35203566-e3643860-ff7c-11e7-8eb3-5c8a477e64f6.jpg)

These worked in the previous release. The link returns a http 200 response.

**Comment by kring** [comment]
ok I'll take a look at that one too.

**Comment by kring** [comment]
Depth of Regolith is working ok for me.  BUT it did fail when I first tried to use it.  It appears that the server was generating errors and not including CORS headers with the error responses, so NationalMap can't even look at the error (hence the generic "request has failed" error).  But now that it's warmed up it's working ok. 

I can't see any general problem with ArcGIS services. There are many ArcGIS Mapservers in the catalog working just fine, such as all the ones in National Datasets -> Infrastructure.
