### ISSUE TITLE
National Map v2018-01-18 pre-release test - Issues in loading data as region names are not recognized 

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#668]
While trying to load data for some links an error appeared stating that region names were not recognised. 

one example of the issue is:
Australian Taxation Office -> Taxation Statistics 2012-13 

![image004](https://user-images.githubusercontent.com/35437484/35131703-983db218-fcbf-11e7-9e52-8c82784499af.jpg)

**Comment by kring** [comment]
The story here is that the CSV file has a column named "POA". POA is interpreted as "the latest ABS POA regions" or (currently) the 2016 version.  The 2016 version has some differences from the 2011 version such that a few postcodes are apparently missing, plus there is of course no region associated with the regionless postcodes. The version of the dataset in National Datasets -> Social and Economic -> Taxation Statistics accounts for all of this an works correctly, but the one in the data.gov.au -> Australian Taxation Office group is a best effort based on the information available from data.gov.au and the dataset itself.  So nothing to fix here as far as I can see.
