### ISSUE TITLE
National Map v2018-01-18 pre-release test - IMOS SOOP Sea Surface Temperature Data  Report fails while loading data

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#670]
The below link gives an error stating that the report has failed

CSIRO Oceans and atmosphere – Hobart -> IMOS SOOP Sea Surface Temperature Data collected on the Merchant Vessel Sea Flyte (Rottnest Island Ferry)

Screenshot below
![image006](https://user-images.githubusercontent.com/35437484/35132028-20e7ec04-fcc1-11e7-9b06-84729bcd3613.jpg)

**Comment by kring** [comment]
The request to the server is not responding within 20 seconds and timing out.  Not something we can fix in NationalMap.
