### ISSUE TITLE
National Map v2018-01-18 pre-release test - Flow Grid direction image returns a 404 - Page not found error

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#671]
The Flow Grid direction image returns a 404 error. The Data source link also returns a page not found error as well. 

Screenshot below 
![image008](https://user-images.githubusercontent.com/35437484/35132309-7a20b408-fcc2-11e7-8ea1-a82b55ec09dd.jpg)

**Comment by AnaBelgun** [comment]
yes, this one needs to be removed, as per https://github.com/TerriaJS/nationalmap/issues/615 
We just missed it in this release.
