### ISSUE TITLE
National Map v2018-01-18 pre-release test - Blank folders in the Add Data window

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#672]
Searching "Australian Bureau of statistics" gives 2 folder results. One of them is a blank folder which throws an error
Screenshot below

![image009](https://user-images.githubusercontent.com/35437484/35132436-38397ede-fcc3-11e7-89be-407da9c0e354.jpg)

Searching for "Placename points " also returns an empty folder but the error is different 

Screenshot below
![image011](https://user-images.githubusercontent.com/35437484/35132494-803fd6b0-fcc3-11e7-8f0e-0bcb0c93c022.jpg)

**Comment by jimmyjamesga** [comment]
We also See this with Rockhampton  points 
![image012](https://user-images.githubusercontent.com/35437484/35132617-f8c7c412-fcc3-11e7-9e21-55596207d4b0.jpg)

**Comment by jimmyjamesga** [comment]
My Description for Point 3 was not clear. Apologies, explaination Below: 

the search String I used was "Rockhampton". 2 Entries came up. 
One was Rockhampron Province which works fine. The second result is a folder Rockhampton that returns the error message.

**Comment by AnaBelgun** [comment]
I didn't get the second folder at all; what is the name of the folder in the catalogue?

**Comment by jimmyjamesga** [comment]
![rockhampton_errors](https://user-images.githubusercontent.com/35437484/35203665-75f57522-ff7d-11e7-8532-935bc75ff033.jpg)

Attaching a clearer screenshot. 
The folder is rockhampton. I am able to see this in both http://preprod.nationalmap.gov.au/ and https://nationalmap.gov.au/

**Comment by kring** [comment]
Rockhampton used to have a CKAN server at localdat.net.au, but it doesn't exist anymore, and I can't find a replacement with a quick Google.  I'll remove it.

**Comment by kring** [comment]
re: Australian Bureau of statistics, this is intentional and exists in the main catalog as well. We used to have a bunch of census data in that group.  When we moved it, we kept the old group with a message telling the user where they can now find the data.

**Comment by kring** [comment]
re: Placename points, the server appears to be down/broken: http://services.thelist.tas.gov.au/arcgis/rest/services/Public/PlacenamePoints/MapServer
I'll remove it from the catalog.
