### ISSUE TITLE
National Map v2018-01-18 pre-release test - Filtering for the Country of birth Data set does not work in some cases

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#673]
Filtering for the Country of birth Data set does not work in some cases. 

Steps to reproduce 
In national maps Click 'Add data' 
Search Country of birth 
Select Country Of Birth ->By Sex -> Over time -> By Local Government Area
Open the filter criteria 'Country of birth person' and select 2 countries. 
Expected: 
Data for the 2 countries should be displayed 
Actual:
No Data gets displayed and the selection becomes unresponsive.

**Comment by AnaBelgun** [comment]
This is indeed slow but it does return results for all searches by country of birth, by sex, by LGA, select countries.

**Comment by kring** [comment]
Actually it doesn't seem to matter how quickly I click that second country, it breaks pretty reliably.

**Comment by kring** [comment]
I've written a TerriaJS issue for this (linked above).
