### ISSUE TITLE
National Map v2018-01-18 pre-release test - National maps page fails due to memory issues 

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#675]
While testing the National maps application in Chrome I get the below issue intermittently. 
This issue resolves itself once you refresh the page 
![image015](https://user-images.githubusercontent.com/35437484/35206249-72788daa-ff8f-11e7-97f0-cbab86189717.jpg)

This issue appears most frequently while using the Search functionality in the 'add data' page extensively and adding a few data sets to the page.

**Comment by kring** [comment]
This can unfortunately happen when attempting to load very large KML and GeoJSON files and has been reported a few times. A possible solution is captured in TerriaJS/terriajs#2638.
