### ISSUE TITLE
National Map v2018-02-15b pre-release test - 'Split Screen' doesn't turn off when used in workbench

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#686]
**Observation - 'Split Screen' function has a bug?**

Two buttons to toggle 'Split Screen' function - one as a tab on the left panel (Slide 1) and one inside the Map window along the right edge as a button.

The left panel tab:
- when clicked splits the screen and creates a new copy of the layer below (Slide 1) - this repeats as many times as the tab is clicked (expected the second click would remove the screen split as it happens for the button inside the Map window)
- Repeated click creates a copy of the layer with a '(copy)' text appended to the title (Slide 2)
- Tried to click the right hand side button to remove the split - it did nothing (Slide 3)

The right hand side 'Split Screen' button works as expected.

![slide1](https://user-images.githubusercontent.com/22827786/36463954-f7988d22-16c4-11e8-9a45-689613de4f97.JPG)

![slide2](https://user-images.githubusercontent.com/22827786/36463959-ffb54252-16c4-11e8-9ab6-20465f545024.JPG)

![slide3](https://user-images.githubusercontent.com/22827786/36463965-097179b4-16c5-11e8-83fb-860a4b3c35b5.JPG)

**Comment by AnaBelgun** [comment]
Will close this here. Issue in terriajs repo: https://github.com/TerriaJS/terriajs/issues/3004
