### ISSUE TITLE
National Map v2018-02-15b pre-release test - GA - Flow Grid - error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#687]
Error opening Catalogue item

**Layer: National Datasets/Elevation/Flow Grid Direction Image**

![slide4](https://user-images.githubusercontent.com/22827786/36464092-bb40294c-16c5-11e8-9618-9f5716c4f753.JPG)

**Comment by AnaBelgun** [comment]
Layer decommissioned and removed.
