### ISSUE TITLE
National Map v2018-02-15b pre-release test - Error loading eAtlas services - Coral Reef studies

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#688]
Error loading KML or KMZ

Layer: Data.gov.au/Coral Reef Studies ARC Centre of Excellence, James Cook University

![slide5](https://user-images.githubusercontent.com/22827786/36464145-11dba9ca-16c6-11e8-82a5-a4e2c35d98c1.JPG)

**Comment by AnaBelgun** [comment]
To check first in data.gov.au
It looks like this might need to be updated by the publisher. It might have an WMS available: http://eatlas.org.au/data/uuid/71127e4d-9f14-4c57-9845-1dce0b541d8d;jsessionid=F22DC17A6C696227D4CD059C5CC5B4AC

Will close and reopen if we need to update the service at our end. For now issue is sent to dga.
