### ISSUE TITLE
National Map v2018-02-15b pre-release test - Difficulty loading Catalogue item

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#689]
Difficulty loading Catalogue item

**Extremely slow – hangs system. Requires restart**

Layer: National Datasets/Communications/Telecommunications in New Developments

![slide6](https://user-images.githubusercontent.com/22827786/36464217-711b8a2c-16c6-11e8-831e-56f0a6fa0809.JPG)

**Comment by AnaBelgun** [comment]
yes, still no working. 
It should be considered to remove it completely from catalogue.
