### ISSUE TITLE
National Map v2018-02-15b pre-release test -'zoom to extent' error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#690]
Observation – Zoom to extent set to Indian Ocean

Layer: Data.gov.au/Climate Features Tasmania – Scenarios A2 and B1

![slide7](https://user-images.githubusercontent.com/22827786/36464250-b4e87dbe-16c6-11e8-89b0-3e91bfe160cb.JPG)

**Comment by AnaBelgun** [comment]
Underlying data https://data.gov.au/dataset/climate-futures-tasmania-scenarios-a2-and-b1
Tested again and zoom to extent doesn't seem to work as expected. 
@kring would you please check

**Comment by rowanwins** [comment]
Layer no longer present in catalog
