### ISSUE TITLE
National Map v2018-02-15b pre-release test - Error accessing Catalogue item

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#691]
**Error accessing Catalogue item**

Layer: Data Providers/State of the Environment 2016/Land Map/LAN1a Observed major vegetation subgroups, from Australia’s NVIS database

![slide8](https://user-images.githubusercontent.com/22827786/36464297-f71dbd2a-16c6-11e8-84fe-a45c426d8b07.JPG)

**Comment by AnaBelgun** [comment]
working now
![image](https://user-images.githubusercontent.com/18452161/41755644-b5366b00-761b-11e8-8b7e-16dda478b257.png)
