### ISSUE TITLE
National Map v2018-02-15b pre-release test - Dept of Env - Biodiversity map

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#692]
**Error accessing Catalogue item**

Layer: Data Providers/State of the Environment 2016/Biodiversity Map Map/BIO1 Global biodiversity hotspots and natural value World Heritage Areas in Australia

![slide9](https://user-images.githubusercontent.com/22827786/36464394-80d63434-16c7-11e8-8ef5-03967c379cbe.JPG)

**Comment by AnaBelgun** [comment]
Working now. 

![image](https://user-images.githubusercontent.com/18452161/41755585-7755ddac-761b-11e8-829b-88cb2a1eefe3.png)
