### ISSUE TITLE
Add Satellite Imagery data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#714]
Following from the work on the TerriaCube project https://github.com/TerriaJS/terria-cube
 NCI and GA have produced 18 layers of satellite imagery data, which can go on NationalMap. DTA has been advised and approved the integration. 

The catalogue structure agreed with the project partners is: 

- [x] tidal layers - in a new subgroup, something like "National Datasets -> Surface Water and Marine -> Tidal" 
DEA High Tide Composite 25m v2.0 false colour
DEA High Tide Composite 25m v2.0 true colour
DEA Low Tide Composite 25m v2.0 false colour
DEA Low Tide Composite 25m v2.0 true colour
DEA Intertidal Extents Model Confidence Layer 25m v2.0
DEA Intertidal Extents Model Relative Layer 25m v2.0

- [x] These imagery layers will go in a new "National Datasets -> Satellite Imagery" group:
 
DEA Landsat 5 terrain corrected surface reflectance false colour
DEA Landsat 5 terrain corrected surface reflectance true colour
DEA Landsat 7 terrain corrected surface reflectance false colour
DEA Landsat 7 terrain corrected surface reflectance true colour
DEA Landsat 8 terrain corrected surface reflectance false colour
DEA Landsat 8 terrain corrected surface reflectance true colour

- [x] 18 layers will go into another new group "Data Providers -> Digital Earth Australia",
 
DEA High Tide Composite 25m v2.0 false colour
DEA High Tide Composite 25m v2.0 true colour
DEA Low Tide Composite 25m v2.0 false colour
DEA Low Tide Composite 25m v2.0 true colour
DEA Intertidal Extents Model Confidence Layer 25m v2.0
DEA Intertidal Extents Model Relative Layer 25m v2.0
DEA Landsat 5 terrain corrected surface reflectance false colour
DEA Landsat 5 terrain corrected surface reflectance true colour
DEA Landsat 7 terrain corrected surface reflectance false colour
DEA Landsat 7 terrain corrected surface reflectance true colour
DEA Landsat 8 terrain corrected surface reflectance false colour
DEA Landsat 8 terrain corrected surface reflectance true colour
DEA Landsat 5 surface reflectance false colour
DEA Landsat 5 surface reflectance true colour
DEA Landsat 7 surface reflectance false colour
DEA Landsat 7 surface reflectance true colour
DEA Landsat 8 surface reflectance false colour
DEA Landsat 8 surface reflectance true colour
 
Blurb to go on the Satellite Imagery and Data providers pages: 

The publication of the Digital Earth Australia (DEA) Landsat data on NationalMap is the result of the 12 month collaborative project “TerriaCube” between the National Computation Infrastructure (NCI), Geoscience Australia, Department of the Environment and Energy (DoEE) and CSIRO Land & Water and Data61 teams. 
Each stakeholder contribution was essential for the project’s success: the NCI developed the data services; Geoscience Australia provided the data; Department of Environment and CSIRO Land and Water, provided insights and the user stories; and CSIRO Data61 provided the software development of terriaJS. 
The project aimed to enable access to the DEA satellite imagery data managed by the NCI on NationalMap; and built functionalities in terriaJS to allow users to easily interact with the data. The project results were twofold: 
1) users have now access to terrain corrected surface reflectance from Landsat 5, 7 and 8 presented as true colour and false colour composites and 
2) all applications using the open source terriaJS have the “screen splitter” and “date picker” functionalities developed, allowing users to make comparisons of imagery for different points in time.

Logos to go on the same pages: https://drive.google.com/drive/folders/1xN5Uje50A5M61v9luFWhwmPoB_AruM0H

**Comment by meh9** [comment]
Added: https://github.com/TerriaJS/NationalMap-Catalog/pull/75
