### ISSUE TITLE
National Map v2018-03-15 pre-release test - load error for various datasets 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#715]
**The following layers [link] failed to load:**

- Radio Licenses - ACMA [http://geo-prototype1.aremi.d61.io/acma/wms]
- Primary Health Networks [null]
- Flow Grid Direction Image [http://www.ga.gov.au/thredds/wms/national_grids/d8-9s.nc]
- Census districts (CD) [http://censusdata.abs.gov.au/arcgis/rest/services/2001_CD/MapServer]
- Commonwealth Electoral Districts (CED) [http://censusdata.abs.gov.au/arcgis/rest/services/2001_CED/MapServer]

**Comment by kring** [comment]
> Radio Licenses - ACMA [http://geo-prototype1.aremi.d61.io/acma/wms]

Fixed! (will roll out the catalog update shortly).

> Primary Health Networks [null]

This one seems to be working ok for me.

> Census districts (CD) [http://censusdata.abs.gov.au/arcgis/rest/services/2001_CD/MapServer]

The ABS server seems to intermittently return an error for this URL. If I just keep hitting refresh, it flips between "Sorry! The page you were looking for could not be found" and a valid ArcGIS metadata page. We'll need to report the problem to ABS.

> Commonwealth Electoral Districts (CED) [http://censusdata.abs.gov.au/arcgis/rest/services/2001_CED/MapServer]

Same as above.

**Comment by AnaBelgun** [comment]
@kring I think we need to remove the Flow Grid completely: https://github.com/TerriaJS/nationalmap/issues/615

**Comment by AnaBelgun** [comment]
Most of them fixed.
