### ISSUE TITLE
National Map v2018-03-15 pre-release test - Data load error 2

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#716]
**Error: Error accessing catalogue item**
Layer: National Data Sets/Social & Economic/Census/Family/Family Blending/2016 Census/By Local Government Area

![slide2](https://user-images.githubusercontent.com/22827786/37690502-2d180e3e-2ca3-11e8-8576-3e7bed49af2c.JPG)

**Comment by kring** [comment]
This one is working for me. Maybe the ABS service was down briefly?
