### ISSUE TITLE
National Map v2018-03-15 pre-release test - Observation - Layer generates error after loading correctly!!

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#717]
**Observation**

Layer: National Datasets/Land/Agriculture and Mining/Agricultural Exposure

Renders correctly then after sometime (about 5 minutes) unexpectedly generates the 'Error accessing the catalogue item' error!!

![slide3](https://user-images.githubusercontent.com/22827786/37690624-0eac26c8-2ca4-11e8-8dc5-182b8fdc0dc7.JPG)

**Comment by kring** [comment]
504 indicates the server timed out and is not something we can fix in NationalMap.
