### ISSUE TITLE
Look into ABS commute distance map

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/nationalmap#719]
Apparently ABS has a commute distance map that they’ve produced (I think from census data). Check whether this is available alongside the other datasets and add it to the catalog.

**Comment by QuadTog** [comment]
Hey Ana,

We'd love to have this data on Data.gov.au! But until then you can find the tables used for creating it at:
   

-  https://guest.censusdata.abs.gov.au/webapi/jsf/dataCatalogueExplorer.xhtml

**Navigate to:** _Catalogue -> 2016 Census of Population and Housing -> 2016 Census of Population and Housing - TableBuilder Basic -> 2016 Census - Employment, Income and Education_ 
**Select:** _2016 Census Industry of Employment by Occupation_ and **Open Table.**
**Select:** _Distance to Work_

**Enjoy!**

Kind Regards,
Adam Rice
**[DTA](https://www.dta.gov.au/) - CTO Group**
**Geospatial Systems Engineer || [Data.gov.au](Data.gov.au) Custodian**

**Comment by RacingTadpole** [comment]
Cool! 
FYI, NationalMap can show any ABS data published in SDMX-JSON - the current list is given in the dropdown menu at http://stat.data.abs.gov.au/sdmx-json/ .  But for various reasons we've had to hardcode the dataset ids in the catalog - which means if new datasets are released, we need to manually add them to the catalog.
I don't see the distance to work on that drop-down list (yet?).
