### ISSUE TITLE
National Map v2018-04-16 pre-release test - Dept of Comms / ADSL availability - no borders 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#722]
Takes too long to load
Layer: National Datasets/Communications/Broadband ADSL Availability no Borders

![slide1](https://user-images.githubusercontent.com/22827786/39110473-c4c6ffc4-46c0-11e8-812d-b5dd743db1f6.JPG)

**Comment by AnaBelgun** [comment]
One of the many issue with the Dept of Comms data. Unfortunately it will not be fixed by custodian.
