### ISSUE TITLE
National Map v2018-04-16 pre-release test - Dept of Comms / telecommunications in development areas - Error loading 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#723]
Error loading catalogue item - hanged and then crashed the system
Layer: National Datasets/Communications/Telecommunications in New Developments

![slide2](https://user-images.githubusercontent.com/22827786/39110550-1b1fd404-46c1-11e8-9d1a-23ef196f6280.JPG)

![slide3](https://user-images.githubusercontent.com/22827786/39110587-3d7632a0-46c1-11e8-8333-2c730bab12d9.JPG)

**Comment by AnaBelgun** [comment]
Tested in IE and Chrome and doesn't seem to work. It's probably a problem with their data service. 
I'll add it to the list of custodians to contact. 
Added to this ticket: https://github.com/TerriaJS/nationalmap/issues/676
