### ISSUE TITLE
National Map v2018-04-16 pre-release test - GA / Elevation - Flow Grid - decommissioned

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#724]
Error loading catalogue item - hanged and then crashed the system
Layer: National Datasets/Elevation/Flow Grid Direction Image

![slide4](https://user-images.githubusercontent.com/22827786/39110645-75d49088-46c1-11e8-924c-3386acc14e3a.JPG)

**Comment by AnaBelgun** [comment]
To be removed from catalogue; data service decommissioned. 

https://github.com/TerriaJS/nationalmap/issues/615
