### ISSUE TITLE
National Map v2018-04-16 pre-release test - GA / Elevation - LiDAR 5m DEM - error loading

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#725]
Error loading catalogue item - Status Code: 504
Layer: National Datasets/Elevation/LiDAR 5m DEM

![slide5](https://user-images.githubusercontent.com/22827786/39110740-c6f94daa-46c1-11e8-9de1-4ac08e99ee2a.JPG)

**Comment by AnaBelgun** [comment]
It seems to work fine now in Chrome and IE: 
![image](https://user-images.githubusercontent.com/18452161/39413328-f2b645b0-4c6b-11e8-914a-2243bbf916a8.png)
