### ISSUE TITLE
National Map v2018-04-16 pre-release test - DoEE / Environment - Heritage List

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#726]
Error loading catalogue item - Status Code: 502
Layer: National Datasets/Environment/Commonwealth Heritage List (CHL)

![slide6](https://user-images.githubusercontent.com/22827786/39110793-fa004a78-46c1-11e8-8348-43f3f908e828.JPG)

**Comment by AnaBelgun** [comment]
It seems to work now: 

![image](https://user-images.githubusercontent.com/18452161/39413281-701eeaa8-4c6b-11e8-9c60-7e4285cee60a.png)

**Comment by AnaBelgun** [comment]
It seems to work now both in Chrome and IE: 

![image](https://user-images.githubusercontent.com/18452161/39413295-9a661386-4c6b-11e8-85fd-36c2db64f120.png)
