### ISSUE TITLE
National Map v2018-04-16 pre-release test - ABS / Environment - Energy supply - fails 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#727]
Error loading catalogue item - Failed
Layer: National Datasets/Environment/Energy supply and generation

Error occurred only on the first attempt!

![slide7](https://user-images.githubusercontent.com/22827786/39110871-5b18a9e0-46c2-11e8-9ce3-361827916b2e.JPG)

**Comment by AnaBelgun** [comment]
Seems to work fine now (from 1st attempt):

![image](https://user-images.githubusercontent.com/18452161/39412861-cc662476-4c65-11e8-90e0-90288c8f11d8.png)
