### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error loading catalogue Item - 7

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#728]
Error loading catalogue item - Status Code: 502, retest error Status Code: 504
Layer: National Datasets/Health/Medicare Offices

![slide8](https://user-images.githubusercontent.com/22827786/39111034-fd510572-46c2-11e8-95bb-6837eb58578d.JPG)

![slide12](https://user-images.githubusercontent.com/22827786/39111655-74ed6092-46c5-11e8-9326-5e78235f2cb5.JPG)

![slide13](https://user-images.githubusercontent.com/22827786/39111670-7ff3d7d2-46c5-11e8-8cc5-d2010b8b7664.JPG)

![slide14](https://user-images.githubusercontent.com/22827786/39111678-866cb20a-46c5-11e8-9767-388bdb5e3798.JPG)

**Comment by AnaBelgun** [comment]
Seems to work now in Chrome and IE; probably service temporarily unavailable. 
![image](https://user-images.githubusercontent.com/18452161/39412820-57c96e52-4c65-11e8-8a09-a4b58943e312.png)

![image](https://user-images.githubusercontent.com/18452161/39412832-6efbb04e-4c65-11e8-885f-52d0ef3da0dd.png)

Will close for now.
