### ISSUE TITLE
National Map v2018-04-16 pre-release test - GA Surface water / Canal Areas - zoom to extent unclear

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#729]
**Observation**

Incorrect Zoom to Extent setting?

Layer: National Datasets/Surface Water and Marine/Australian Hydrological Geospatial Fabric (Geofabric)/Canal Areas

![slide9](https://user-images.githubusercontent.com/22827786/39111215-e561c036-46c3-11e8-9d06-66698e0154b6.JPG)

**Comment by AnaBelgun** [comment]
This is part of the GA's Individual Hydrology and Marine Layers category (not the BoM Geofabric) and indeed the 'zoom to extent' seems unclear. Probably a flaw of the data service design. @kring would you please confirm.

**Comment by kring** [comment]
The server says that layer's extent is this:
![image](https://user-images.githubusercontent.com/924374/39413580-a7a07e52-4c6f-11e8-8e5e-0e7d04540125.png)
(see http://services.ga.gov.au/site_7/rest/services/NM_Hydrology_and_Marine_Polygons/MapServer/12)

If I draw that extent with the measure tool, it looks like this:
![image](https://user-images.githubusercontent.com/924374/39413573-945f29ba-4c6f-11e8-8a30-ae5fbef98993.png)

So NationalMap is correctly zooming to the server-provided extent. GA may want to verify that the server is reporting its extent correctly.
