### ISSUE TITLE
National Map v2018-04-16 pre-release test - data viz disappears after few minutes - error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#730]
Error loading catalogue item - Takes too long to load, then after loading displays the error - Staus Code: 503
Layer: National Datasets/Surface Water and Marine/Dynamic Hydrology and Marine Layer

![slide10](https://user-images.githubusercontent.com/22827786/39111340-49a6ab06-46c4-11e8-83a1-5e4993c028b8.JPG)

**Comment by AnaBelgun** [comment]
Duplication of #732
