### ISSUE TITLE
National Map v2018-04-16 pre-release test - GA Surface water - watercourse slow loading 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#733]
Takes a long time to load
Layer: National Datasets/Surface Water and Marine/Individual Hydrology and Marine Layers/Watercourse areas

![slide16](https://user-images.githubusercontent.com/22827786/39111880-31ba1364-46c6-11e8-8157-bced6f4a6ddb.JPG)

**Comment by AnaBelgun** [comment]
Performance seems ok in Chrome; nothing to fix at our end. Will close for now.
