### ISSUE TITLE
National Map v2018-04-16 pre-release test - Dummy/test catalogue entry (via data.gov.au)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#734]
Not sure if this dummy catalogue entry should be in Production!

Catalogue group: Data Request Default Organisation

![slide17](https://user-images.githubusercontent.com/22827786/39111946-78e03250-46c6-11e8-9c1c-f6872cbb8188.JPG)

**Comment by AnaBelgun** [comment]
Hi @maxious,. probably this entry needs to be deleted. Let us know if we need to do anything about it.

**Comment by maxious** [comment]
Hidden that dataset.

**Comment by kring** [comment]
It's still showing up for the moment due to caching, but it should vanish within 24 hours.
