### ISSUE TITLE
National Map v2018-04-16 pre-release test - Downloads empty CSV file

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#735]
**Downloads empty CSV file!** 

If the download function is not supported in KML format expect the option should be hidden.

Layer: Data.gov.au/Department of Communications and the Arts/Cybersafety Outreach Program (KML)

![slide18](https://user-images.githubusercontent.com/22827786/39112275-86bd454c-46c7-11e8-94f0-c43278a54b8c.JPG)

**Comment by AnaBelgun** [comment]
Looks like a bug (@kring to confirm)
Opened a terriaJS issue: https://github.com/TerriaJS/terriajs/issues/2948
Will close this one
