### ISSUE TITLE
National Map v2018-04-16 pre-release test - Poor visualisation of DHS indigenous data in KML (via data.gov.au)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#736]
**Observation**

Not sure if this is correct - could not see any feature on the map

Layer: Data.gov.au/Department of Human Services/Australian Government Indigenous Programs & Policy Locations (AGIL) dataset (KML)

![slide19](https://user-images.githubusercontent.com/22827786/39112509-3c9b6f38-46c8-11e8-8e33-ac0676d3688a.JPG)

**Comment by AnaBelgun** [comment]
Yes, not great viz but it's working and if  you change the map base and click on a (dark) point you get the feature info as well. Plus, there are other formats available for the user. 
![image](https://user-images.githubusercontent.com/18452161/39348683-794e751c-4a3b-11e8-9a5e-8fc8b7bee07f.png)

There's nothing more we can do about it.
