### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error loading GA KMZ layers (via data.gov.au)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#737]
Error loading KML or KMZ

Layer: Data Providers/Geoscience Australia/Air Traffic Services Centres

![slide20](https://user-images.githubusercontent.com/22827786/39112637-9c574910-46c8-11e8-8c6f-c9e10222f820.JPG)

**Comment by AnaBelgun** [comment]
Connected to #741 
Will close this one.
