### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error loading GA KMZ layers (via data.gov.au)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#738]
Error loading KML or KMZ

Layer: Data Providers/Geoscience Australia/National Coastal Maritime Navigation Lights Database

![slide21](https://user-images.githubusercontent.com/22827786/39112709-e146765e-46c8-11e8-8e88-25ec6438f234.JPG)

**Comment by AnaBelgun** [comment]
Connected to #741 
Will close this one.
