### ISSUE TITLE
National Map v2018-04-16 pre-release test - GA National Wastewater duplicate layers - one not working (via data.gov.au)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#739]
Error loading catalogue item - Status Code: 503
Layer: Data Providers/Geoscience Australia/National Wastewater Treatment Facilities WMS (WMS)

![slide22](https://user-images.githubusercontent.com/22827786/39112788-246a2642-46c9-11e8-831f-ac5f346a9837.JPG)

**Comment by AnaBelgun** [comment]
Connected to #740 
Will close this one
