### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error displaying GA KMZ files (via data.gov.au)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#741]
**Catalogue entries generating error**

Data group: Data Providers/Geoscience Australia/*

This Catalogue group entries need to be investigated!!

![slide24](https://user-images.githubusercontent.com/22827786/39113145-2a26083e-46ca-11e8-8326-a4baf91d267a.JPG)

**Comment by AnaBelgun** [comment]
Is probably connected to: https://github.com/TerriaJS/terriajs/pull/2716

Will close after @kring investigates

**Comment by kring** [comment]
The issue with the KMZ files has been reported a bunch of times, and needs to be fixed on GA's side. See https://github.com/TerriaJS/nationalmap/issues/623#issuecomment-342015868

> This ia CORS failure. The KML file comes from https://d28rz98at9flks.cloudfront.net/74778/AirTrafficServicesCentres_v1.kml. cloudfront.net is not in our proxy whitelist, because it is a domain that can host a wide range of content. And the server also does not support Cross-Origin Resource Sharing (CORS). So web security rules do not allow NationalMap to access it. This is not something we can fix in NationalMap, but GA could fix it by hosting the file at a gov.au domain or by enabling CORS support on the server.

There are also a few WMS servers in the list above, but those all seemed to work ok for me.
