### ISSUE TITLE
National Map v2018-04-16 pre-release test - BoM Geofabric catchments layer without graphics

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#742]
**Observation**

No graphics to display?

Layer: Data Providers/Water (Bureau of Meteorology Geofabric)/ Hydrology_Reporting_Catchments/(All) Hydrology_Reporting_Catchments

![slide25](https://user-images.githubusercontent.com/22827786/39113214-745fa1b2-46ca-11e8-93dc-ef54339e0fe0.JPG)

**Comment by AnaBelgun** [comment]
This is part of the BoM data catalogue curation issue on NatMap: Geofabric layers (old and new) are in different sections of NatMap catalogue. 
Connected to this issue: https://github.com/TerriaJS/nationalmap/issues/649
Included in NatMap May release. 
Will close this one. 

![image](https://user-images.githubusercontent.com/18452161/39346245-67773cd0-4a30-11e8-9c4a-7d74b4e3e477.png)
