### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error loading SA Gov / Metro real time passenger

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#744]
Error loading catalogue item

Layer: South Australian Government (BETA)/Development Portal Beta (GovHack 2017)/Adelaide Metro Real-Time Passenger Information

![slide27](https://user-images.githubusercontent.com/22827786/39113424-24863e16-46cb-11e8-8a0d-bf40f6862905.JPG)

Same issue as #745 and #746 
Might just need to add SA Gov to CORS
Data link on data.sa.gov.au: https://data.sa.gov.au/data/dataset/adelaide-metro-real-time-passenger-information/resource/329c0b1d-24c3-4748-a1c3-c38c275d0554

![image](https://user-images.githubusercontent.com/18452161/39345890-a04a5c7e-4a2e-11e8-9a19-10fb703812ee.png)

**Comment by AnaBelgun** [comment]
Probably connected to https://github.com/TerriaJS/nationalmap/issues/552
Will close after @kring investigates/confirms

**Comment by kring** [comment]
The problem here is that the dataset says it's a GeoJSON, but it's not. It's JSON, but not GeoJSON. This needs to be fixed within data.gov.au.
