### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error loading SA Gov / Acid Sulfate Soil Potential

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#746]
Error loading catalogue item

Layer: South Australian Government (BETA)/ Water, energy, resources, environment and science/ Acid Sulfate Soil Potential

![slide29](https://user-images.githubusercontent.com/22827786/39113584-aaf3264e-46cb-11e8-9c6a-c2224357c069.JPG)

**Comment by AnaBelgun** [comment]
We get this error when trying to upload (including suggesting that CORS might not be enabled)
![image](https://user-images.githubusercontent.com/18452161/39345756-ae85be9c-4a2d-11e8-950e-66162cd7e3d1.png)

**Comment by AnaBelgun** [comment]
Ticket moved to NatMap may release milestone

**Comment by AnaBelgun** [comment]
Could be connected to: https://github.com/TerriaJS/nationalmap/issues/552
Will close after @kring investigates/confirms

**Comment by kring** [comment]
There are a few problems stopping this one from working:
1. It's a 77MB ZIP file downloaded from a slow server, so CloudFront times out while waiting for the NationalMap proxy to obtain the file from the remote server.
2. Unzipped, it's a 232 MB GeoJSON file, which is too big to reasonably load into NationalMap.
I don't think there's much we can do to fix it.
