### ISSUE TITLE
National Map v2018-04-16 pre-release test - Error loading Local Gov/Ballarat 

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#747]
Error loading catalogue item – hanged and crashed the system

Layer: Local Government/Victoria/Ballarat/Ballarat 1 m contours (GeoJSON)

![slide30](https://user-images.githubusercontent.com/22827786/39113644-e42995ba-46cb-11e8-8e5f-14021d5fae9b.JPG)

http://nationalmap.gov.au/#share=s-vCZmpIHXlpglLWuXTN2gNWqwNaQ

**Comment by AnaBelgun** [comment]
Not something we can fix. 
Layer from data.gov.au: https://data.gov.au/dataset/ballarat-1m-contours
WMS layer is working
Will notify custodian of issues with the GeoJSON format; added to ticket https://github.com/TerriaJS/nationalmap/issues/676
