### ISSUE TITLE
National Map v2018-05-22 pre-release test - Data load error - Australian Antarctic Division - voyage track

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#756]
Error loading data
Layer: Data.gov.au/Australian Antarctic Division/2012-13 Season Voyage Track and Underway Data

![slide1](https://user-images.githubusercontent.com/22827786/40466123-67656e28-5f67-11e8-9786-ec05ca61cf52.JPG)

**Comment by AnaBelgun** [comment]
Underlying data comes from a data.gov.au resource with lots of duplicates and possibly other issues (with the service)

**Comment by AnaBelgun** [comment]
Advised data.gov.au team. 
Will reopen if necessary.
