### ISSUE TITLE
National Map v2018-05-22 pre-release test - Data load error - Wet Tropics Mngmt Auth -mountain locations

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#758]
Error loading data
Layer: Data.gov.au/Wet Tropics Management Authority/Wet Tropics Bioregion - Mountain locations (WTMA)

![slide3](https://user-images.githubusercontent.com/22827786/40466247-0620468c-5f68-11e8-9a51-281820d758b7.JPG)

**Comment by AnaBelgun** [comment]
same as #759
