### ISSUE TITLE
 National Map v2018-05-22 pre-release test - Data load error - Wet Tropics Mngm Auth - zones

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#759]
Error loading data
Layer: Data.gov.au/Wet Tropics Management Authority/Wet Tropics of Queensland World Heritage Area Zoning Scheme 1998 (WTMA)

![slide4](https://user-images.githubusercontent.com/22827786/40466300-482a004a-5f68-11e8-87dd-186e95b22d93.JPG)

**Comment by AnaBelgun** [comment]
To check first in data.gov.au 
It looks like this might need to be updated by the publisher. It might have an WMS available: http://eatlas.org.au/data/uuid/71127e4d-9f14-4c57-9845-1dce0b541d8d;jsessionid=F22DC17A6C696227D4CD059C5CC5B4AC

Will close and reopen if we need to update the service at our end. For now issue is sent to dga.
