### ISSUE TITLE
National Map v2018-05-22 pre-release test - Data load error - GA - Air Traffic Services Centres

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#760]
Error loading data
Layer: Data Providers/Geoscience Australia/Air Traffic Services Centres

![slide5](https://user-images.githubusercontent.com/22827786/40466335-79a96ed0-5f68-11e8-9e21-6d55d8b1499c.JPG)

**Comment by AnaBelgun** [comment]
Connected to https://github.com/TerriaJS/nationalmap/issues/741
Emailed GA
