### ISSUE TITLE
 National Map v2018-05-22 pre-release test - Data load error - GA - Transmission lines

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#761]
Error loading data
Layer: Data Providers/Geoscience Australia/Electricity Transmission Lines

![slide6](https://user-images.githubusercontent.com/22827786/40466374-b00368be-5f68-11e8-9b0d-71f4d7380f9c.JPG)

**Comment by AnaBelgun** [comment]
Connected with previous reported error with KMZ files: 
https://github.com/TerriaJS/nationalmap/issues/741
