### ISSUE TITLE
National Map v2018-05-22 pre-release test - Data load error - GA - Substations

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#762]
Error loading data
Layer: Data Providers/Geoscience Australia/Electricity Transmission Substations

![slide7](https://user-images.githubusercontent.com/22827786/40466405-e8239174-5f68-11e8-9134-b6ec775f1f0a.JPG)

**Comment by AnaBelgun** [comment]
Same issue previously reported (with KMZ files). 
https://github.com/TerriaJS/nationalmap/issues/741
