### ISSUE TITLE
National Map v2018-05-22 pre-release test - Data load error - VIC Gov - Traffic count locations

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#763]
Error loading data
- Page unresponsive
- Displays some graphics
- Freezes the system

Layer: Victorian Government/(No group)/Traffic count locations

![slide8](https://user-images.githubusercontent.com/22827786/40466481-53d591a6-5f69-11e8-8e8b-8db3c7609c47.JPG)

![slide9](https://user-images.githubusercontent.com/22827786/40466491-5b8cf34e-5f69-11e8-835c-866750a21854.JPG)

![slide10](https://user-images.githubusercontent.com/22827786/40466500-632d2a2e-5f69-11e8-9dba-a9277399ce84.JPG)

**Comment by AnaBelgun** [comment]
2018-06-21
Contacted dp&c@dpc.vic.gov.au and enquire assistance to check issues with these datasets: 
- Traffic count locations
- Traffic signals
- Pavement condition data
