### ISSUE TITLE
National Map v2018-05-22 pre-release test -  error ABS - Land management survey

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#764]
Error loading data
Layer: National Datasets/Land/Agriculture and Mining/Land Management Practices Survey 2011-2012

![slide12](https://user-images.githubusercontent.com/22827786/40466593-b583c5d0-5f69-11e8-952d-19c7bc192705.JPG)

**Comment by AnaBelgun** [comment]
retested and looks like working: 
![image](https://user-images.githubusercontent.com/18452161/41698620-bec01eb4-7562-11e8-8b9b-6ef425f38b6e.png)
