### ISSUE TITLE
Investigate traffic data from data.vic.gov.au - error on NationalMap

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#770]
When trying to add the Traffic Count locations (under Victorian Government group) harvested from data.vic.gov.au it doesn't work (it's trying to load without succeeding). 
Data is available in multiple formats here: https://www.data.vic.gov.au/data/dataset/traffic_count_locations
VIC team responded that data sources are working and are accessible.

**Comment by kring** [comment]
The KML (the one NationalMap chooses by default) doesn't work because it's big, 68 MB.

**Comment by AnaBelgun** [comment]
So the quickest solution would be to make the csv a csv-geo-au?

**Comment by kring** [comment]
Just tried fixing the column names, and even the CSV is too big to work well (it crashes the tab). It has over 57 thousand points. The quickest solution is to expose it as an Esri MapServer. If that's not an option, we'd have to do some significant work to make this work well.

**Comment by AnaBelgun** [comment]
ok, thanks, I'll let the VIC team know. I don't think it will be a priority to fix at our end, since they have more transport data on NatMap which works fine (although not traffic specific).

**Comment by rowanwins** [comment]
Dataset no longer available at that link
