### ISSUE TITLE
Add Emergency Services Facilities - GA service

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#779]
This is the authoritative national dataset and any similar layers currently on NationalMap should be reviewed.

Service endpoint:
https://services.arcgis.com/RylLPiI61AyfENce/ArcGIS/rest/services/National_set/FeatureServer
Metadata: 
https://docs.wixstatic.com/ugd/e7ba1c_1965ca72531d4ab8bdf587db64229ca8.pdf

Wait for custodian to revise metadata before publishing!!!

**Comment by AnaBelgun** [comment]
Publishing pending approval from GA.

**Comment by meh9** [comment]
If we haven't got it by now we're not getting it. :)
