### ISSUE TITLE
NationalMap can't seem to Add Web Data from external URLs.

### ISSUE THREAD

**Issue by QuadTog** [TerriaJS/nationalmap#780]
**Issue**
We had a user report an issue with the dataset they're hosting:
    https://www.digitalgraphics.com.au/rtm/suburbs.csv

It won't load the data via '_Add Web Data_' but if downloaded and drag-dropped it works fine (albiet with some issues 😄).

So it seems like NationalMap won't read .csv's from external URLs. Mind if we grab some clarification around the processes here?

**Results/Screenshots:**
**External URL:**
![image](https://user-images.githubusercontent.com/20583588/43563251-93a94638-9664-11e8-9ad3-8bf773548fb0.png)

**Drag-Drop:**
![image](https://user-images.githubusercontent.com/20583588/43563770-058ab0fa-9667-11e8-96c4-84e646a21397.png)

**Comment by AnaBelgun** [comment]
@QuadTog Hi. The team thinks it is a CORS problem.  www.digitalgraphics.com.au isn’t in our proxy whitelist, so if the server doesn’t support CORS, it won’t work. To find more info about CORS: https://terria.io/Documentation/guide/connecting-to-data/cross-origin-resource-sharing/
