### ISSUE TITLE
NationalMap Share doesn't remember splitter settings

### ISSUE THREAD

**Issue by QuadTog** [TerriaJS/nationalmap#785]
**Issue**
NationalMap share link remembers Splitter position, but not splitter division (eg. left/right).

Here's the Share link (share=s-ApJuYVHiBs16X2Lgfi4d1aZdUEx) I prepared with a working splitter:
![image](https://user-images.githubusercontent.com/20583588/45402632-f6b35700-b699-11e8-8796-68fba753a8a4.png)

**Results/Screenshots:**
Visit share link: http://nationalmap.gov.au/#share=s-ApJuYVHiBs16X2Lgfi4d1aZdUEx
![image](https://user-images.githubusercontent.com/20583588/45402642-03d04600-b69a-11e8-8d50-e26857e7aed4.png)

**Comment by AnaBelgun** [comment]
Hi @QuadTog. yes, you're right, when checking with your data selection (social economic indices by SA2 and taxation), when you share the splitter doesn't show the data left and right. Instead it shows both data sets turned on on whole screen. 
However, when tested with the satellite imagery (any random data layer) in two cases: 1) one data layer splitted to show different times and 2) two different data layers, sharing the split behaves normally (identical image as the original one).
Would you mind testing that too and see it it works as expected?
will then investigate if it's a terria bug or data issue.

**Comment by QuadTog** [comment]
Hey Ana,

Yup; ya right. Tested with some satellite data, time data etc. and it all works. Time is remembered, and the split. So I think it's because of the Tax URL: 
http://stat.data.abs.gov.au/sdmx-json/data/ABS_SEIFA_SA2 

It's probably pulling this data each time you share the link and it recreates the data and forgets the split position. For example: Here's the same as before but with Landsat8 data added (and the Landsat split is remembered but Tax is forgotten):
http://nationalmap.gov.au/#share=s-jtW5tsjo16SHfhAK9ZLdkHqHBph
