### ISSUE TITLE
Add TERN GEOSS Auscover layers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/nationalmap#795]
Details here: http://wiki.auscover.net.au/wiki/GEOSS_ecosystem_map

Explanation of why they're important: http://www.tern.org.au/Australia-s-newest-globally-consistent-ecosystem-map-bgp4339.html?platform=hootsuite

**Comment by AnaBelgun** [comment]
@stevage I've tried to drag and drop some of the services on map and they don't seem to work; also went on TERN website and I can't seem to find the services

**Comment by stevage** [comment]
Hmm, at least some of them seem to work ok for me: 
http://nationalmap.gov.au/#share=s-ccizYBh15r9YdMeHX025sdBXzAG

**Comment by AnaBelgun** [comment]
Not sure what I do wrong, but I get this when copying the service url: 
![image](https://user-images.githubusercontent.com/18452161/46647637-f47ee280-cbdc-11e8-8912-8077826c7da0.png)

**Comment by stevage** [comment]
Hmm, I'm not sure. It's a little bit confusing in that the visible text and the hyperlink aren't the same on that wiki page, but most seem to work ok for me.
