### ISSUE TITLE
Update Innovation map

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#812]
Update Innovation Map with latest dga upload from DIIS

Could you please add the National Research Infrastructure dataset to National Map, listing the data sets (as following):

SA3 Region Innovation Data 2009-15
Innovation Precincts
National Research Infrastructure

DIIS have now uploaded the National research infrastructure – October 2018 file onto data.gov.au, link: 
https://data.gov.au/dataset/2c403f7d-2d61-4d0c-9557-a1c25e46a96e/resource/f2a53e3f-dbee-4eaf-a09c-765413dd104e/download/national-research-infrastructure-october-2018.csv

**Comment by AnaBelgun** [comment]
HI Mats and Ana,

Apologies, I have received further clarification re process behind the adding of data to the InnovationMap (IFrame to the National Map).

**Comment by meh9** [comment]
https://nationalmap.gov.au/#share=s-iXg8wGybmaVxtufNEd94aiAsqhC

Fixed?
