### ISSUE TITLE
Respect min/max scale restrictions on WMS services

### ISSUE THREAD

**Issue by keithmoss** [TerriaJS/nationalmap#815]
# Issue
One of our agencies has published threatened species data as a WMS service with scale restrictions applied.

Due to the sensitivity of the data they require the WMS to not display any detail beyond 1:200,000 scale. i.e. It's OK for the public to see the rough shape and distribution of the data, but they shouldn't be able to identify specific locations.

The WMS service has been published with this scale restriction on its display (see below for specifics).

NationalMap's current behaviour is to:

* Stop requesting new tiles from the service once the user moves outside the scale range, and
* continue to display and resample the last requested set of image tiles.

_Last Tile Requested_
![dbca_1](https://user-images.githubusercontent.com/5944358/49193581-7eb41d80-f3ba-11e8-887a-8de09f3d2fab.png)

_Resampled Tile (Zoomed in +2)_
![dbca_2](https://user-images.githubusercontent.com/5944358/49193597-8d9ad000-f3ba-11e8-95c8-357dd4915676.png)

The custodian is concerned that this will still allow people to identify specific locations and would like NationalMap to hide the layer's image tiles when the user is outside the designated scale range.

In our experience this is the convention applied by other spatial applications and is more in keeping with the intent of the latest WMS spec i.e. The layer's data (image tiles for WMS, actual raw data for WFS) is hidden when the user is not within the designated scale range.

Are you open to making this change?

# Further Info
In our [Environment WMS service](https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Environment/MapServer/WMSServer?request=GetCapabilities&service=WMS) these scale restrictions are set:

```xml
<MinScaleDenominator>188988.095238</MinScaleDenominator>
<MaxScaleDenominator>9449404.761905</MaxScaleDenominator>
```

for these layers:

* [Threatened and Priority Flora (DBCA-036)](http://services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Environment/MapServer/21)
* [Threatened and Priority Fauna (DBCA-037)](http://services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Environment/MapServer/22)

# WMS Spec
This behaviour may stem from difference in how WMS 1.1.1 and 1.3. 0 describe scale restrictions.
 
## WMS 1.1.1
WMS 1.1.1 defines a scale hint that **suggests** to clients what the optimal scale range is for the given layer.

```xml
<ScaleHint min="79.195959" max="3959.797975"></ScaleHint>
```
 
> "Minimum and maximum scale hints for which it is appropriate to display this layer."
 
## WMS 1.3.0
WMS 1.3.0 introduced **scale restrictions** for servers and clients that are a little more restrictive, but that do allow servers to return a blank map if the layer is outside the scale range.
 
> "The `<MinScaleDenominator>` and `<MaxScaleDenominator>` elements define the range of scales for which it is appropriate to generate a map of a Layer. Because maps from a WMS may be viewed on arbitrary displays rather than on paper, the values used are actually the scale denominators relative to a common display pixel size.
>
> The scale denominator values are guidelines for clients, not firm limits. Upon receiving a request for a map that is not within the scale denominator range, the server may return a blank map, or may return a portrayal of the Layer that is crowded with features or otherwise poorly suited for display; the server shall not respond with a service exception."

**Comment by kring** [comment]
@keithmoss I don't think this is a good default for Terria. Maps disappearing when zooming in is pretty user-unfriendly, and the supposed security benefits are highly questionable. However, we do have an option in `ArcGisMapServerCatalogItem` to enable this sort of behavior. Specifically, you would set `maximumScaleBeforeMessage` to the desired scale limit, and `showTilesAfterMessage` to false. Then, when you zoom in past the layer's limit, you'll see a message like:

> The [name] dataset will not be shown when zoomed in this close to the map because the data custodian has indicated that the data is not intended or suitable for display at this scale.  Click the dataset's Info button on the Now Viewing tab for more information about the dataset and the data custodian.'

We don't currently have an option like this for WMS, but it would be reasonable to add one.

**Comment by keithamoss** [comment]
Agreed - and a configurable option works well for us.

Are these new options you're suggesting theoretically configurable for the catalogue of layers that you load from DataWA's CKAN?

**Comment by kring** [comment]
It would need to be applied to all the layers from DataWA's CKAN, but as long as that's ok, the `itemProperties` property can be used to apply it to all the layers discovered from CKAN.

**Comment by keithamoss** [comment]
Talking to our Spatial Services Team - How will the `maximumScaleBeforeMessage` display to the user? As a popup dialog or as a notification?

**Comment by kring** [comment]
It will display as a popup dialog when the resolution is first exceeded, and not be shown again unless the layer is toggled off and back on.

**Comment by keithamoss** [comment]
Good good - And `showTilesAfterMessage: false` will hide/remove tiles for any of our layers on NationalMap when the user is outside the given scale range?

**Comment by kring** [comment]
Yep, exactly.

**Comment by keithamoss** [comment]
Neat - that'll work for us. Let us know once it's in DEV and we'll test and run it past the data custodian for input. Thanks Kevin!

**Comment by keithamoss** [comment]
@kring Just had a quick look at the PR - am I right in saying that there's no need for us to set a `maximumScaleBeforeMessage` for this behaviour since NationalMap will just display a generic message?

**Comment by kring** [comment]
Yep that is correct @keithamoss.
