### ISSUE TITLE
Enable WCS clip and ship 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#819]
All DEA web services delivered from GSKY and ODC-WCS now have WCS enabled. Enable Clip & Ship for the following: 

- [x] Barest Earth

- [x] Landsat 16 day aggregate

- [x] Landsat daily observations

- [x] Sentinel 2 NRT

- [x] Landsat Annual Geomedians

- [x] Mangroves

- [x] ITEM - Intertidal Extents Model?

- [x] HLTC - High Tide Composite layers?

- [x] NIDEM - National Intertidal Digital Elevation Model

- [x] WOfS Full Summaries

- [x] WOfS Annual Summaries

- [x] WOfS Daily

- [x] Weathering intensity

- [x] Multi-Scale Topographic Position

**Comment by stevage** [comment]
Context for me:

* What clip and ship is: https://github.com/TerriaJS/terriajs/issues/2937
* Example [here](https://github.com/TerriaJS/terria-cube/blob/master/wwwroot/init/terria-cube.json#L57)

**Comment by stevage** [comment]
I'm not quite sure about these layers:

* NIDEM - can't find anything called anything like that
* Daily Landsat - are these all the Landsat ones that aren't medians?

Also not sure about the significance of the question marks on two of them :) But I did them.

**Comment by stevage** [comment]
OIC, the NIDEM one depends on #817

**Comment by stevage** [comment]
NIDEM one fixed in #817.

**Comment by AnaBelgun** [comment]
@kring I had a look at the merge and catalogue release and cannot find the export functionality at Sentinel and Landsat layers

Landsat 16 day: https://www.nationalmap.gov.au/#share=s-v8xRRlfAhKJ90cxShaoEa6arYzE 
![image](https://user-images.githubusercontent.com/18452161/56330328-eaacec00-61ca-11e9-9e5e-bb8ca1377a47.png)

Sentinel NRT 
https://www.nationalmap.gov.au/#share=s-oqnXJfg0woTHQWC6LxOoTTDqev8

![image](https://user-images.githubusercontent.com/18452161/56330366-192ac700-61cb-11e9-8e3d-6141e2863ead.png)


The current placement of satellite imagery under 2 catalogue groups adds to the confusion but will deal with that here: https://github.com/TerriaJS/nationalmap/issues/837
