### ISSUE TITLE
Add latest ABS State Electoral Divisions (SED)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#827]
prepare and add the CED 2018 version to NationalMap 
-	There are 3 distinct processes: 
1)	Configuring region mapping = adding the regions to the terria region mapping server (to allow any csv-geo-au formatted dataset, mapped against CED 2018 to be visualised on NatMap)
2)	Providing access to boundary-coded datasets = connecting to the CED 2018 data (not geometry) via the SDMX JSON API
3)	Providing access to boundary geometry = showing the regions on the map and allowing people to download the corresponding shapefile)

Short term: 
-	Steve will work on adding the CED 2018 to the region mapping server and updating the csv-geo-au https://github.com/TerriaJS/terriajs/issues/3203 
-	Estimated upload to the ABS.stat – Mar 2019
-	ABS team to send terria team a pre-release sample to test the CSVs

**Comment by AnaBelgun** [comment]
probably will be done in March/April release of NatMap

**Comment by alakaboo** [comment]
Is it possible to add the 2018 SEDs to this request as well, or should I lodge a separate issue?

**Comment by AnaBelgun** [comment]
@stevage would you please look at SED 2018 too? 
https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.003~July%202018~Main%20Features~State%20Electoral%20Divisions%20(SEDs)~4
