### ISSUE TITLE
Remove the catalogue group Data providers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#837]
Catalogue group Data Providers creates confusion. All data on NatMap is provided by a custodian. 
Group should be removed and all the datasets should be moved under other categories: 
- ABS Statistical Boundaries - to be moved under Statistical Boundaries - as is
- Australian Institute of Marine Science - to be moved under Surface Water and Marine
- GA - to delete TBC the service cannot be revived
- State of Environment 2016 - to move under Environment group

**Comment by AnaBelgun** [comment]
we're waiting for GA to confirm some changes to their data position in the catalogue

**Comment by reginapramesti** [comment]
@AnaBelgun what about the category Digital Earth Australia? And also, are we still waiting for confirmation from GA?

**Comment by reginapramesti** [comment]
So far I've moved:

State of Environment 2016 to the Environment category
![](https://user-images.githubusercontent.com/16102484/57213344-d6217e00-7029-11e9-8dac-806b28ebc37b.png)

ABS Statistical Boundaries to the Statistical Boundaries category
![](https://user-images.githubusercontent.com/16102484/57213396-0832e000-702a-11e9-95a9-629186c5374f.png)

and Australian Institute of Marine Science to the Surface Water and Marine category
![](https://user-images.githubusercontent.com/16102484/57213443-2d275300-702a-11e9-9944-83959c25c87d.png)

I'll move the rest once I get that

**Comment by AnaBelgun** [comment]
with DEA we need to wait for this PR https://github.com/TerriaJS/NationalMap-Catalog/pull/121 and then moved all of them under Satellite Imagery

**Comment by AnaBelgun** [comment]
We have to now wait for the Sat Imagery names to be updated: https://github.com/TerriaJS/nationalmap/issues/852
