### ISSUE TITLE
Add clip and ship for Sentinel 2A/2B

### ISSUE THREAD

**Issue by stevage** [TerriaJS/nationalmap#847]
From Ana's comment [here](https://github.com/TerriaJS/NationalMap-Catalog/pull/114#issuecomment-487425729):

>It seems that all layers in this list TerriaJS/nationalmap#819 present the "export" functionality; the ones that don't are near real time: Sentinel 2A and 2B

>https://www.nationalmap.gov.au/#share=s-iywJoGZ2OkVPaYGHhED0innRXNK
>https://www.nationalmap.gov.au/#share=s-4eCiOwI1vElV8otQOyrkooXlwrs

>They do have the Export on the TerriaCube prototype site:

>https://terria-cube.terria.io/#share=s-powNQcCnUmwb7V31s1jCmtdDPoQ

**Comment by AnaBelgun** [comment]
@stevage is this something you have to do an re-merge?
