### ISSUE TITLE
data.vic.gov.au is broken

### ISSUE THREAD

**Issue by stevage** [TerriaJS/nationalmap#850]
The URL https://www.data.vic.gov.au/data returns a 301. Haven't investigated further than that.

**Comment by kring** [comment]
It's redirecting to `data.vic.gov.au` instead of `www.data.vic.gov.au`, but the redirect response doesn't include a CORS header so the browser redirects it. Most likely we can just change our URL to `data.vic.gov.au` and it will work fine.
