### ISSUE TITLE
Reinstate Broadband data layers in Communications group on NatMap 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#859]
The broadband layers have been removed due to data services not being available. 
DTA and Dept of Communications have fixed the issue and approved the data to be reinstated in the catalogue due to popular demand. 

The windows mapping server has been reinstated and data is now available again on data.gov.au

https://data.gov.au/dataset/ds-dga-e9f887d7-f437-43ca-8e00-c1a288d225b3/details?q=broadband

**Comment by kring** [comment]
Fixed by https://github.com/TerriaJS/NationalMap-Catalog/pull/125
