### ISSUE TITLE
Question regarding feature information popup overlap on embedded map

### ISSUE THREAD

**Issue by ashleysommer** [TerriaJS/nationalmap#865]
See this page for example: https://geofabricld.net/catchment/12101198

This uses the centroid of the catchment to make a picked feature to display on map startup.
Is there a way to have the feature information overlay popup be collapsed by default when loading the embedded map? As you can see in this example, the overlay covers half of feature of interest. Is there an option to not expand the overlay by default when setting a picked feature?

**Comment by kring** [comment]
@ashleysommer there's not currently a way to do that, but adding such a feature to TerriaJS wouldn't be too hard if you're up for it. The relevant property is `featureInfoPanelIsCollapsed` on `ViewState`.
