### ISSUE TITLE
VIC data.gov broken 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#876]
No Victorian Government data can be retrieved. Gives the following error:

Victorian Government
Couldn't retrieve packages from this CKAN server.

If you entered the URL manually, please double-check it.

If it's your server, make sure CORS is enabled.

Otherwise, if reloading doesn't fix it, please report the problem by sending an email to data@digital.gov.au with the technical details below. Thank you!

Request has failed

**Comment by rowanwins** [comment]
Seems to be resolved
