### ISSUE TITLE
Australia Post locations

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#878]
Add Australia Post locations: https://drive.google.com/file/d/15A4AjTD_5NP-MwieByYjpaJmmQaPNOI3/view

or ideally using one of the APIs here: https://developers.auspost.com.au/docs/reference

**Comment by soyarsauce** [comment]
@rowanwins what was the latest stance for this?
cc @AnaBelgun

**Comment by AnaBelgun** [comment]
It was useful to add to NationalMap because we would have added to Droughtmap, but that action has been parked for now. If we are to add it to NatMap only, do we need to host the csv or can we just use the API? I think last time Rowan had a look, we had to use the csv.

**Comment by rowanwins** [comment]
Yeah so the API isn't a goer. 

We would need to add it as a static csv file in the `data` dir although I think we probably want to tidy up the columns a bit.

**Comment by na9da** [comment]
I did a minimal clean up of the CSV and this is what I have. Is it good enough and which group should I add it to?

![Screenshot](https://user-images.githubusercontent.com/1430/62923068-43df0200-bdf0-11e9-97d6-bd527ce7b86a.png)

**Comment by AnaBelgun** [comment]
@na9da looks good; shall we put it under Habitation?
