### ISSUE TITLE
NatMap WMS Proxied URL Issue

### ISSUE THREAD

**Issue by vduong2** [TerriaJS/nationalmap#879]
When we add the service directly in NationalMap via Add Web Data => Choose WMS => Add URL NationalMap constructs this proxy URL:

https://nationalmap.gov.au/proxy/_1d/https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Transport/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0&tiled=true

It works and returns a valid GetCapabilities document.

When our CKAN embeds NationalMap for a layer in this service:

https://catalogue.data.wa.gov.au/dataset/city-of-perth-car-parks/resource/77c6ba1e-b3d0-34a0-a2f3-726d26edfb10

It constructs this URL for the embed widget:

https://nationalmap.gov.au/#clean&hideExplorerPanel=1&start=%7B%22version%22%3A%220.0.03%22%2C%22initSources%22%3A%5B%7B%22catalog%22%3A%5B%7B%22type%22%3A%22group%22%2C%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22The%20group%20for%20data%20that%20was%20added%20by%20the%20user%20via%20the%20Add%20Data%20panel.%22%2C%22isUserSupplied%22%3Atrue%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22type%22%3A%22wms%22%2C%22name%22%3A%22User%20Data%22%2C%22isUserSupplied%22%3Atrue%2C%22isOpen%22%3Atrue%2C%22isEnabled%22%3Atrue%2C%22url%22%3A%22https%3A%2F%2Fservices.slip.wa.gov.au%2Fpublic%2Fservices%2FSLIP_Public_Services%2FTransport%2FMapServer%2FWMSServer%22%2C%22layers%22%3A%229%22%7D%5D%7D%5D%2C%22catalogIsUserSupplied%22%3Atrue%2C%22homeCamera%22%3A%7B%22west%22%3A115.81977546540351%2C%22south%22%3A-31.987039074617382%2C%22east%22%3A115.88383368062877%2C%22north%22%3A-31.94293940258389%7D%7D%5D%7D

This ends up sending a proxied request to our WMS service with the following URL structure:

https://nationalmap.gov.au/proxy/_1d/https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Transport/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities

This returns an HTTP 400 error generated by our ArcGIS Server.

If we go directly to the proxied URL:

https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Transport/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities

It works (as expected).

If we change the order of the URL parameters in the proxied URL to switch 'version' and 'request':

https://nationalmap.gov.au/proxy/_1d/https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Transport/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0

The NatMap proxied URL suddenly works.

We're stumped. Is the NationalMap proxy doing anything that's dependent on the order of the URL parameters?

This appears to be the only service we have that's impacted in this way. Other services work perfectly well as far as we've tested, for example:

https://catalogue.data.wa.gov.au/dataset/shipwrecks/resource/d4f88a9a-4e7c-3687-a147-f1e539acf427

The below is displayed in the ArcGIS Server error logs
Error handling request to service 'SLIP_Public_Services/Transport.MapServer'. java.lang.Exception: AutomationException: 0x80070057 - Invalid http method. in '"esriCarto.WMSServer"'

Thanks!

**Comment by kring** [comment]
@vduong2 I'm getting a valid response (instead of a 404) from:
https://nationalmap.gov.au/proxy/_1d/https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Transport/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities

Most likely the problem was that either the NationalMap proxy or your web browser has cached a bad response from your server. Changing something as simple as the order of parameters avoids the cached copy. The proxy's cache will expire after 1 day (that's what the `_1d` means). Generally it shouldn't cache a 404, but WMS servers often return errors as 200 responses, in which case they _will_ get cached.

I'm closing this because I don't think there's much to do on our side, but feel free to reopen if you want to discuss further.

**Comment by vduong2** [comment]
Cheers thanks Kevin.
