### ISSUE TITLE
Main page anniversary pop-up + feedback page

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#884]
In the lead up to the 5 Year anniversary of NationalMap, it would be great to ask the public to send relevant stories of using NatMap datasets. changes to be made: 

- [x] develop a pop-up window with the text: "NationalMap is turning 5! and we're looking for great stories. Let us tell yours! Get in touch at info@terria.io or use the feedback button.” 

- [ ] apply changes to the feedback text to say: 
"Tell us about a problem that National Map helped you solve or how it has supported your organisation."

**Comment by AnaBelgun** [comment]
@philipgrimmett would you please create some options for this?

**Comment by meh9** [comment]
"pop-up window" is probably using a relabelled disclaimer window?

**Comment by kring** [comment]
We need to consider what happens in a few scenarios. Does the pop-up still show?
* Visiting a share link
* Visiting a share link that contains stories
* Visiting a share link that contains stories and `playStory=1` is in the URL.
* Map is embedded in another page (e.g. data.gov.au or or https://catalogue.data.wa.gov.au/dataset/wamsi-2-kimberley-node-project-1-1-2-key-ecological-processes-in-kimberley-benthic-communit_b7df/resource/fbfd9499-c9ac-4673-95f2-e15adad9de92)
* Mobile UI
* Probably others?

**Comment by AnaBelgun** [comment]
was thinking it will be exactly how the disclaimer currently runs in AREMI
- visiting a share link - yes, will appear
- visiting a share link that contains stories - yes, will appear (especially in this case, to encourage users to create their stories using the story feature)
- Visiting a share link that contains stories and playStory=1 is in the URL - yes, I guess (not 100% sure)
- Map is embedded in another page - yes
- mobile UI - yes

just a reminder this will run for 2 weeks approx

**Comment by AnaBelgun** [comment]
pending product owner decision

**Comment by philipgrimmett** [comment]
Invision prototype:
https://invis.io/MGSP05OAD8E#/370744937_NM_-_5th

Note: click NT to launch modal
