### ISSUE TITLE
Update Satellite Blended with new layer name temporarily

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#894]
The layer National Datasets -> Satellite Images -> Satellite Images Multi-Sensor Blended - daily -> Hill shadows removed -> Landsat and Sentinel-2 Blended Service needs to have the layer name updated from `blend_sentinel2_landsat_nbart_daily` to `blend_sentinel2_landsat_nbart_daily_true_colour`.

This is to get things working for now, and then we will most likely have to roll back at some point in the future.

**Comment by na9da** [comment]
Fixed by TerriaJS/NationalMap-Catalog#134.
