### ISSUE TITLE
new layers from DoEE

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/nationalmap#898]
http://www.environment.gov.au/mapping/rest/services/ogc_services

Some are useful in RaPP Map, could be useful in NAt Map as well.
Particularly: 
NRM Natural_Resource_Management_Regions (MapServer) 
National_Landcare_Program_Management_Unit (MapServer)  (be careful about large poly in the ocean, freezes Terria when doing feature info)
A few more probably on conservation areas, wetlands and so on

**Comment by meh9** [comment]
@rowanwins any thoughts on if we can stop a MapServer from sending the `geom`, as the "freeze" is Terria trying to render a 4.5mb gzipped chunk of GeoJSON?

**Comment by meh9** [comment]
Here's the layer with very large polygon, click anywhere in the ocean inside the Australian EEZ (I think it is): https://map.geo-rapp.org/#share=s-3oUbH6FLeAqSheRjxCOwoEHvK1S

**Comment by rowanwins** [comment]
There is a parameter for not sending the geom (eg `returnGeometry = false`), however that would mean we'd not be able to show the highlight region.

Another alternative is there is a parameter for simplifying the geometry (eg `maxAllowableOffset =2`) and also limiting the precision of coords sent back (eg `geometryPrecision=6`). It might be worth trialling these first and seeing if they can generate helpful results before culling the geometries completely.

**Comment by juan-guerschman** [comment]
thanks @rowanwins
