### ISSUE TITLE
Add Catchment Scale Land Use 2018

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#906]
Under the Land group, separate the Agriculture & Mining into 2 new subgroups: Agriculture and Mining and include the new 2018 version of CLUM data:  http://www.asris.csiro.au/arcgis/rest/services/abares/clum_50m_2018/MapServer 
	

- Replace the existing C Catchment scale land use 2017 with the new data

- Reorder the entry so it is directly under Land – currently it is under Agriculture and Mining

- Enable users to use any of the 5 depictions in the WMS.

**Comment by reginapramesti** [comment]
Resolved as part of https://github.com/TerriaJS/NationalMap-Catalog/pull/142
