### ISSUE TITLE
Allow setting a custom request limit for different servers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#910]
increase the performance of services by changing the limit of requests
fixed in DE Africa
https://github.com/TerriaJS/de-africa-map/pull/19

**Comment by AnaBelgun** [comment]
To use the latest limit @steve9164 is implementing for DE Africa

**Comment by reginapramesti** [comment]
We won’t add custom request limits for DEA services, as fixing the cesium bug to allow 6 requests is adequate
