### ISSUE TITLE
Remove the 32 day time limit from BoM hydro data

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/nationalmap#924]
https://github.com/TerriaJS/NationalMap-Catalog/blob/master/datasources/National_Datasets/Water.ejs#L244

Remove the `"defaultDuration": "32d"`, noting that this change needs to be applied to a number of layers.

**Comment by AnaBelgun** [comment]
fixed by https://github.com/TerriaJS/NationalMap-Catalog/pull/150
