### ISSUE TITLE
Update catalogue of Satellite Imagery data to show points not lines on charts

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#936]
Currently the satellite imagery dates are still shown as lines on charts rather than points: https://nationalmap.gov.au/#share=s-4kB94VANOqEIpiDNPSHlv9oM7az

A catalogue update is needed to change to points (latest charts sat imagery interaction design)

**Comment by rowanwins** [comment]
The reason I hadn't done this was because GA have their own instances - I wasn't sure if changing the appearance on the chart for all users on NM was something that made sense.

**Comment by soyarsauce** [comment]
@rowanwins it sounds like this can be done on per catalog item? Can you point me to where the tjs updates are that do this?

**Comment by soyarsauce** [comment]
>... no update; ... there are other maps to use the dot style forn ow
