### ISSUE TITLE
NationalMap catalogue update for Western Australia layers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/nationalmap#940]
We need to do a NatMap catalogue update for Western Australia layers as not all layers are showing up. 

E.g.:

https://catalogue.data.wa.gov.au/dataset/main-roads-regions

https://catalogue.data.wa.gov.au/dataset/tri-drive-concessional-network-3-1-td3-1-without-conditions-

These are the catalogue files we need to work on:

https://github.com/TerriaJS/NationalMap-Catalog/blob/master/datasources/includes/WA.ejs

https://github.com/TerriaJS/NationalMap-Catalog/blob/master/datasources/includes/data_wa_org.ejs

Issues:
- [ ] Change the URL from `...catalogue.beta.wa...` to `...catalogue.wa...`
- [ ] `WA.ejs` only allows `WMS` datasets that has homepage URL's that include the string `_Public_Services`, i.e. public datasets from SLIP such as this https://catalogue.data.wa.gov.au/dataset/aboriginal-heritage-places. The reason for this is that there are other non-public datasets that have homepages such as https://catalogue.data.wa.gov.au/dataset/distribution-overhead-power-lines-wp-031 which has the string `_Public_Secure_Services` which you cannot access openly.

We need to widen the search query to include other datasets with other types and other homepages, such as https://catalogue.data.wa.gov.au/dataset/main-roads-regions

I tried doing this in order to try to capture the Mainroads dataset above:

```
    {
      "type": "ckan",
      "name": "Western Australian Government OGC WMS",
      "url": "http://catalogue.data.wa.gov.au/",
      "groupBy": "organization",
      "filterQuery": [ 'q=res_format:("OGC WMS")' ],
      "wmsResourceFormat": '/^ogc wms$/i'
    },
```

The dataset is included in the response on the Network tab, but the group in the Terria catalogue is empty, so I'm missing something in how to make the `CkanCatalogGroup` add it as a layer.

Thoughts:
- I don't think filtering only for `_Public_Services` is going to work any more, as it excludes all non-SLIP services.
- There now appears to be many new format strings such as `OGC WMS` and others that we wouldn't actually look for.
- When we actually do look for those we probably also have to change the regex that `CkanCatalogGroup` use to determine what format a resource is. 
- We might have to do a mini-inventory together with WA and possibly normalise format names?

**Comment by rowanwins** [comment]
See also #946

**Comment by rowanwins** [comment]
Looks like we could perhaps make use of `"access_level": "open"`
````
      "filterQuery": [ "q=access_level:open&fq=res_format:WMS" ]
````
Setting that takes us from 46 items to 502
