### ISSUE TITLE
Add more Forests data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#943]
-	Tenure of Australia’s forests (2018)
URL :  https://data.gov.au/data/dataset/a923c977-8db4-4451-9740-8ff24b94742c 
WMS is available here: http://www.asris.csiro.au/arcgis/rest/services/abares/tenure_of_australias_forests_2018/MapServer

-	Australia’s Indigenous Forest Estate (2018) 
 URL: https://data.gov.au/data/dataset/a8715d8f-a8e4-4318-9a81-491d23506622  
WMS is available here:  http://www.asris.csiro.au/arcgis/rest/services/abares/australias_indigenous_forest_estate_2018/MapServer 

-	Fire in Australia’s Forests (2011-2016)
URL:  https://data.gov.au/data/dataset/c0cd6f5a-6b0f-4cd0-8980-1ca5b2c31006 
WMS(two layers) are available here: https://www.asris.csiro.au/arcgis/rest/services/abares/fire_in_australias_forests_2011_2016/MapServer :
Layer 1:  Fires in Australias Forests 2011-16 [2018] [Fire Type 2011-12 to 2015-16] (0) 
Layer 2:  Fires in Australias Forests 2011-16 [2018] [Number of fires 2011-12 to 2015-16] (1)

**Comment by mwu2018** [comment]
It appears that `Tenure of Australia’s forests (2018)` already exists. @steve9164 . See
https://nationalmap.gov.au/#share=s-l5Mk1Tf0B32wtbUOcZOWIftjkqT
