### ISSUE TITLE
Consolidate fire related data from States and Territories

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#944]
Given latest developments and the number of data sources and applications users have to access for fire, traffic and weather data, it would be good to consolidate this information on NationalMap, as another option to give access to general public. 
This is not to replace the State based applications or platforms. 

1st step - contacting the data custodians
2nd - access readily available (open data services)
3rd - work with custodians to develop web services 
4th - visualise them on NationalMap and other applications

Some links to start with:

Fire information:

- [x] NSW - Rural Fire Service - https://www.rfs.nsw.gov.au/about-us/contact-us
- https://www.arcgis.com/home/webmap/viewer.html?webmap=2168b5162d61432c8b3499818a2d60df&extent=147.1007,-36.3499,150.5834,-34.9753
- https://data.nsw.gov.au/data/organization/nsw-rural-fire-service
- http://www.rfs.nsw.gov.au/news-and-media/stay-up-to-date/feeds

- [ ] VIC - Country Fire Authority - https://www.cfa.vic.gov.au/home - https://www.cfa.vic.gov.au/contact
- https://www.emergency.vic.gov.au/respond/

- [x] SA - South Australian Country Fire Service - https://www.cfs.sa.gov.au/site/home.jsp - https://www.cfs.sa.gov.au/site/about_cfs/contact_the_cfs.jsp 
- https://www.cfs.sa.gov.au/site/home.jsp
- https://apps.geohub.sa.gov.au/CFSMap/index.html
- https://services.geohub.sa.gov.au/

- [ ] WA - Landgate FireWatch map services - to contact Satellite Remote Sensing Services Operations at: srss-online@landgate.wa.gov.au and 
Department of Fire & Emergency Services https://www.dfes.wa.gov.au/Pages/default.aspx
- https://www.emergency.wa.gov.au/
- https://myfirewatch.landgate.wa.gov.au/

- [ ] TAS - Tasmania Fire Service - http://www.fire.tas.gov.au/Show?pageId=colContactUs
- http://www.fire.tas.gov.au/Show?pageId=colWhatsBurningNow
-  http://www.fire.tas.gov.au/Show?pageId=colGMapBushfires
- https://data.thelist.tas.gov.au/datagn/srv/eng/main.home?uuid=5b8c2242-4329-4571-a778-cb513f179252

- [ ] QLD - QLD Fire and Emergency Services - https://www.qfes.qld.gov.au/Pages/default.aspx - https://www.qfes.qld.gov.au/Pages/Contact-Us.aspx
- https://www.ruralfire.qld.gov.au/map/Pages/default.aspx
- https://www.ruralfire.qld.gov.au/map/Pages/mapfeeds.aspx

- [ ] NT - NT police, fire and emergency services - https://www.pfes.nt.gov.au/contact-us
- https://www.pfes.nt.gov.au/incidentmap/

- [ ] ACT - Emergency Services Agency - https://esa.act.gov.au/contact-us 
- https://esa.act.gov.au/

Traffic:
NSW - https://www.livetraffic.com/desktop.html; https://opendata.transport.nsw.gov.au/node/342/exploreapi
WA - https://catalogue.data.wa.gov.au/dataset/dbca-traffic-management
VIC - http://api.vicroads.vic.gov.au/

**Comment by tobybellwood** [comment]
ArcGIS online has two layers for VIC
https://www.arcgis.com/home/item.html?id=1a3c13a8a6ab458fbc933553f883f032
https://www.arcgis.com/home/item.html?id=dc59edbec23c4b209def4d65193c7b2b

Ping @simongis - he may have more ideas too!

**Comment by simongis** [comment]
For some of the States that had some issues getting access to their feeds, we worked with them to setup some syncs to ArcGIS Online.  

Welcome to use those services in NationalMap, won't put any pressure on the agencies infrastructure.  Reach out if you want to go down this path, can bring the various agency contacts into the conversation if required.

https://bushfires-esriau.hub.arcgis.com/

**Comment by AnaBelgun** [comment]
Thanks @simongis and @tobybellwood; we're looking into it and will email you for details

**Comment by rowanwins** [comment]
So just jotting down some notes

**NSW Fire data**
- geojson available from esri available here, seems to match the stuff used on the NSW FIresNearMe app very closely eg [here](https://services.arcgis.com/ocp0tSBogo1xXKRo/arcgis/rest/services/RFS_GeoRSS_feed_open/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=)
- Data used directly on RFS Fires Near me is https://www.rfs.nsw.gov.au/feeds/majorIncidents.json
- Some of the data used for styling is contained with a `description` field as HTML (see example below)
  - I thing we'd want to pull out `STATUS` for example
  - `ALERT LEVEL` appears to be available in  a seperate field called `category`
````
{
   "description": 
        "ALERT LEVEL: Advice <br />
        LOCATION: 1650 Blue Springs Rd, Stubbo, NSW 2852 <br />
        COUNCIL AREA: Mid-Western <br />
        STATUS: Under control <br />
        TYPE: Grass Fire <br />
        FIRE: Yes <br />
        SIZE: 0 ha <br />
        RESPONSIBLE AGENCY: Rural Fire Service <br />
        UPDATED: 8 Jan 2020 04:12"
}
````
- The Fires Near Me App has a very simple symbology
![NSW](https://user-images.githubusercontent.com/6735870/71939962-93432600-3208-11ea-8c17-fa47251e64ca.png)


**VIC Fire data**
- geojson available from esri here, although appears to be simplified version of what's available on https://emergency.vic.gov.au/, I'm not sure it contains the required attributes - [eg here](https://services1.arcgis.com/vHnIGBHHqDR6y0CR/arcgis/rest/services/VIC_Incidents_from_EMV/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=)
- The VIC website uses data directly from https://emergency.vic.gov.au/public/osom-geojson.json
  - it has much more detailed properties
- In general the VIC data has a wider range of attributes although not consistently named with NSW and has different values
- Symbology on the site is more detailed
![Vic](https://user-images.githubusercontent.com/6735870/71940184-7f4bf400-3209-11ea-926e-c2404f0f1e85.png)

**Comment by simongis** [comment]
Happy to answer some of those issues around differences, but think we might be in luck.
EMSINA will be releasing a national bushfire boundary layer web service (some states still in progress...)

This will initially cover TAS/ACT/VIC/NSW/SA

Will be hosted in ArcGIS Online.

Will report back

**Comment by rowanwins** [comment]
Awesome - thanks for the update @simongis

**Comment by simongis** [comment]
Update:  It will be just the extents for starters.  Hopefully released tomorrow.

**Comment by simongis** [comment]
EMSINA have put out an early release of their Bushfire Boundaries.
They are working on some of the missing states and incidents.  

There is DCAT (for CKAN/Data.gov.au), GeoJSON, WFS endpoints that can be crawled from Data.gov.au and National Map if required.  @tobybellwood has helped enable this in the past.

Sing out if any Qs.  EMSINA contacts can be found in the Metadata  


Australian Bushfire Boundaries from EMSINA  (Esri Shops)
https://www.arcgis.com/home/item.html?id=5c7f580b60ef457e8819441e598c4366

Australian Bushfire Boundaries from EMSINA - WFS:  (Non Esri Shops)
https://www.arcgis.com/home/item.html?id=0f7c0f0aa3244da0a8e1771b0807e87c

Very Simple Web App:
https://www.arcgis.com/home/item.html?id=3c2316fbd7de4dbbbcbc9c40de91004c

Bushfire Resources in ArcGIS Online
https://bushfires-esriau.hub.arcgis.com/

![image](https://user-images.githubusercontent.com/2769383/72032553-cf978480-32e3-11ea-9a81-9ebff8478857.png)

**Comment by AnaBelgun** [comment]
Thank you for the update @simongis; we're working with the EM-LINK group to get these services on NationalMap (initially in staging). Will keep you posted through this ticket. Thanks again for all the updates.

**Comment by simongis** [comment]
Excellent.  Let me know if there is anything you need from the Esri side.

**Comment by simongis** [comment]
Note that GA have had to use new endpoints for the services as of about 20 minutes ago.
Now includes Area attributes
