### ISSUE TITLE
NatMap - Feb 2020 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#950]
- [x] update WA CKAN catalogue - https://github.com/TerriaJS/nationalmap/issues/946 and https://github.com/TerriaJS/nationalmap/issues/940

- [x] add more Forests: https://github.com/TerriaJS/nationalmap/issues/943

- [x] updated ABS national boundaries links: https://github.com/TerriaJS/NationalMap-Catalog/pull/158 and https://github.com/TerriaJS/NationalMap-Catalog/pull/159

**Comment by mwu2018** [comment]
WA CKAN catalogues grant public (unauthenticated) access to metadata. However, many datasets contains resources that only grant access to authenticated users (free sign on), resulting in those catalogue items being unable to be added to the map (`Loading...` spins forever).

**Comment by mwu2018** [comment]
Version `2020-03-20b` is now running at `https://staging.nm.terria.io`.

**Comment by AnaBelgun** [comment]
27 March - no comments received from the WA team on their data; will proceed to send the release to GA
