### ISSUE TITLE
Update ABS boundaries 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#954]
Currently NatMap uses the following map server url for the ABS Census boundaries: 
http://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/ASGS2016BoundariesOnline/MapServer/12
which throws a 404 error 
![image](https://user-images.githubusercontent.com/18452161/76809128-f0c5a580-683d-11ea-8810-8fd49ecf3134.png)

If this map server address is used, all the layers work: https://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/SA1/MapServer

https://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016

Action: 
- to replace all layers under Statistical Boundaries - ABS Statistical Boundaries - 2016 with the new map server url
- to replace the LGA 2016 and Postal Areas 2016 under National Boundaries (they are part of same Census old server)

**Comment by rowanwins** [comment]
From what I can tell this has been done
