### ISSUE TITLE
data.gov.au - to add to corsDomain - to discuss

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#967]
data.gov.au to corsDomains so it doesn’t need to be proxied

**Comment by soyarsauce** [comment]
@AnaBelgun 
Is there a historical reason to why DGA needs to be proxied? Are there performance reasons relating to non-magda DGA, or the fact that it didn't do CORS at one point but does now?

**Comment by AnaBelgun** [comment]
Not really. at least I can't remember why it didn't do CORS before. Let's change it in one - off release before V8 rollout

**Comment by rowanwins** [comment]
Done in #166
