### ISSUE TITLE
NationalMap - Sep 20 (catalogue only) release (on Master) 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#970]
- [x] just to add a modal / message on landing informing users a new NatMap is being prepared and this version will no longer be supported etc etc - https://github.com/TerriaJS/nationalmap/issues/971 - this is being added in Aug release

- [x] DEA needs a catalogue only release mid - Sep 2020 of CEMP InSAR data https://terria-cube.terria.io/#share=s-si1cdVJmnL3xLi4HzSjEHLtQvRT - currently under development 

This is the merged version in Digital Earth Australia catalogue: https://github.com/GeoscienceAustralia/dea-config/pull/581
Needs to be included in NationalMap under NSW data group.

**Comment by steve9164** [comment]
Done. See new datasets here: https://nationalmap.gov.au/#share=s-mz9x4LHZaa3kQPWeMQVWFsTg07I

**Comment by steve9164** [comment]
See also TerriaJS/NationalMap-Catalog#169
