### ISSUE TITLE
Investigate and add DoH COVID data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#973]
- [ ] check the following open data services available on the DoH hub https://department-of-health-covid-19-resources-australianhealth.hub.arcgis.com/ 

- [ ] check the issue with WFS https://bushfires-esriau.hub.arcgis.com/pages/wfs-access-issues 

- [ ] if WFS is not an option, check the geoJSON version (example here Assessment Centres) https://opendata.arcgis.com/datasets/4dc6aef41a1e4aff84bbe44947bbe78f_0.geojson and see if legends can be improved https://nationalmap.gov.au/#share=s-rJjj1qMQITQk0U28wYEQ0VvUpmJ 

- [ ] should geoJSON work and legend can be tweaked, add to catalogue under Health group

**Comment by rowanwins** [comment]
Looks like this could be added using the `ArcGisPortalCatalogGroup`

This is the query being triggered on the page, that search query can be passed in as a parameter to the `ArcGisPortalCatalogGroup` model.

````
https://www.arcgis.com/sharing/rest/search?f=json&q=id:4dc6aef41a1e4aff84bbe44947bbe78f OR id:9b5ed09807054a4aa54ae469f86b5602 OR id:78aa0bc22286463fb4864416c830f0b8 OR id:3f0cd2ae420449469cca4f8f37835219 OR id:b045de436c484e94a60882f92627312e OR id:4102902d09bf4eb8a26b00d70a119a52 OR id:8b178f82740849128c060a71f6f1e19f OR id:170f73e1724c4055bfaeb1d078bc344f OR id:6fc59e452be7465c8683d4cb3ac6772e OR id:a3fabf3192384a95ae7cba8dc2b8617d OR id:6890fccede4a4453a4bd8c17932a4ce3
````

**Comment by rowanwins** [comment]
Something like this I think

````
{
  "type": "arcgis-portal-group",
  "name": "Department of Health COVID-19 Resources",
  "url": "https://www.arcgis.com",
  "searchParams": {
        "q": "id:4dc6aef41a1e4aff84bbe44947bbe78f OR id:9b5ed09807054a4aa54ae469f86b5602 OR id:78aa0bc22286463fb4864416c830f0b8 OR id:3f0cd2ae420449469cca4f8f37835219 OR id:b045de436c484e94a60882f92627312e OR id:4102902d09bf4eb8a26b00d70a119a52 OR id:8b178f82740849128c060a71f6f1e19f OR id:170f73e1724c4055bfaeb1d078bc344f OR id:6fc59e452be7465c8683d4cb3ac6772e OR id:a3fabf3192384a95ae7cba8dc2b8617d OR id:6890fccede4a4453a4bd8c17932a4ce3"
      }
}
````

**Comment by reginapramesti** [comment]
Ah right so is that the way to add them to the catalogue all at once? I thought we wanted to do it one at a time and the only way that seemed feasible was to use the geojson 😆 

Since `ArcGisPortalCatalogGroup` is only available on mobx, is this something to be added once nationalmap is on mobx? Or do we want a temporary solution using geojson?

**Comment by rowanwins** [comment]
Urgh completely forgot about that.

By the looks of it most of them are Esri Feature Servers so you should be able to configure them one by one like so
````
{
  "name": "Australian COVID19 Assessment Centres",
  "type": "esri-featureServer",
  "url": "https://services5.arcgis.com/OvOcYIrJnM97ABBA/arcgis/rest/services/Australian_COVID19_Assessment_Centres_WFL1/FeatureServer/0"
}
````

**Comment by reginapramesti** [comment]
Oh I see I shouldn't include this part of the URL `query?where=1%3D1&outFields=*&outSR=4326&f=json` 🤦 I was wondering why it wasn't working but now that seems easy enough
