### ISSUE TITLE
Review NationalMap catalogue 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#985]
- [ ] review and update current NationalMap catalogue ahead of Dec release 

Catalogue structure master spreadsheet: https://drive.google.com/file/d/1WeGabxusQzs2eKPvz3t0jz7tWtUpBS8-/view?usp=sharing

**Comment by nf-s** [comment]
- [ ] Go through ABS SDMX dataflows - make sure region mapping is working as expected - make sure default values are sensible
- [ ] Add YDYR

**Comment by AnaBelgun** [comment]
done
