### ISSUE TITLE
GA layers to update post 5 January 2021

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#986]
Hi all

This is to advise of a number of web services that are being decommissioned or have been migrated to the cloud including advising of any replacement services.

To be decommissioned on the 5th January 2021:

1.	Shoreline_WM (http://services.ga.gov.au/gis/rest/services/Shoreline_WM/MapServer)
This service is replaced by: https://services.ga.gov.au/gis/rest/services/Australian_Shoreline/MapServer 

2.	Surface_Hydrology_WM (http://services.ga.gov.au/gis/rest/services/Surface_Hydrology_WM/MapServer)
This service is replaced by: https://services.ga.gov.au/gis/rest/services/Surface_Hydrology/MapServer 

3.	Proximity_To_Transmission_Infrastructure_Lines_WM
(http://services.ga.gov.au/gis/rest/services/Proximity_To_Transmission_Infrastructure_Lines_WM/MapServer)
There is no replacement for this service.

4.	Proximity_To_Transmission_Infrastructure_Substations_WM (http://services.ga.gov.au/gis/rest/services/Proximity_To_Transmission_Infrastructure_Substations_WM/MapServer)
There is no replacement for this service.

5.	NEXIS Agricultural Exposure (http://services.ga.gov.au/gis/rest/services/NEXIS_Agricultural_Exposure/MapServer)
The contents of this service was being duplicated in Australian Exposure Information service and can be found here: https://services.ga.gov.au/gis/rest/services/Australian_Exposure_Information/MapServer

6.	CWTH_OMA_1994_Mineral_Blocks_AMB2006a_WM (http://services.ga.gov.au/gis/rest/services/CWTH_OMA_1994_Mineral_Blocks_AMB2006a_WM/MapServer)
Only the two most recent epochs (2014 & 2020) will be retained, therefore there is no replacement for this service.

7.	CWTH_OPGGSA_2006_Petroleum_Blocks_AMB2001a (https://services.ga.gov.au/gis/rest/services/CWTH_OPGGSA_2006_Petroleum_Blocks_AMB2001a/MapServer)
Only the two most recent epochs (2014 & 2020) will be retained, therefore there is no replacement for this service.

8.	CWTH_OPGGSA_2006_Petroleum_Blocks_AMB2006a (https://services.ga.gov.au/gis/rest/services/CWTH_OPGGSA_2006_Petroleum_Blocks_AMB2006a/MapServer)
Only the two most recent epochs (2014 & 2020) will be retained, therefore there is no replacement for this service.

Migrated to the cloud and with some shortening of layer names. The old services will be turned off on 5th January 2021 and the migrated services are available now:
9.	Australian_Maritime_Boundary_Treaties_AMB2014a  (http://services.ga.gov.au/gis/rest/services/Australian_Maritime_Boundary_Treaties_AMB2014a/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/Treaties_Australian_Maritime_Boundaries_AMB2014a/MapServer 

10.	CWTH_CW_Act_1980_Coastal_Waters_AMB2014a (http://services.ga.gov.au/gis/rest/services/CWTH_CW_Act_1980_Coastal_Waters_AMB2014a/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/CW_1970_1980_AMB2014a/MapServer 

11.	CWTH_OMA_1994_Mineral_Blocks_AMB2014a_WM (http://services.ga.gov.au/gis/rest/services/CWTH_OMA_1994_Mineral_Blocks_AMB2014a_WM/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/OMA_1994_Mineral_Blocks_AMB2014a/MapServer 

12.	CWTH_OPGGSA_2006_Petroleum_Blocks_AMB2014a (https://services.ga.gov.au/gis/rest/services/CWTH_OPGGSA_2006_Petroleum_Blocks_AMB2014a/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/OPGGSA_2006_Petroleum_Blocks_AMB2014a/MapServer 

13.	CWTH_OPGGSA_2006_AMB2014a (http://services.ga.gov.au/gis/rest/services/CWTH_OPGGSA_2006_AMB2014a/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/OPGGSA_2006_Areas_AMB2014a/MapServer 

14.	SSLA_1973_AMB2014a_WM (https://services.ga.gov.au/gis/rest/services/SSLA_1973_AMB2014a_WM/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/SSLA_1973_AMB2014a/MapServer 

15.	SSLA_1973_AMB2014a (http://services.ga.gov.au/gis/rest/services/SSLA_1973_AMB2014a/MapServer)
Migrated service at: https://services.ga.gov.au/gis/rest/services/SSLA_1973_AMB2014a/MapServer

**Comment by mwu2018** [comment]
Most of the listed items are not in the national map catalog that is specified by http://static.nationalmap.nicta.com.au/init/2020-09-03.json, except for item 5. Should we add them to the catalog?

**Comment by AnaBelgun** [comment]
@mwu2018 yes please

**Comment by mwu2018** [comment]
The current nationalmap deployment is based on terriajs v7 and its catalog is defined by http://static.nationalmap.nicta.com.au/init/2020-09-03.json. I assume that we will roll out v8 nationalmap soon and its catalog is specified by http://static.nationalmap.nicta.com.au/init/2020-12-18-converted-v8.json. Should we target v7 or v8?

**Comment by AnaBelgun** [comment]
@mwu2018 definitely v8. we're decommissioning v7 in the next month.

**Comment by steve9164** [comment]
@steve9164, @mwu2018 & @nf-s to discuss and document how to handle NationalMap catalogue changes.

**Comment by mwu2018** [comment]
Please see 9 new datasets and 1 updated in this PR https://github.com/TerriaJS/natmap-catalog-v8/pull/10

**Comment by nf-s** [comment]
Looks good, will push new catalog to prod next week
