### ISSUE TITLE
NationalMap v8 - stand alone app

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#990]
Due to current arrangements between agencies, NationalMap v8 should be a stand alone platform. Release should follow the current process until further notice from partners. 

Update 31 Aug 2021: 
- when releasing NatMap standalone, pls don't forget to include Related Maps: https://github.com/TerriaJS/nationalmap/issues/1054

**Comment by nf-s** [comment]
What I mean by "implement of simple SaaS method" - is to use magda-map-config format in TerriaMap 

See https://saas.terria.io/api/v0/registry-auth/records/map-config-nationalmap?optionalAspect=terria&optionalAspect=terria-saas&optionalAspect=terria-config&optionalAspect=terria-init&optionalAspect=group&dereference=true

This is so we don't have to configure anything directly in TerriaMap/TerriaJS repos - it is all JSON

**Comment by nf-s** [comment]
When making standalone - and transferring about pages over - make sure to remove "Help page" - https://github.com/TerriaJS/nationalmap/issues/998

**Comment by wibily** [comment]
- upgrade terriajs to v8
- migrate over config.json & related from sass
- migrate over help pages

crispy: is it easier to migrate terriamap main into nationalmap or just fork terriamap again?

**Comment by wibily** [comment]
related to this ticket is Pete's ticket on whether or not we can containerise our deployable to GA

**Comment by steve9164** [comment]
Additional information:
* GA will continue to deploy nationalmap using the same process (cloudformation + tarballs)
* We should merge `TerriaMap/main` into `nationalmap` and not fork TerriaMap again.

Proposed steps:
* Follow https://docs.terria.io/guide/contributing/migration-guide/ (except for initialization file conversion, which isn't needed)
    * Merge `TerriaMap/main` into `nationalmap/master`, push to nationalmap repo
* Notify a TerriaJS admin (Pete or @steve9164) to rename `master` as `main`. Unlike TerriaMap, we will not make a `terriajs7` branch of nationalmap.
* Work out how nationalmap used to work with NationalMap-Catalog repo and do a similar thing (or propose a more sensible alternative) with natmap-catalog-v8 (we should also archive one repo - either NationalMap-Catalog or move the contents of natmap-catalog-v8 to NationalMap-Catalog and archive natmap-catalog-v8)
* Discuss with the team (especially @nf-s and @steve9164) whether we want to move config from our map-config files into the wwwroot/config.json file
    * Ascertain whether nationalmap can be configured as it is in saas by copying config from saas-catalogs repo into wwwroot/config.json
* Test npm installing, building (including a release build with `gulp release`)
* Test making a tarball (I can't remember what the name of that gulp task is)
* Read through `npm run deploy` script and other scripts that it calls and see if any need updating
* Test `npm run deploy`
