### ISSUE TITLE
NationalMap v7 release - redraft landing modal 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#991]
Current landing modal

![image](https://user-images.githubusercontent.com/18452161/106418387-4c2a7180-64aa-11eb-9c90-a75b5de8e78b.png)

Dear AREMI users 
please check the Energy data group in NationalMap Beta (https://nationalmap.prod.saas.terria.io/#share=s-uQvnloR2FjBbnr9SlMMAwfBHcca) version to access electricity and renewables datasets.

**Comment by AnaBelgun** [comment]
NationalMap v2.0 is now on beta!

Hello everyone! We’re counting on you to shape the future release of NationalMap 2.0!
We have developed the new version of NationalMap on the latest TerriaJS and we need the community to take it for a test drive. Users have new tools for onboarding and help, an improved user interface and more datasets from the Australian open data platform, data.gov.au.
Let us know what you think of this release on NationalMap 2.0 on Beta [https://nationalmap.prod.saas.terria.io/] by emailing info@terria.io.

Dear AREMI users
please check the Energy data group in NationalMap Beta (https://nationalmap.prod.saas.terria.io/#share=s-uQvnloR2FjBbnr9SlMMAwfBHcca) version to access electricity and renewables datasets.

**Comment by na9da** [comment]
Added the message for AREMI users - http://nationalmap-2021-02-02b.nm.terria.io/

**Comment by AnaBelgun** [comment]
done
