### ISSUE TITLE
NationalMap - Feb 2021 (V7) release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#996]
Based on the users feedback and issues with discovery of AREMI data in NationalMap Beta v8, we could help users by temporarily integrating AREMI v7 catalogue groups into NationalMap v7 catalogue. 
The following groups in AREMI v7: 
- Electricity 
- Renewable Energy 
- Electric Vehicles 

to be transferred to NationalMap v7 Energy group. 

In addition, the landing page message should be updated to further clarify the actions of: 
- test NationalMap v8
- find AREMI data 
- send feedback 

The release will need a catalogue and code release as well to solve the proxy or cors issues with some of AREMI data (such as the ISF - Network opportunities).

**Comment by AnaBelgun** [comment]
Landing page message: 
![image](https://user-images.githubusercontent.com/18452161/106706179-63e92d80-6643-11eb-82e9-14beda9b4674.png)

the AREMI paragraph should have the same format size as the rest

<a href="https://nationalmap.prod.saas.terria.io/" target="_blank">Click here to test NationalMap v2.0 Beta</a>!

**Comment by steve9164** [comment]
Progress in #1000.

Tasks to release v7:
- [x] Groups extracted and copied across
- [x] Regionmapping updated for ISF
- [x] Catalog released under tag `2021-02-04`
- [x] Catalog file uploaded and privateclientconfig updated
- [ ] Landing page message updated (partial work included in above PR)
- [ ] Check that all the necessary `allowProxyFor` domains are copied from AREMI to nationalmap
- [ ] Test data
- [ ] Stuff I've forgotten
- [ ] Send to GA

**Comment by AnaBelgun** [comment]
@na9da post testing: 

- [ ] to check the issue with Electric Vehicle Avg Hourly and Daily Traffic Volumes
- [ ] to remove the Feedlot Waste from Energy - Renewables - Bioenergy - WA 
- [ ] to check the error with Oil Malee Stems and Grape Mac from Energy - Renewables - Bioenergy - WA
- [ ] to leave the Network Opportunities (Supporting Information - Distribution cables and substation) until Geoserver is back up again

**Comment by na9da** [comment]
> to check the error with Oil Malee Stems and Grape Mac from Energy - Renewables - Bioenergy - WA

These 2 data sets seem to be working for me!

https://nationalmap-2021-02-05c.nm.terria.io/#share=s-ex0esByXzhHw9gUG2GufqOa9AVB

**Comment by AnaBelgun** [comment]
done; https://nationalmap.gov.au/
