### ISSUE TITLE
Legend URLs 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#999]
- [x]  Make sure legend URLs are all PROXIED

- [x]  Test styles LegendURL

- [x]  Test custom legend in catalog JSON

**Comment by AnaBelgun** [comment]
- [ ] TerriaJS v8 bug with proxying legends 
- [ ] no advertisement for creating legend graphic (trait - support legend graphic to be set to "true")

**Comment by AnaBelgun** [comment]
related issues: 
- https://github.com/TerriaJS/terriajs/issues/5021 
- https://github.com/TerriaJS/terriajs/issues/5048

**Comment by nf-s** [comment]
PRs:

- [ ] https://github.com/TerriaJS/terriajs/pull/5247
- [ ] https://github.com/TerriaJS/terriajs/pull/5144
